### ISSUE TITLE
Fix config_group test: test_create_negative_1

### ISSUE THREAD

**Issue by sghai** [SatelliteQE/robottelo#1285]
Error Message
```
Search box not found.
```
Stacktrace
```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "/home/jenkins/shiningpanda/jobs/00db9532/virtualenvs/d41d8cd9/lib/python2.7/site-packages/ddt.py", line 114, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jenkins/workspace/satellite6-automation/DISTRO/rhel7/ENDPOINT/ui/PROJ/downstream/PYTHON/System-CPython-2.7/tests/foreman/ui/test_config_groups.py", line 79, in test_create_negative_1
    search = self.configgroups.search(name)
  File "/home/jenkins/workspace/satellite6-automation/DISTRO/rhel7/ENDPOINT/ui/PROJ/downstream/PYTHON/System-CPython-2.7/robottelo/ui/configgroups.py", line 44, in search
    locators["config_groups.select_name"])
  File "/home/jenkins/workspace/satellite6-automation/DISTRO/rhel7/ENDPOINT/ui/PROJ/downstream/PYTHON/System-CPython-2.7/robottelo/ui/base.py", line 76, in search_entity
    raise Exception("Search box not found.")
Exception: Search box not found.
```

**Comment by oshtaier** [comment]
Issue is more general and should be resolved in #2091
