### ISSUE TITLE
Fix tests.foreman.smoke.test_ui_smoke.TestSmoke.end_to_end_ui_test

### ISSUE THREAD

**Issue by omaciel** [SatelliteQE/robottelo#1553]
Please take a look at the latest nightly run in Jenkins and look into what's causing this error in our smoke test suite.

```bash
======================================================================
ERROR: @Test: Perform end to end smoke tests using RH repos.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jenkins/workspace/satellite6-smoke/DISTRO/rhel65/PROJ/upstream/PYTHON/System-CPython-2.7/tests/foreman/smoke/test_ui_smoke.py", line 267, in end_to_end_ui_test
    self.sync.enable_rh_repos(repos)
  File "/home/jenkins/workspace/satellite6-smoke/DISTRO/rhel65/PROJ/upstream/PYTHON/System-CPython-2.7/robottelo/ui/sync.py", line 168, in enable_rh_repos
    (strategy3, value3 % repo_name), 60).click()
AttributeError: 'NoneType' object has no attribute 'click'
```

**Comment by sghai** [comment]
Issue is already fixed in referenced PR #1561. Closing this now..
