### ISSUE TITLE
Fix failed activation-key and content-view tests

### ISSUE THREAD

**Issue by sghai** [SatelliteQE/robottelo#1843]
A bunch of UI activation-key and content-view tests are failing due to following issue:

Error Message
```
u'success' != u'error'
- success
+ error
```
Stacktrace
```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "/home/jenkins/shiningpanda/jobs/96e4b58e/virtualenvs/d41d8cd9/lib/python2.7/site-packages/ddt.py", line 163, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jenkins/workspace/satellite6-automation@2/DISTRO/rhel66/ENDPOINT/ui/PROJ/upstream/PYTHON/System-CPython-2.7/tests/foreman/ui/test_activationkey.py", line 215, in test_positive_create_activation_key_3
    self.cv_publish_promote(cv_name, env_name, repo_id)
  File "/home/jenkins/workspace/satellite6-automation@2/DISTRO/rhel66/ENDPOINT/ui/PROJ/upstream/PYTHON/System-CPython-2.7/tests/foreman/ui/test_activationkey.py", line 125, in cv_publish_promote
    self.assertEqual(u'success', content_view.publish()['result'])
  File "/usr/lib64/python2.7/unittest/case.py", line 553, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib64/python2.7/unittest/case.py", line 964, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/lib64/python2.7/unittest/case.py", line 450, in fail
    raise self.failureException(msg)
AssertionError: u'success' != u'error'
- success
+ error
```

**Comment by sghai** [comment]
This is not an automation issue..its something related to product itself. Keeping this open until the issue get fixed.

-
ERF12-4115 [ProxyAPI::ProxyException]: Unable to get classes from Puppet for
KT_FLroGDT3UX_ilMwJQdmVG_xRCEOKGtxC_10 ([RestClient::NotAcceptable]: 406 Not
Acceptable) for proxy https://:9090/puppet
--

**Comment by Ichimonji10** [comment]
See [BZ 11846432](https://bugzilla.redhat.com/show_bug.cgi?id=1186432), #1869 and #1873.

**Comment by elyezer** [comment]
This issue is not valid anymore. Closing it.
