### ISSUE TITLE
fix all tests related to param settings

### ISSUE THREAD

**Issue by sghai** [SatelliteQE/robottelo#1875]
Error Message
```
Couldn't find edit button to update selected param
```
Stacktrace
```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "/home/jenkins/shiningpanda/jobs/d2e7576f/virtualenvs/d41d8cd9/lib/python2.7/site-packages/ddt.py", line 146, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jenkins/workspace/satellite6-automation-upstream-rhel66/ENDPOINT/ui/PYTHON/System-CPython-2.7/tests/foreman/ui/test_settings.py", line 566, in test_positive_update_auth_param_19
    param_value=test_data['param_value'])
  File "/home/jenkins/workspace/satellite6-automation-upstream-rhel66/ENDPOINT/ui/PYTHON/System-CPython-2.7/robottelo/ui/factory.py", line 507, in edit_param
    Settings(session.browser).update(**update_args)
  File "/home/jenkins/workspace/satellite6-automation-upstream-rhel66/ENDPOINT/ui/PYTHON/System-CPython-2.7/robottelo/ui/settings.py", line 65, in update
    "Couldn't find edit button to update selected param")
UINoSuchElementError: Couldn't find edit button to update selected param
```

**Comment by sghai** [comment]
Looks like issue is with locator.. it will fix 4 more issues.

**Comment by sghai** [comment]
In 'test_positive_update_auth_param_19', the param is renamed 
from:
`require_ssl_puppetmaster`
to:
`require_ssl_smart_proxies`

```
<sghai> guys: I noticed.. we had  param under settings --> auth -> "require_ssl_puppetmasters".. i don't see in recent nightly ?
<stbenjam> sghai: renamed to require_ssl_smart_proxies
```

**Comment by sghai** [comment]
In 'test_positive_update_auth_param_20', the param is renamed 
from:
restrict_registered_puppetmasters
to:
restrict_registered_smart_proxies

**Comment by sghai** [comment]
In 'test_positive_update_auth_param_[21,22]', the params are removed
 `signo_sso and signo_url`
```
<sghai> stbenjam, what about these params:  signo_sso and signo_url ? have been removed ?
<sghai> stbenjam, getting failures in automation..as we did some validation around these params earlier and now tests are failing...so checking
<mhulan> sghai: yes, they were removed, we don't need signo anymore
```

**Comment by sghai** [comment]
So I'll update test_positive_update_auth_param_[19,20] and remove test_positive_update_auth_param_[21,22] as per above comments.

**Comment by sghai** [comment]
PR raised: https://github.com/SatelliteQE/robottelo/pull/1876

**Comment by sghai** [comment]
Closing this now as PR got merged..
