### ISSUE TITLE
Fix Page Submission failed error for Verified bug Test: tests.foreman.ui.test_syncplan.Syncplan.test_positive_create_3

### ISSUE THREAD

**Issue by jyejare** [SatelliteQE/robottelo#2037]
'Page Submission failed ' error shown for test .test_positive_create_3 dependent on Verified bug BZ: 1131661. Creating a Sync plan with date but not verifying the date is correctly displayed or not. Closing the browser immediately after creating sync plan.

StackTrace:
```
Traceback (most recent call last):
  File "/home/jyejare/Desktop/RedHat/RobotteloTop/robottelo/robottelo/common/decorators.py", line 362, in wrapper_func
    return func(*args, **kwargs)
  File "/home/jyejare/Desktop/RedHat/RobotteloTop/robottelo/tests/foreman/ui/test_syncplan.py", line 147, in test_positive_create_3
    description=description, startdate=startdate_str)
  File "/home/jyejare/Desktop/RedHat/RobotteloTop/robottelo/robottelo/ui/factory.py", line 552, in make_syncplan
    Syncplan(session.browser).create(**create_args)
  File "/home/jyejare/Desktop/RedHat/RobotteloTop/robottelo/robottelo/ui/syncplan.py", line 54, in create
    validation=submit_validate)
  File "/home/jyejare/Desktop/RedHat/RobotteloTop/robottelo/robottelo/ui/base.py", line 382, in submit_and_validate
    raise UIPageSubmitionFailed("Page submission failed.")
UIPageSubmitionFailed: Page submission failed.
-------------------- >> begin captured logging << --------------------
root: INFO: Bugzilla bug 1131661 not in cache. Fetching.
py.warnings: WARNING: /usr/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

root: DEBUG: NoSuchElementException: Could not locate element //div[contains(@class, 'jnotify-notification-error')].
--------------------- >> end captured logging << ---------------------
```

**Comment by jyejare** [comment]
This issue has observed on both RHEL 6.6 and RHEL 7.1

**Comment by jyejare** [comment]
The issue here is something different other than page submission issue , the issue was the start date differs before adding and after adding the sync plan.

StackTrace;
```
File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel71-ui/robottelo/common/decorators.py", line 362, in wrapper_func
    return func(*args, **kwargs)
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel71-ui/tests/foreman/ui/test_syncplan.py", line 153, in test_positive_create_3
    self.assertEqual(saved_startdate, fetch_startdate)
  File "/usr/lib64/python2.7/unittest/case.py", line 553, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib64/python2.7/unittest/case.py", line 546, in _baseAssertEqual
    raise self.failureException(msg)
'\'Apr 23\' != \'Apr 24\'\n-------------------- >> begin captured logging << --------------------\nrobottelo.ui.locators: DEBUG: Accessing locator "sp.fetch_startdate" by xpath: "//span[contains(.,\'Start Date\')]/../span[contains(@class,\'info-value\')]"\nrobottelo.ui.locators: DEBUG: Accessing locator "login.username" by id: "login_login"\nrobottelo.ui.locators: DEBUG: Accessing locator "login.username" by id: "login_login"\nrobottelo.ui.locators: DEBUG: Accessing locator "login.password" by id: "login_password"\nrobottelo.ui.locators: DEBUG: Accessing locator "submit" by name: "commit"\nrobottelo.ui.locators: DEBUG: Accessing locator "notif.error" by xpath: "//div[contains(@class, \'jnotify-notification-error\')]"\nrobottelo.ui.locators: DEBUG: Accessing locator "menu.current_text" by xpath: "//div[contains(@style,\'static\') or contains(@style,\'fixed\')]//li[contains(@class,\'org-switcher\')]/a"\nrobottelo.ui.locators: DEBUG: Accessing locator "menu.fetch_org" by xpath: "//div[contains(@style,\'static\') or contains(@style, \'fixed\')]//li[contains(@class, \'org-menu\')]/a"\nrobottelo.ui.locators: DEBUG: Accessing locator "menu.fetch_loc" by xpath: "//div[contains(@style,\'static\') or contains(@style, \'fixed\')]//li[contains(@class, \'loc-menu\')]/a"\nrobottelo.ui.locators: DEBUG: Accessing locator "menu.any_context" by xpath: "//div[contains(@style,\'static\') or contains(@style,\'fixed\')]//li[contains(@class,\'org-switcher\')]/a"\nrobottelo.ui.locators: DEBUG: Accessing locator "org.nav_current_org" by xpath: "(//div[contains(@style,\'static\') or contains(@style,\'fixed\')]//li[contains(@class,\'org-switcher\')]//li/a[@data-toggle=\'dropdown\'])[1]"\nrobottelo.ui.locators: DEBUG: Accessing locator "org.select_org" by xpath: "//div[contains(@style,\'static\') or contains(@style,\'fixed\')]//a[@href=\'/organizations/clear\']/../../li/a[contains(.,\'%s\')]"\nrobottelo.ui.locators: DEBUG: Accessing locator "menu.current_text" by xpath: "//div[contains(@style,\'static\') or contains(@style,\'fixed\')]//li[contains(@class,\'org-switcher\')]/a"\nrobottelo.ui.locators: DEBUG: Accessing locator "menu.fetch_org" by xpath: "//div[contains(@style,\'static\') or contains(@style, \'fixed\')]//li[contains(@class, \'org-menu\')]/a"\nrobottelo.ui.locators: DEBUG: Accessing locator "menu.content" by xpath: "//div[contains(@style,\'static\') or contains(@style, \'fixed\')]//a[@id=\'content_menu\']"\nrobottelo.ui.locators: DEBUG: Accessing locator "menu.sync_plans" by xpath: "//div[contains(@style,\'static\') or contains(@style, \'fixed\')]//a[@id=\'menu_item_sync_plans\']"\nrobottelo.ui.locators: DEBUG: Accessing locator "sp.new" by xpath: "//button[@ui-sref=\'sync-plans.new\']"\nrobottelo.ui.locators: DEBUG: Accessing locator "name" by id: "name"\nrobottelo.ui.locators: DEBUG: Accessing locator "description" by id: "description"\nrobottelo.ui.locators: DEBUG: Accessing locator "sp.start_date" by id: "startDate"\nrobottelo.ui.locators: DEBUG: Accessing locator "create" by xpath: "//button[contains(@ng-click,\'Save\')]"\nrobottelo.ui.locators: DEBUG: Accessing locator "sp.select" by xpath: "//a[contains(@href,\'info\') and contains(.,\'%s\')]"\nrobottelo.ui.locators: DEBUG: Accessing locator "kt_search" by xpath: "//input[@ng-model=\'table.searchTerm\']"\nrobottelo.ui.locators: DEBUG: Accessing locator "kt_search_button" by xpath: "//button[@ng-click=\'table.search(table.searchTerm)\']"\nrobottelo.ui.locators: DEBUG: Accessing locator "sp.select" by xpath: "//a[contains(@href,\'info\') and contains(.,\'%s\')]"\nrobottelo.ui.locators: DEBUG: Accessing locator "kt_search" by xpath: "//input[@ng-model=\'table.searchTerm\']"\nrobottelo.ui.locators: DEBUG: Accessing locator "kt_search_button" by xpath: "//button[@ng-click=\'table.search(table.searchTerm)\']"\n--------------------- >> end captured logging << ---------------------'
```
