### ISSUE TITLE
Fix could not update operating system issue error in test : tests.foreman.ui.test_operatingsys.OperatingSys.test_update_os_medium

### ISSUE THREAD

**Issue by jyejare** [SatelliteQE/robottelo#2042]
Fill the error is because it is not able to search out the requested os parameter due to double quotes added to os parameter while searching. Remove them should do the trick.

StackTrace:
```
Traceback (most recent call last):
  File "/home/jyejare/Desktop/RedHat/RobotteloTop/robottelo/tests/foreman/ui/test_operatingsys.py", line 351, in test_update_os_medium
    self.operatingsys.update(os_name, new_mediums=[medium_name])
  File "/home/jyejare/Desktop/RedHat/RobotteloTop/robottelo/robottelo/ui/operatingsys.py", line 147, in update
    "Could not update the operating system '%s'" % os_name)
Exception: Could not update the operating system '맆𝟁﨎拺भ黾ڇꯄ縐𤽲旇옄芨鄯𣑢𧡓䡢ᆌ详𤆅や퍒𓄫믞ￜאּ뛪'
-------------------- >> begin captured logging << --------------------
py.warnings: WARNING: /usr/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

py.warnings: WARNING: /usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)

py.warnings: WARNING: /usr/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

py.warnings: WARNING: /usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)

root: DEBUG: NoSuchElementException: Could not locate element //div[contains(@class, 'jnotify-notification-error')].
root: DEBUG: TimeoutException: Timed out waiting for element '//a[contains(., '맆𝟁﨎拺भ黾ڇꯄ縐𤽲旇옄芨鄯𣑢𧡓䡢ᆌ详𤆅や퍒𓄫믞ￜאּ뛪')]' to display.
--------------------- >> end captured logging << ---------------------
```

**Comment by sghai** [comment]
taking this.. looks like issue is again with org association..

**Comment by sghai** [comment]
Fixed in PR: https://github.com/SatelliteQE/robottelo/pull/2051

**Comment by sghai** [comment]
Closing it.. as PR got merged.
