### ISSUE TITLE
Automation failure : .TestActivationKey.test_remove_host

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2131]
the test is failing in nightly

TestName:
tests.foreman.cli.test_activationkey.TestActivationKey.test_remove_host

the test is failing due to bz:
https://bugzilla.redhat.com/show_bug.cgi?id=1215628

please add the decorator to skip the test until it is fixed
thanks

**Comment by tkolhar** [comment]
The set of commands to be executed in nightly to obtain this failure is  : 

 hammer -v -u admin -p changeme --output=csv host-collection create --organization-id="213" --name="먿10𦬏10𦬏𤧔10𦬏𤧔𨫸10𦬏𤧔𨫸𣮢10𦬏𤧔𨫸𣮢𧈿㻃10𦬏𤧔𨫸𣮢𧈿𫈉㥨10𦬏𤧔𨫸𣮢𧈿𫈉𢘬"
Message,Id,Name
Host collection created,12,먿10𦬏10𦬏𤧔10𦬏𤧔𨫸10𦬏𤧔𨫸𣮢10𦬏𤧔𨫸𣮢𧈿㻃10𦬏𤧔𨫸𣮢𧈿𫈉㥨10𦬏𤧔𨫸𣮢𧈿𫈉𢘬

 hammer -v -u admin -p changeme  activation-key add-host-collection --host-collection="먿10𦬏10𦬏𤧔10𦬏𤧔𨫸10𦬏𤧔𨫸𣮢10𦬏𤧔𨫸𣮢𧈿㻃10𦬏𤧔𨫸𣮢𧈿𫈉㥨10𦬏𤧔𨫸𣮢𧈿𫈉𢘬" --name="6z41HWhVRs" --organization-id="213"
[ERROR 2015-04-26 21:30:32 Exception] undefined method `id' for nil:NilClass
Could not add host collection:
  undefined method `id' for nil:NilClass
[ERROR 2015-04-26 21:30:32 Exception] 

RestClient::InternalServerError (500 Internal Server Error):
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/abstract_response.rb:48:in `return!'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:230:in `process_result'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:178:in `transmit'
    /usr/lib/ruby/1.8/net/http.rb:543:in `start'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:172:in `transmit'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:64:in `execute'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `execute'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/resource.rb:54:in `get'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.12/lib/apipie_bindings/api.rb:279:in `send'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.12/lib/apipie_bindings/api.rb:279:in `call_client'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.12/lib/apipie_bindings/api.rb:210:in `http_call'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.12/lib/apipie_bindings/api.rb:161:in `call'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.12/lib/apipie_bindings/resource.rb:14:in `call'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli_foreman-0.1.4/lib/hammer_cli_foreman/id_resolver.rb:178:in `resolved_call'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli_foreman-0.1.4/lib/hammer_cli_foreman/id_resolver.rb:164:in `find_resource_raw'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli_foreman-0.1.4/lib/hammer_cli_foreman/id_resolver.rb:158:in `find_resource'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli_foreman-0.1.4/lib/hammer_cli_foreman/id_resolver.rb:143:in `get_id'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli_foreman-0.1.4/lib/hammer_cli_foreman/id_resolver.rb:133:in `host_collection_id'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli_foreman-0.1.4/lib/hammer_cli_foreman/commands.rb:149:in `send'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli_foreman-0.1.4/lib/hammer_cli_foreman/commands.rb:149:in `get_resource_id'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli_foreman-0.1.4/lib/hammer_cli_foreman/commands.rb:474:in `get_associated_identifier'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli_foreman-0.1.4/lib/hammer_cli_foreman/commands.rb:521:in `get_new_ids'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli_foreman-0.1.4/lib/hammer_cli_foreman/commands.rb:495:in `request_params'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4/lib/hammer_cli/./apipie/command.rb:43:in `send_request'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli_foreman-0.1.4/lib/hammer_cli_foreman/commands.rb:185:in `send_request'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4/lib/hammer_cli/./apipie/command.rb:34:in `execute'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:68:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:68:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:68:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:126:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4/bin/hammer:108
    /usr/bin/hammer:19:in `load'
    /usr/bin/hammer:19

please let me know if any clarification is needed

**Comment by tkolhar** [comment]
closing this as this issue is added a to a common github issue created for all upstream failures
