### ISSUE TITLE
Automation failure : testnames is mentioned below

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2137]
This test is failing for nightly
tests.foreman.cli.test_lifecycleenvironment.TestLifeCycleEnvironment.test_positive_update_1
tests.foreman.cli.test_lifecycleenvironment.TestLifeCycleEnvironment.test_positive_update_2

 hammer -v -u admin -p changeme --output=csv lifecycle-environment update --new-name="<iframe>NctGJzEQbugdPTo</iframe>" --id="259" --organization-id="231"
[ERROR 2015-04-26 21:57:29 Exception] Error: At least one of options --prior, --prior-id is required

See: 'hammer lifecycle-environment update --help'
Could not update environment:
  Error: At least one of options --prior, --prior-id is required
  
  See: 'hammer lifecycle-environment update --help'
[ERROR 2015-04-26 21:57:29 Exception] 

Clamp::UsageError (At least one of options --prior, --prior-id is required):
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4/lib/hammer_cli/./apipie/../abstract.rb:37:in `parse'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:68:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:68:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:126:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4/bin/hammer:108
    /usr/bin/hammer:19:in `load'
    /usr/bin/hammer:19

In nightly the expected command is as follows: 
 hammer -v -u admin -p changeme --output=csv lifecycle-environment update --new-name="xxx" --id="259" --organization-id="231" --prior Library

please fix the above issue
thanks

**Comment by tkolhar** [comment]
the help page for lifecycle environment update
------------------------------------------------------------
# hammer -v -u admin -p changeme --output=csv lifecycle-environment update --help
Message
"Usage:
    hammer lifecycle-environment update [OPTIONS]

Options:
 --description DESCRIPTION               description of the environment
 --id ID                                 ID of the environment
 --name NAME                             Lifecycle environment name to search by
 --new-name NEW_NAME                     new name to be given to the environment
 --organization ORGANIZATION_NAME        Organization name to search by
 --organization-id ORGANIZATION_ID       organization ID
 --organization-label ORGANIZATION_LABEL Organization label to search by
 --prior PRIOR                           Name of the prior enviroment
 --prior-id PRIOR_ID                     ID of an environment that is prior to the new environment in the chain. It
                                         has to be either the ID of Library or the ID of an environment at the end
                                         of a chain.
 -h, --help                              print help

**Comment by tkolhar** [comment]
this issue occurred again dated on 06/24/2015
TestNames:
tests.foreman.cli.test_lifecycleenvironment.TestLifeCycleEnvironment.test_positive_update_2
tests.foreman.cli.test_lifecycleenvironment.TestLifeCycleEnvironment.test_positive_update_1

Error Message
64 != 0

robottelo.common.ssh: DEBUG: >>> [qe-foreman-rhel71.usersys.redhat.com] LANG=en_US.UTF-8 hammer -v -u admin -p changeme --output=csv lifecycle-environment update --prior="Library" --organization-id="287" --id="314" --new-name="<applet>AmHLkoPjxGHmLZi</applet>"
robottelo.common.ssh: INFO: Instantiated Paramiko client 0x4604c10
robottelo.common.ssh: INFO: Destroying Paramiko client 0x4604c10
robottelo.common.ssh: INFO: Destroyed Paramiko client 0x4604c10
robottelo.common.ssh: DEBUG: <<< stderr
[ERROR 2015-06-24 22:04:08 Exception] Error: Unrecognised option '--prior'

See: 'hammer lifecycle-environment update --help'
Could not update environment:
  Error: Unrecognised option '--prior'
  
  See: 'hammer lifecycle-environment update --help'
[ERROR 2015-06-24 22:04:08 Exception] 

Clamp::UsageError (Unrecognised option '--prior'):
    /usr/share/gems/gems/clamp-1.0.0/lib/clamp/option/parsing.rb:62:in `find_option'
    /usr/share/gems/gems/clamp-1.0.0/lib/clamp/option/parsing.rb:28:in `parse_options'
    /usr/share/gems/gems/clamp-1.0.0/lib/clamp/command.rb:53:in `parse'
    /usr/share/gems/gems/hammer_cli-0.2.0/lib/hammer_cli/abstract.rb:31:in `parse'
    /usr/share/gems/gems/clamp-1.0.0/lib/clamp/command.rb:67:in `run'
    /usr/share/gems/gems/hammer_cli-0.2.0/lib/hammer_cli/abstract.rb:23:in `run'
    /usr/share/gems/gems/clamp-1.0.0/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/share/gems/gems/clamp-1.0.0/lib/clamp/command.rb:68:in `run'
    /usr/share/gems/gems/hammer_cli-0.2.0/lib/hammer_cli/abstract.rb:23:in `run'
    /usr/share/gems/gems/clamp-1.0.0/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/share/gems/gems/clamp-1.0.0/lib/clamp/command.rb:68:in `run'
    /usr/share/gems/gems/hammer_cli-0.2.0/lib/hammer_cli/abstract.rb:23:in `run'
    /usr/share/gems/gems/clamp-1.0.0/lib/clamp/command.rb:133:in `run'
    /usr/share/gems/gems/hammer_cli-0.2.0/bin/hammer:108:in `<top (required)>'
    /usr/bin/hammer:23:in `load'
    /usr/bin/hammer:23:in `<main>'

Stacktrace

  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "/home/jenkins/shiningpanda/jobs/74f3b441/virtualenvs/d41d8cd9/lib/python2.7/site-packages/ddt.py", line 146, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jenkins/workspace/satellite6-automation-upstream-rhel71-cli/tests/foreman/cli/test_lifecycleenvironment.py", line 251, in test_positive_update_1
    self.assertEqual(result.return_code, 0)
  File "/usr/lib64/python2.7/unittest/case.py", line 553, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib64/python2.7/unittest/case.py", line 546, in _baseAssertEqual
    raise self.failureException(msg)
'64 != 0\n--------------------

**Comment by tkolhar** [comment]
this issue occurred again dated 7/13/2015
TestNames:
tests.foreman.cli.test_lifecycleenvironment.TestLifeCycleEnvironment.test_positive_update_1
tests.foreman.cli.test_lifecycleenvironment.TestLifeCycleEnvironment.test_positive_update_2

Error Message
64 != 0

robottelo.common.ssh: DEBUG: >>> [qe-foreman-rhel66.usersys.redhat.com] LANG=en_US.UTF-8  hammer -v -u admin -p changeme --output=csv lifecycle-environment update --prior="Library" --description="ItJQODtq0703aWm" --organization-id="337" --id="308"
robottelo.common.ssh: INFO: Instantiated Paramiko client 0x4735950
robottelo.common.ssh: INFO: Destroying Paramiko client 0x4735950
robottelo.common.ssh: INFO: Destroyed Paramiko client 0x4735950
robottelo.common.ssh: DEBUG: <<< stderr
[ERROR 2015-07-14 21:49:51 Exception] Error: Unrecognised option '--prior'

See: 'hammer lifecycle-environment update --help'
Could not update environment:
  Error: Unrecognised option '--prior'
  
  See: 'hammer lifecycle-environment update --help'
[ERROR 2015-07-14 21:49:51 Exception] 

Clamp::UsageError (Unrecognised option '--prior'):
    /usr/lib/ruby/gems/1.8/gems/clamp-1.0.0/lib/clamp/option/parsing.rb:62:in `find_option'
    /usr/lib/ruby/gems/1.8/gems/clamp-1.0.0/lib/clamp/option/parsing.rb:28:in `parse_options'
    /usr/lib/ruby/gems/1.8/gems/clamp-1.0.0/lib/clamp/command.rb:53:in `parse'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.2.0/lib/hammer_cli/./apipie/../abstract.rb:31:in `parse'
    /usr/lib/ruby/gems/1.8/gems/clamp-1.0.0/lib/clamp/command.rb:67:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.2.0/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-1.0.0/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/lib/ruby/gems/1.8/gems/clamp-1.0.0/lib/clamp/command.rb:68:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.2.0/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-1.0.0/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/lib/ruby/gems/1.8/gems/clamp-1.0.0/lib/clamp/command.rb:68:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.2.0/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-1.0.0/lib/clamp/command.rb:133:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.2.0/bin/hammer:115
    /usr/bin/hammer:19:in `load'
    /usr/bin/hammer:19

Stacktrace

  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "/home/jenkins/shiningpanda/jobs/2fbde56b/virtualenvs/d41d8cd9/lib/python2.7/site-packages/ddt.py", line 146, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jenkins/workspace/satellite6-automation-upstream-rhel66-cli/tests/foreman/cli/test_lifecycleenvironment.py", line 292, in test_positive_update_2
    self.assertEqual(result.return_code, 0)
  File "/usr/lib64/python2.7/unittest/case.py", line 553, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib64/python2.7/unittest/case.py", line 546, in _baseAssertEqual
    raise self.failureException(msg)
'64 != 0\n--------------------

**Comment by tkolhar** [comment]
closing this as this issue is added a to a common github issue created for all upstream failures
