### ISSUE TITLE
Automation failure : testnames are given below

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2138]
This tests is failing for nightly:
tests.foreman.cli.test_host_collection.TestHostCollection.test_positive_update_1
tests.foreman.cli.test_host_collection.TestHostCollection.test_positive_update_2
tests.foreman.cli.test_host_collection.TestHostCollection.test_positive_update_3

 hammer -v -u admin -p changeme --output=csv host-collection update --max-content-hosts="17" --id="21" --organization-id="213"
[ERROR 2015-04-26 21:55:32 Exception] Error: Unrecognised option '--organization-id'

See: 'hammer host-collection update --help'
Could not update the the host collection:
  Error: Unrecognised option '--organization-id'
  
  See: 'hammer host-collection update --help'
[ERROR 2015-04-26 21:55:32 Exception] 

Clamp::UsageError (Unrecognised option '--organization-id'):
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/option/parsing.rb:62:in `find_option'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/option/parsing.rb:28:in `parse_options'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:53:in `parse'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4/lib/hammer_cli/./apipie/../abstract.rb:31:in `parse'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:68:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:68:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:126:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4/bin/hammer:108
    /usr/bin/hammer:19:in `load'
    /usr/bin/hammer:19

i will update the help page once the nightly is available
So this test should work as follows:
 hammer -v -u admin -p changeme --output=csv host-collection update --max-content-hosts="17" --id="21"

**Comment by tkolhar** [comment]
closing this as this issue is added a to a common github issue created for all upstream failures
