### ISSUE TITLE
Automation failure : list of tests given below

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2142]
this test is failing for nightly
below link provide list of tests for nightly:
- https://jenkins.example.com/view/Nightly/job/satellite6-automation-upstream-rhel66-cli/64/#showFailuresLink

the above tests are failing due to bz : 
 - https://bugzilla.redhat.com/show_bug.cgi?id=1217004
 - https://bugzilla.redhat.com/show_bug.cgi?id=1217005

if decorator is added to the tests it can be skipped until it is fixed
Examples of some commands which are failing : 

```
$ hammer -v -u admin -p changeme --output=csv organization create --name="t123"
[ERROR 2015-04-29 07:35:21 Modules] Error while loading module hammer_cli_import
Warning: An error occured while loading module hammer_cli_import
[ERROR 2015-04-29 07:35:21 Modules] <Gem::LoadError> RubyGem version error: hammer_cli_foreman(0.2.0 not ~> 0.1.1)

	/usr/lib/ruby/site_ruby/1.8/rubygems.rb:779:in `report_activate_error'
	/usr/lib/ruby/site_ruby/1.8/rubygems.rb:214:in `activate'
	/usr/lib/ruby/site_ruby/1.8/rubygems.rb:249:in `activate'
	/usr/lib/ruby/site_ruby/1.8/rubygems.rb:248:in `each'
	/usr/lib/ruby/site_ruby/1.8/rubygems.rb:248:in `activate'
	/usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:35:in `require'
	/usr/lib/ruby/gems/1.8/gems/hammer_cli-0.2.0/lib/hammer_cli/modules.rb:78:in `require_module'
	/usr/lib/ruby/gems/1.8/gems/hammer_cli-0.2.0/lib/hammer_cli/modules.rb:57:in `load!'
	/usr/lib/ruby/gems/1.8/gems/hammer_cli-0.2.0/lib/hammer_cli/modules.rb:72:in `load'
	/usr/lib/ruby/gems/1.8/gems/hammer_cli-0.2.0/lib/hammer_cli/modules.rb:83:in `load_all'
	/usr/lib/ruby/gems/1.8/gems/hammer_cli-0.2.0/lib/hammer_cli/modules.rb:82:in `each'
	/usr/lib/ruby/gems/1.8/gems/hammer_cli-0.2.0/lib/hammer_cli/modules.rb:82:in `load_all'
	/usr/lib/ruby/gems/1.8/gems/hammer_cli-0.2.0/bin/hammer:95
	/usr/bin/hammer:19:in `load'
	/usr/bin/hammer:19
Message,Id,Name
Organization created,376,t123


$ hammer -v -u admin -p changeme --output=csv location create --name="test"
[ERROR 2015-04-29 07:45:20 Modules] Error while loading module hammer_cli_import
Warning: An error occured while loading module hammer_cli_import
[ERROR 2015-04-29 07:45:20 Modules] <Gem::LoadError> RubyGem version error: hammer_cli_foreman(0.2.0 not ~> 0.1.1)

	/usr/lib/ruby/site_ruby/1.8/rubygems.rb:779:in `report_activate_error'
	/usr/lib/ruby/site_ruby/1.8/rubygems.rb:214:in `activate'
	/usr/lib/ruby/site_ruby/1.8/rubygems.rb:249:in `activate'
	/usr/lib/ruby/site_ruby/1.8/rubygems.rb:248:in `each'
	/usr/lib/ruby/site_ruby/1.8/rubygems.rb:248:in `activate'
	/usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:35:in `require'
	/usr/lib/ruby/gems/1.8/gems/hammer_cli-0.2.0/lib/hammer_cli/modules.rb:78:in `require_module'
	/usr/lib/ruby/gems/1.8/gems/hammer_cli-0.2.0/lib/hammer_cli/modules.rb:57:in `load!'
	/usr/lib/ruby/gems/1.8/gems/hammer_cli-0.2.0/lib/hammer_cli/modules.rb:72:in `load'
	/usr/lib/ruby/gems/1.8/gems/hammer_cli-0.2.0/lib/hammer_cli/modules.rb:83:in `load_all'
	/usr/lib/ruby/gems/1.8/gems/hammer_cli-0.2.0/lib/hammer_cli/modules.rb:82:in `each'
	/usr/lib/ruby/gems/1.8/gems/hammer_cli-0.2.0/lib/hammer_cli/modules.rb:82:in `load_all'
	/usr/lib/ruby/gems/1.8/gems/hammer_cli-0.2.0/bin/hammer:95
	/usr/bin/hammer:19:in `load'
	/usr/bin/hammer:19
Message,Id,Name
Location created,377,test
```

**Comment by tkolhar** [comment]
closing this as this issue is added a to a common github issue created for all upstream failures
