### ISSUE TITLE
Fix test_update_resource: 

### ISSUE THREAD

**Issue by sghai** [SatelliteQE/robottelo#2145]
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ddt.py", line 94, in wrapper
    return func(self, *args, **kwargs)
  File "/home/sghai/QE/robottelo/tests/foreman/ui/test_computeresource.py", line 189, in test_update_resource
    libvirt_set_passwd=False)
  File "/home/sghai/QE/robottelo/robottelo/ui/computeresource.py", line 89, in update
    edit.click()
AttributeError: 'NoneType' object has no attribute 'click'
```

**Comment by sghai** [comment]
Looks like locator issue.. Fix is in upcoming PR

**Comment by sghai** [comment]
Looks like if we create entity with html or multi-byte strings then name of entity appears in special characters in html tags. So selenium unable to find the object with given name. However test is working fine with alpha, numeric and alphanumeric.

**Comment by sghai** [comment]
PR raised: #2203

**Comment by sghai** [comment]
Closing it as referenced PR merged
