### ISSUE TITLE
Fix the locator issue test : tests.foreman.ui.test_syncplan.Syncplan.test_positive_create_2

### ISSUE THREAD

**Issue by jyejare** [SatelliteQE/robottelo#2155]
The test is failing due to locator issue, even though we fix the locator issue, test should not run because the dependent bug BZ1202811 needs to be fixed. Needs to update this test with the given Bug id as its have a old bug id there in verified state.

Stacktrace:

```
E
======================================================================
ERROR: @Test: Create Sync plan with specified start time
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jyejare/Desktop/RedHat/RobotteloTop/robottelo/robottelo/common/decorators.py", line 362, in wrapper_func
    return func(*args, **kwargs)
  File "/home/jyejare/Desktop/RedHat/RobotteloTop/robottelo/tests/foreman/ui/test_syncplan.py", line 119, in test_positive_create_2
    starttime_text = self.syncplan.wait_until_element(locator).text
AttributeError: 'NoneType' object has no attribute 'text'

robottelo.ui.base: DEBUG: TimeoutException: Timed out waiting for element '//span[contains(.,'Start Date')]/../span[contains(@class,'info-value')]' to display.
```

**Comment by jyejare** [comment]
Closing this issue as PR #2158 has been merged.
