### ISSUE TITLE
Automation failure : test_enable_manifest_repository_set

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2228]
TestNames:
tests.foreman.cli.test_subscription.TestSubscription.test_enable_manifest_repository_set

Error Message
70 != 0 : Repo was not enabled
-------------------- >> begin captured logging << --------------------
robottelo: DEBUG: Running test TestSubscription/test_enable_manifest_repository_set
robottelo.common.ssh: INFO: Instantiated Paramiko client 0x31bdd90
robottelo.common.ssh: INFO: Destroying Paramiko client 0x31bdd90
robottelo.common.ssh: INFO: Destroyed Paramiko client 0x31bdd90
robottelo.common.ssh: DEBUG: >>> [qe-sat6-rhel71.usersys.redhat.com] LANG=en_US.UTF-8 hammer -v -u admin -p changeme  subscription upload --organization-id="253" --file="/tmp/tmpEGavQg"
robottelo.common.ssh: INFO: Instantiated Paramiko client 0x31bd150
robottelo.common.ssh: INFO: Destroying Paramiko client 0x31bd150
robottelo.common.ssh: INFO: Destroyed Paramiko client 0x31bd150
robottelo.common.ssh: DEBUG: >>> [qe-sat6-rhel71.usersys.redhat.com] LANG=en_US.UTF-8 hammer -v -u admin -p changeme --output=csv subscription list --organization-id="253"
robottelo.common.ssh: INFO: Instantiated Paramiko client 0x31bde10
robottelo.common.ssh: INFO: Destroying Paramiko client 0x31bde10
robottelo.common.ssh: INFO: Destroyed Paramiko client 0x31bde10
robottelo.common.ssh: DEBUG: <<<
Name,Contract,Account,Support,Quantity,Consumed,End Date,ID,Product,Quantity,Attached
405133325387225,,,"",-1,0,2045-05-05,ff8080814d4a78f3014d4ae807182bc9,405133325387225,-1,0
<tr>ufscwRMWCbNyjpK</tr>,,,"",-1,0,2045-05-05,ff8080814d4a78f3014d4ae8498e2bdb,<tr>ufscwRMWCbNyjpK</tr>,-1,0
IFYpjxxaQPwRqGOxQCdH,,,"",-1,0,2045-05-05,ff8080814d4a78f3014d4ae877432be8,IFYpjxxaQPwRqGOxQCdH,-1,0
InWVdxIWCYyvGURDdXuD,,,"",-1,0,2045-05-05,ff8080814d4a78f3014d4ae8adec2bee,InWVdxIWCYyvGURDdXuD,-1,0
QdsAgfRrNTElwMKGYtSn,,,"",-1,0,2045-05-05,ff8080814d4a78f3014d4ae7c4f52bbd,QdsAgfRrNTElwMKGYtSn,-1,0
RSjtjjwvbTXOWYvdMWGx,,,"",-1,0,2045-05-05,ff8080814d4a78f3014d4ae8e1a82bf4,RSjtjjwvbTXOWYvdMWGx,-1,0
jrsmzfHcpiDveWJ,,,"",-1,0,2045-05-05,ff8080814d4a78f3014d4ae7f9232bc3,jrsmzfHcpiDveWJ,-1,0
pnbaFrLuUnuDdKOghfGE,,,"",-1,0,2045-05-05,ff8080814d4a78f3014d4ab0344e183e,pnbaFrLuUnuDdKOghfGE,-1,0
ÄâÄÀðçÙÐáÍÑÜÌÇÌ,,,"",-1,0,2045-05-05,ff8080814d4a78f3014d4ae816692bcf,ÄâÄÀðçÙÐáÍÑÜÌÇÌ,-1,0
çÄýÚßÅÝÛíÔçóÄÂÁ,,,"",-1,0,2045-05-05,ff8080814d4a78f3014d4ae8309a2bd5,çÄýÚßÅÝÛíÔçóÄÂÁ,-1,0

robottelo.common.ssh: DEBUG: >>> [qe-sat6-rhel71.usersys.redhat.com] LANG=en_US.UTF-8 hammer -v -u admin -p changeme --output=csv repository-set enable --product="Red Hat Enterprise Linux Workstation" --basearch="x86_64" --releasever="6Workstation" --name="Red Hat Enterprise Virtualization Agents for RHEL 6 Workstation (RPMs)" --organization-id="253"
robottelo.common.ssh: INFO: Instantiated Paramiko client 0x31bd690
robottelo.common.ssh: INFO: Destroying Paramiko client 0x31bd690
robottelo.common.ssh: INFO: Destroyed Paramiko client 0x31bd690
robottelo.common.ssh: DEBUG: <<< [ERROR 2015-05-12 21:41:37 Exception] Error: product not found
Could not enable repository:
  Error: product not found
[ERROR 2015-05-12 21:41:37 Exception] 

HammerCLIForeman::ResolverError (product not found):
    /usr/share/gems/gems/hammer_cli_foreman-0.1.4.11/lib/hammer_cli_foreman/id_resolver.rb:191:in `pick_result'
    /usr/share/gems/gems/hammer_cli_foreman-0.1.4.11/lib/hammer_cli_foreman/id_resolver.rb:156:in `find_resource'
    /usr/share/gems/gems/hammer_cli_foreman-0.1.4.11/lib/hammer_cli_foreman/id_resolver.rb:139:in `get_id'
    /usr/share/gems/gems/hammer_cli_foreman-0.1.4.11/lib/hammer_cli_foreman/id_resolver.rb:129:in `block (2 levels) in define_id_finders'
    /usr/share/gems/gems/hammer_cli_foreman-0.1.4.11/lib/hammer_cli_foreman/commands.rb:149:in `get_resource_id'
    /usr/share/gems/gems/hammer_cli_foreman-0.1.4.11/lib/hammer_cli_foreman/commands.rb:214:in `block in customized_options'
    /usr/share/gems/gems/hammer_cli_foreman-0.1.4.11/lib/hammer_cli_foreman/commands.rb:211:in `each'
    /usr/share/gems/gems/hammer_cli_foreman-0.1.4.11/lib/hammer_cli_foreman/commands.rb:211:in `customized_options'
    /usr/share/gems/gems/hammer_cli_foreman-0.1.4.11/lib/hammer_cli_foreman/commands.rb:235:in `request_params'
    /usr/share/gems/gems/hammer_cli-0.1.4.10/lib/hammer_cli/apipie/command.rb:43:in `send_request'
    /usr/share/gems/gems/hammer_cli_foreman-0.1.4.11/lib/hammer_cli_foreman/commands.rb:185:in `send_request'
    /usr/share/gems/gems/hammer_cli-0.1.4.10/lib/hammer_cli/apipie/command.rb:34:in `execute'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.10/lib/hammer_cli/abstract.rb:23:in `run'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.10/lib/hammer_cli/abstract.rb:23:in `run'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.10/lib/hammer_cli/abstract.rb:23:in `run'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:125:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.10/bin/hammer:108:in `<top (required)>'
    /usr/bin/hammer:23:in `load'
    /usr/bin/hammer:23:in `<main>'

**Comment by tkolhar** [comment]
when tried locally running the test using nosetests the results are:
$ nosetests -c robottelo.properties -m test_enable_manifest_repository_set /home/tkolhar/git/robottelo/tests/foreman/cli/test_subscription.py
/usr/lib/python2.7/site-packages/nose/plugins/manager.py:395: RuntimeWarning: Unable to load plugin xunitmp = nose_xunitmp:XunitMP: cannot import name force_unicode
  RuntimeWarning)
@Test: enable repository set (positive) ... 2015-05-13 17:59:03 - robottelo - DEBUG - Running test TestSubscription/test_enable_manifest_repository_set
2015-05-13 17:59:03 - robottelo.common.ssh - DEBUG - >>> [qe-sat6-rhel71.usersys.redhat.com] LANG=en_US.UTF-8 hammer -v -u admin -p changeme --output=csv organization create --name="ZXJvyO"
2015-05-13 17:59:07 - robottelo.common.ssh - INFO - Instantiated Paramiko client 0x1ca9890
2015-05-13 17:59:10 - robottelo.common.ssh - INFO - Destroying Paramiko client 0x1ca9890
2015-05-13 17:59:10 - robottelo.common.ssh - INFO - Destroyed Paramiko client 0x1ca9890
2015-05-13 17:59:10 - robottelo.common.ssh - DEBUG - <<<
Message,Id,Name
Organization created,434,ZXJvyO

2015-05-13 17:59:10 - robottelo.common.ssh - DEBUG - >>> [qe-sat6-rhel71.usersys.redhat.com] LANG=en_US.UTF-8 hammer -v -u admin -p changeme  organization info --id="434"
2015-05-13 17:59:13 - robottelo.common.ssh - INFO - Instantiated Paramiko client 0x1ca9950
2015-05-13 17:59:16 - robottelo.common.ssh - INFO - Destroying Paramiko client 0x1ca9950
2015-05-13 17:59:16 - robottelo.common.ssh - INFO - Destroyed Paramiko client 0x1ca9950
2015-05-13 17:59:16 - robottelo.common.ssh - DEBUG - <<<
Id:                     434
Name:                   ZXJvyO
Users:                  

Smart proxies:          
    qe-sat6-rhel71.usersys.redhat.com
Subnets:                

Compute resources:      

Installation media:     

Templates:              
    Boot disk iPXE - generic host (Bootdisk)
    Boot disk iPXE - host (Bootdisk)
    idm_register ()
    Kickstart default iPXE (iPXE)
    Kickstart default PXELinux (PXELinux)
    kickstart_networking_setup ()
    puppet.conf ()
    PXELinux default local boot (PXELinux)
    PXELinux global default (PXELinux)
    Satellite Kickstart Default (provision)
    Satellite Kickstart Default Finish (finish)
    Satellite Kickstart Default User Data (user_data)
    subscription_manager_registration ()
Domains:                

Environments:           

Hostgroups:             

Parameters:             

Created at:             2015/05/13 12:29:09
Updated at:             2015/05/13 12:29:09
Label:                  ZXJvyO
Description:            
Red Hat Repository URL: https://cdn.redhat.com


2015-05-13 17:59:19 - robottelo.common.ssh - INFO - Instantiated Paramiko client 0x7fd357eb49d0
2015-05-13 17:59:24 - robottelo.common.ssh - INFO - Destroying Paramiko client 0x7fd357eb49d0
2015-05-13 17:59:24 - robottelo.common.ssh - INFO - Destroyed Paramiko client 0x7fd357eb49d0
2015-05-13 17:59:24 - robottelo.common.ssh - DEBUG - >>> [qe-sat6-rhel71.usersys.redhat.com] LANG=en_US.UTF-8 hammer -v -u admin -p changeme  subscription upload --organization-id="434" --file="/tmp/tmpHf5PGy"
2015-05-13 17:59:27 - robottelo.common.ssh - INFO - Instantiated Paramiko client 0x1cb0ed0
2015-05-13 18:00:01 - robottelo.common.ssh - INFO - Destroying Paramiko client 0x1cb0ed0
2015-05-13 18:00:01 - robottelo.common.ssh - INFO - Destroyed Paramiko client 0x1cb0ed0
2015-05-13 18:00:01 - robottelo.common.ssh - DEBUG - >>> [qe-sat6-rhel71.usersys.redhat.com] LANG=en_US.UTF-8 hammer -v -u admin -p changeme --output=csv subscription list --organization-id="434"
2015-05-13 18:00:03 - robottelo.common.ssh - INFO - Instantiated Paramiko client 0x1ca9d90
2015-05-13 18:00:05 - robottelo.common.ssh - INFO - Destroying Paramiko client 0x1ca9d90
2015-05-13 18:00:05 - robottelo.common.ssh - INFO - Destroyed Paramiko client 0x1ca9d90
2015-05-13 18:00:05 - robottelo.common.ssh - DEBUG - <<<
Name,Contract,Account,Support,Quantity,Consumed,End Date,ID,Product,Quantity,Attached
CloudForms Employee Subscription,10041814,477931,Self-Support,10,0,2022-01-01,ff8080814d4a78f3014d4d40ac165c57,CloudForms Employee Subscription,10,0
Red Hat Employee Subscription,10169793,477931,SELF-SUPPORT,10,0,2022-01-01,ff8080814d4a78f3014d4d40aa0d5b63,Red Hat Employee Subscription,10,0

2015-05-13 18:00:05 - robottelo.common.ssh - DEBUG - >>> [qe-sat6-rhel71.usersys.redhat.com] LANG=en_US.UTF-8 hammer -v -u admin -p changeme --output=csv repository-set enable --product="Red Hat Enterprise Linux Workstation" --basearch="x86_64" --releasever="6Workstation" --name="Red Hat Enterprise Virtualization Agents for RHEL 6 Workstation (RPMs)" --organization-id="434"
2015-05-13 18:00:08 - robottelo.common.ssh - INFO - Instantiated Paramiko client 0x1cb0150
2015-05-13 18:00:19 - robottelo.common.ssh - INFO - Destroying Paramiko client 0x1cb0150
2015-05-13 18:00:19 - robottelo.common.ssh - INFO - Destroyed Paramiko client 0x1cb0150
2015-05-13 18:00:19 - robottelo.common.ssh - DEBUG - <<<
Message,Id
Repository enabled,523ee324-7e97-4865-bbd9-6087c3ccfe17

2015-05-13 18:00:19 - robottelo.common.ssh - DEBUG - >>> [qe-sat6-rhel71.usersys.redhat.com] LANG=en_US.UTF-8 hammer -v -u admin -p changeme --output=csv repository synchronize --product="Red Hat Enterprise Linux Workstation" --name="Red Hat Enterprise Virtualization Agents for RHEL 6 Workstation RPMs x86_64 6Workstation" --organization-id="434"
2015-05-13 18:00:21 - robottelo.common.ssh - INFO - Instantiated Paramiko client 0x1ca9fd0
2015-05-13 18:00:43 - robottelo.common.ssh - INFO - Destroying Paramiko client 0x1ca9fd0
2015-05-13 18:00:43 - robottelo.common.ssh - INFO - Destroyed Paramiko client 0x1ca9fd0
2015-05-13 18:00:43 - robottelo.common.ssh - DEBUG - <<<
No new packages.

ok
XML: foreman-results.xml
Ran 1 test in 99.930s

OK

**Comment by tkolhar** [comment]
this issue is found in snap4 compose 2 also
Error Message
70 != 0 : Repo was not enabled

**Comment by elyezer** [comment]
The reason why this is failing in jenkins and not locally is because the cached behaviour when creating an organization.

I checked the systems and the organization specified shows the message on the `Red Hat Products` page:

```
Expand each Red Hat Product below to examine the different repository sets available. When enabling a repository set, the different repositories within are discovered and may be enabled individually.

Enable Red Hat Repositories

No Red Hat products currently exist, please import a manifest here to receive Red Hat content.
```
