### ISSUE TITLE
Automation failure : test_update_os_medium 

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2261]
TestNames:
tests.foreman.ui.test_operatingsys.OperatingSys.test_update_os_medium

Error Message
Valid fields are ['name', 'media_path', 'operatingsystem', 'os_family', 'organization', 'id'], but received ['organization', 'path_', 'name'] instead.

Stacktrace
Traceback (most recent call last):
  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel71-ui/tests/foreman/ui/test_operatingsys.py", line 353, in test_update_os_medium
    organization=[self.org_id],
  File "/home/jenkins/shiningpanda/jobs/ca586003/virtualenvs/d41d8cd9/lib/python2.7/site-packages/nailgun/entities.py", line 1847, in __init__
    super(Media, self).__init__(server_config, **kwargs)
  File "/home/jenkins/shiningpanda/jobs/ca586003/virtualenvs/d41d8cd9/lib/python2.7/site-packages/nailgun/entity_mixins.py", line 256, in __init__
    .format(self._fields.keys(), kwargs.keys())
NoSuchFieldError: Valid fields are ['name', 'media_path', 'operatingsystem', 'os_family', 'organization', 'id'], but received ['organization', 'path_', 'name'] instead.

**Comment by tkolhar** [comment]
when executed locally using nosetests:
$  nosetests -c robottelo.properties -m test_update_os_medium /home/tkolhar/git/robottelo/tests/foreman/ui/test_operatingsys.py
ERROR: @Test: Update OS medium
Traceback (most recent call last):
  File "/home/tkolhar/git/robottelo/tests/foreman/ui/test_operatingsys.py", line 353, in test_update_os_medium
    organization=[self.org_id],
  File "/usr/lib/python2.7/site-packages/nailgun/entity_mixins.py", line 227, in __init__
    fields.keys(), kwargs.keys()
NoSuchFieldError: Valid fields are ['name', 'media_path', 'id', 'os_family', 'organization', 'operatingsystem'], but received ['organization', 'path_', 'name'] instead.

the field key error should be fixed
A valid key must be used

**Comment by jyejare** [comment]
Tested this issue on RHEL 6 and RHEL 7 jenkins systems .
Both are working Fine. Also passing in latest run.
Hence closing as not repro.

Results:
```
[root@jyejare robottelo]# nosetests -m test_update_os_medium ./tests/foreman/ui/test_operatingsys.py
.
----------------------------------------------------------------------
Ran 1 test in 79.562s

OK
[root@jyejare robottelo]# nosetests -m test_update_os_medium ./tests/foreman/ui/test_operatingsys.py
.
----------------------------------------------------------------------
Ran 1 test in 84.309s

OK
```

**Comment by tkolhar** [comment]
this issue occurred again dated 06/24/2015
TestNames : 
tests.foreman.ui.test_operatingsys.OperatingSys.test_update_os_medium

Error Message
'ascii' codec can't encode characters in position 0-29: ordinal not in range(128)

Stacktrace

  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel71-ui/tests/foreman/ui/test_operatingsys.py", line 358, in test_update_os_medium
    self.operatingsys.update(os_name, new_mediums=[medium_name])
  File "robottelo/ui/operatingsys.py", line 158, in update
    'Could not update the operating system "{0}"'.format(os_name)
'\'ascii\' codec can\'t encode characters in position 0-29: ordinal not in range(128)\n-------------------- >

**Comment by sthirugn** [comment]
Passed in snap 12
