### ISSUE TITLE
Automation failure : test_search_permissions

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2287]
TestNames:
tests.foreman.api.test_permission.PermissionsTestCase.test_search_permissions

Error Message
Items in the second set but not the first:
u'Docker/ImageSearch'
u'DiscoveryRule'
u'Container'
u'DockerRegistry'

Stacktrace
  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel66-api/tests/foreman/api/test_permission.py", line 89, in test_search_permissions
    frozenset(perm_resource_types),
  File "/usr/lib64/python2.7/unittest/case.py", line 553, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib64/python2.7/unittest/case.py", line 836, in assertSetEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/lib64/python2.7/unittest/case.py", line 450, in fail
    raise self.failureException(msg)
'Items in the second set but not the first:\nu\'Docker/ImageSearch\'\nu\'DiscoveryRule\'\nu\'Container

**Comment by tkolhar** [comment]
when executed locally using nosetests:
$ nosetests -c robottelo.properties test_search_permissions /home/tkolhar/git/robottelo/tests/foreman/api/test_permission.py
FAIL: @test: search with no parameters return all permissions
Traceback (most recent call last):
  File "/home/tkolhar/git/robottelo/tests/foreman/api/test_permission.py", line 89, in test_search_permissions
    frozenset(perm_resource_types),
AssertionError: Items in the second set but not the first:
u'Docker/ImageSearch'
u'DiscoveryRule'
u'Container'
u'DockerRegistry'

**Comment by Ichimonji10** [comment]
Upstream and downstream return different sets of permissions. We can update this test to deal with the discrepancy by using function `robottelo.common.helpers.get_server_software`. Before just going ahead and accepting what's returned by the server, though, it's worth asking what the server *should* be returning. IIRC, @oshtaier filed a bug about this very issue. Can you provide any insight?

**Comment by elyezer** [comment]
This issue duplicates #2173.
