### ISSUE TITLE
Automation failure : test_delete_version_non_default 

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2299]
TestNames:
tests.foreman.ui.test_contentviews.TestContentViewsUI.test_delete_version_non_default 

Error Message
Selected version "Version 1.0" was not deleted successfully

**Comment by tkolhar** [comment]
when executed locally using nosetests:
$ nosetests -c robottelo.properties -m test_delete_version_non_default /home/tkolhar/git/robottelo/tests/foreman/ui/test_contentviews.py
2015-05-27 16:20:12 - nailgun.client - DEBUG - Received HTTP 200 response: {"id":"41978826-e3d5-4877-b723-ae9950a943ae","label":"Actions::Katello::ContentView::Promote","pending":false,"username":"admin","started_at":"2015-05-27T10:49:54Z","ended_at":"2015-05-27T10:50:10Z","state":"stopped","result":"success","progress":1.0,"input":{"content_view":{"id":561,"name":"jEqwCxXBpz","label":"jEqwCxXBpz"},"organization":{"id":416,"name":"󼩂ᨓꊃࢉ񺃷򢃷󎫾򮣥򮱭񱇚򰌋󝋔","label":"35bf2a15-9ba6-4ab4-b900-328273700da8"},"history_id":229,"environment_id":460,"user_id":3,"environment_name":"񧌰󬵋헗񕀲𿕢򑓲򶷁򽸦򧂥񿭏","content_view_id":561,"current_user_id":3,"locale":"en"},"output":{},"humanized":{"action":"Promotion","input":[["content_view",{"text":"content view 'jEqwCxXBpz'","link":"#/content_views/561/versions"}],["organization",{"text":"organization '󼩂ᨓꊃࢉ񺃷򢃷󎫾򮣥򮱭񱇚򰌋󝋔'","link":"/organizations/416/edit"}]],"output":"","errors":[]},"cli_example":null}
2015-05-27 16:20:12 - robottelo.ui.locators - DEBUG - Accessing locator "login.username" by id: "login_login"
2015-05-27 16:20:13 - robottelo.ui.locators - DEBUG - Accessing locator "login.username" by id: "login_login"
2015-05-27 16:20:13 - robottelo.ui.locators - DEBUG - Accessing locator "login.password" by id: "login_password"
2015-05-27 16:20:13 - robottelo.ui.locators - DEBUG - Accessing locator "submit" by name: "commit"
2015-05-27 16:20:15 - robottelo.ui.locators - DEBUG - Accessing locator "notif.error" by xpath: "//div[contains(@class, 'jnotify-notification-error')]"
2015-05-27 16:20:19 - robottelo.ui.base - DEBUG - NoSuchElementException: Could not locate element //div[contains(@class, 'jnotify-notification-error')].
2015-05-27 16:20:19 - robottelo.ui.locators - DEBUG - Accessing locator "menu.any_context" by xpath: "//div[contains(@style,'static') or contains(@style,'fixed')]//li[contains(@class,'org-switcher')]/a"
2015-05-27 16:20:19 - robottelo.ui.locators - DEBUG - Accessing locator "org.nav_current_org" by xpath: "(//div[contains(@style,'static') or contains(@style,'fixed')]//li[contains(@class,'org-switcher')]//li/a[@data-toggle='dropdown'])[1]"
2015-05-27 16:20:19 - robottelo.ui.locators - DEBUG - Accessing locator "org.select_org" by xpath: "//div[contains(@style,'static') or contains(@style,'fixed')]//a[@href='/organizations/clear']/../../li/a[contains(.,'%s')]"
2015-05-27 16:20:22 - robottelo.ui.locators - DEBUG - Accessing locator "menu.current_text" by xpath: "//div[contains(@style,'static') or contains(@style,'fixed')]//li[contains(@class,'org-switcher')]/a"
2015-05-27 16:20:25 - robottelo.ui.locators - DEBUG - Accessing locator "menu.fetch_org" by xpath: "//div[contains(@style,'static') or contains(@style, 'fixed')]//li[contains(@class, 'org-menu')]/a"
2015-05-27 16:20:25 - robottelo.ui.locators - DEBUG - Accessing locator "menu.content" by xpath: "//div[contains(@style,'static') or contains(@style, 'fixed')]//a[@id='content_menu']"
2015-05-27 16:20:25 - robottelo.ui.locators - DEBUG - Accessing locator "menu.content_views" by xpath: "//div[contains(@style,'static') or contains(@style, 'fixed')]//a[@id='menu_item_content_views']"
2015-05-27 16:20:26 - robottelo.ui.locators - DEBUG - Accessing locator "contentviews.key_name" by xpath: "//tr[contains(@ng-repeat, 'contentView')]/td/a[contains(., '%s')]"
2015-05-27 16:20:26 - robottelo.ui.locators - DEBUG - Accessing locator "contentviews.key_name" by xpath: "//tr[contains(@ng-repeat, 'contentView')]/td/a[contains(., '%s')]"
2015-05-27 16:20:26 - robottelo.ui.locators - DEBUG - Accessing locator "kt_search" by xpath: "//input[@ng-model='table.searchTerm']"
2015-05-27 16:20:41 - robottelo.ui.locators - DEBUG - Accessing locator "kt_search_button" by xpath: "//button[@ng-click='table.search(table.searchTerm)']"
2015-05-27 16:20:47 - robottelo.ui.locators - DEBUG - Accessing locator "contentviews.remove_ver" by xpath: "//td/a[contains(., '%s')]/following::td/button[contains(@ui-sref, 'version-deletion')]"
2015-05-27 16:20:55 - robottelo.ui.locators - DEBUG - Accessing locator "contentviews.completely_remove_checkbox" by xpath: "//span/input[contains(@ng-model, 'deleteArchive')]"
2015-05-27 16:20:57 - robottelo.ui.locators - DEBUG - Accessing locator "contentviews.next_button" by xpath: "//button[@ng-click='processSelection()']"
2015-05-27 16:20:58 - robottelo.ui.locators - DEBUG - Accessing locator "contentviews.confirm_remove_ver" by xpath: "//button[@ng-click='performDeletion()']"
2015-05-27 16:21:03 - robottelo.ui.locators - DEBUG - Accessing locator "contentviews.key_name" by xpath: "//tr[contains(@ng-repeat, 'contentView')]/td/a[contains(., '%s')]"
2015-05-27 16:21:03 - robottelo.ui.locators - DEBUG - Accessing locator "contentviews.key_name" by xpath: "//tr[contains(@ng-repeat, 'contentView')]/td/a[contains(., '%s')]"
2015-05-27 16:21:03 - robottelo.ui.locators - DEBUG - Accessing locator "kt_search" by xpath: "//input[@ng-model='table.searchTerm']"
2015-05-27 16:21:04 - robottelo.ui.locators - DEBUG - Accessing locator "kt_search_button" by xpath: "//button[@ng-click='table.search(table.searchTerm)']"
2015-05-27 16:21:11 - robottelo.ui.locators - DEBUG - Accessing locator "contentviews.version_name" by xpath: "//td/a[contains(., '%s')]"
2015-05-27 16:21:11 - robottelo.ui.base - DEBUG - NoSuchElementException: Could not locate element //td/a[contains(., 'Version 1.0')].
2015-05-27 16:21:11 - robottelo.ui.locators - DEBUG - Accessing locator "login.gravatar" by xpath: "//img[contains(@class, 'avatar')]"
2015-05-27 16:21:11 - robottelo.ui.locators - DEBUG - Accessing locator "menu.account" by xpath: "//a[@id='account_menu']"
2015-05-27 16:21:11 - robottelo.ui.locators - DEBUG - Accessing locator "menu.sign_out" by xpath: "//a[@id='menu_item_logout']"
ok
XML: foreman-results.xml
Ran 1 test in 199.712s
OK

**Comment by jyejare** [comment]
Tested this on both RHEL 6 and RHEL 7 jenkins systems.
Passing on both so closing the issue.
```
[root@jyejare robottelo]# nosetests -m test_delete_version_non_default ./tests/foreman/ui/test_contentviews.py
.
----------------------------------------------------------------------
Ran 1 test in 172.579s

OK
[root@jyejare robottelo]# nosetests -m test_delete_version_non_default ./tests/foreman/ui/test_contentviews.py
.
----------------------------------------------------------------------
Ran 1 test in 179.534s

OK
```

**Comment by tkolhar** [comment]
this issue occurred again on 06/05/2015
Error Message
Selected version "Version 1.0" was not deleted successfully
Stacktrace

  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel66-ui/tests/foreman/ui/test_contentviews.py", line 1274, in test_delete_version_non_default
    self.content_views.validate_version_deleted(cv.name, version)
  File "robottelo/ui/contentviews.py", line 769, in validate_version_deleted
    .format(version)
'Selected version "Version 1.0" was not deleted successfully\n--------------------

**Comment by tkolhar** [comment]
this issue occurred again dated 06/18/2015
tests.foreman.ui.test_contentviews.TestContentViewsUI.test_delete_version_non_default 

Error Message
Selected version "Version 1.0" was not deleted successfully

Stacktrace

  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel66-ui/tests/foreman/ui/test_contentviews.py", line 1269, in test_delete_version_non_default
    self.content_views.validate_version_deleted(cv.name, version)
  File "robottelo/ui/contentviews.py", line 769, in validate_version_deleted
    .format(version)
'Selected version "Version 1.0" was not deleted successfully\n--------------------

**Comment by sthirugn** [comment]
Failed in Snap 12

**Comment by tkolhar** [comment]
this test is failing when executed locally using nosetests:
$  nosetests -c robottelo.properties -m test_delete_version_non_default /home/tkolhar/git/robottelo/tests/foreman/ui/test_contentviews.py
2015-08-12 14:06:34 - nailgun.client - DEBUG - Received HTTP 200 response: {"id":14,"name":"VZAJQxzXDL","label":"VZAJQxzXDL","description":null,"organization":{"name":"򮖧","label":"ad9cec32-5cb3-4b52-93ef-91caf7500586","id":16},"created_at":"2015-08-12T08:36:34Z","updated_at":"2015-08-12T08:36:34Z","composite":null,"repository_ids":[],"component_ids":[],"default":false,"next_version":1,"last_published":null,"permissions":{"view_content_views":true,"edit_content_views":true,"destroy_content_views":true,"publish_content_views":true,"promote_or_remove_content_views":true},"environments":[],"repositories":[],"puppet_modules":[],"versions":[],"components":[],"activation_keys":[],"content_host_count":0}

ERROR
ERROR


ERROR: @Test: Delete a content-view version associated to non-default

Traceback (most recent call last):
  File "/home/tkolhar/git/robottelo/tests/foreman/ui/test_contentviews.py", line 1257, in test_delete_version_non_default
    cv.update(['repository'])
AttributeError: 'ContentView' object has no attribute 'update'


ERROR: @Test: Delete a content-view version associated to non-default

Traceback (most recent call last):
  File "/home/tkolhar/git/robottelo/robottelo/test.py", line 282, in tearDown
    self.take_screenshot(self._testMethodName)
  File "/home/tkolhar/git/robottelo/robottelo/test.py", line 270, in take_screenshot
    directory,
  File "/usr/lib64/python2.7/posixpath.py", line 77, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'


XML: foreman-results.xml

Ran 1 test in 81.337s

FAILED (errors=2)

**Comment by tkolhar** [comment]
closing this as this issue is added a to a common github issue created for all downstream failures
