### ISSUE TITLE
Automation failure : test_sync_rh_repos

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2309]
TestNames:
tests.foreman.ui.test_sync.Sync.test_sync_rh_repos

Error Message
Could not select the product: 'Red Hat Enterprise Linux Server'

Stacktrace

  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel66-ui/tests/foreman/ui/test_sync.py", line 83, in test_sync_rh_repos
    self.sync.enable_rh_repos(repos)
  File "robottelo/ui/sync.py", line 162, in enable_rh_repos
    "Could not select the product: '{0}'".format(PRDS[prd]))
'Could not select the product: \'Red Hat Enterprise Linux Server\'\n--------------------

**Comment by tkolhar** [comment]
when executed locally using nosetests:
$ nosetests -c robottelo.properties -m test_sync_rh_repos /home/tkolhar/git/robottelo/tests/foreman/ui/test_sync.py
ERROR


ERROR: @Test: Create Content RedHat Sync with two repos.
Traceback (most recent call last):
  File "/home/tkolhar/git/robottelo/tests/foreman/ui/test_sync.py", line 81, in test_sync_rh_repos
    self.subscriptions.upload(manifest_path)
  File "/home/tkolhar/git/robottelo/robottelo/ui/subscription.py", line 23, in upload
    self.wait_until_element(locators["subs.manage_manifest"]).click()
AttributeError: 'NoneType' object has no attribute 'click'


ERROR: @Test: Create Content RedHat Sync with two repos.
Traceback (most recent call last):
  File "/home/tkolhar/git/robottelo/robottelo/test.py", line 258, in tearDown
    self.take_screenshot(self._testMethodName)
  File "/home/tkolhar/git/robottelo/robottelo/test.py", line 246, in take_screenshot
    directory,
  File "/usr/lib64/python2.7/posixpath.py", line 77, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'

XML: foreman-results.xml
Ran 1 test in 74.297s

FAILED (errors=2)

the subs.manage_manifest object has no attribute click

**Comment by jyejare** [comment]
This test is passing locally in my system. But failing is Jenkins system rapidly.

The only reason I believe is Selenium version in Jenkins system. I ran this test on my system with selenium version 2.42 which auto scrolls down and finds the web element on the page. where I believe the selenium in Jenkins system has older version which doesn't have auto scroll down function. So needs to upgrade that otherwise manually scroll down the page till that element visible, particular for this test.

**Comment by tkolhar** [comment]
this issue related to the test ic occurring again dated 06/05/2015
Error Message
Task 09be215d-cb2d-4b3b-aa9d-1287c9c2600f completed with result warning. Error message(s): [u'Validation failed: Name must contain at least 1 character']
Stacktrace

  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel66-ui/tests/foreman/ui/test_sync.py", line 80, in test_sync_rh_repos
    ).upload_manifest(path=manifest_path)
  File "/home/jenkins/shiningpanda/jobs/abb3bf3f/virtualenvs/d41d8cd9/lib/python2.7/site-packages/nailgun/entities.py", line 2294, in upload_manifest
    return _handle_response(response, self._server_config, synchronous)
  File "/home/jenkins/shiningpanda/jobs/abb3bf3f/virtualenvs/d41d8cd9/lib/python2.7/site-packages/nailgun/entities.py", line 104, in _handle_response
    return ForemanTask(server_config, id=response.json()['id']).poll()
  File "/home/jenkins/shiningpanda/jobs/abb3bf3f/virtualenvs/d41d8cd9/lib/python2.7/site-packages/nailgun/entities.py", line 1419, in poll
    timeout
  File "/home/jenkins/shiningpanda/jobs/abb3bf3f/virtualenvs/d41d8cd9/lib/python2.7/site-packages/nailgun/entity_mixins.py", line 104, in _poll_task
    task_info['humanized']['errors']
'Task 09be215d-cb2d-4b3b-aa9d-1287c9c2600f completed with result warning. Error message(s): [u\'Validation failed: Name must contain at least 1 character\']\n-------------------- >> begin captured logging 

when executed locally using nosetests:
$ nosetests -c robottelo.properties -m test_sync_rh_repos /home/tkolhar/git/robottelo/tests/foreman/ui/test_sync.py
ERROR: @Test: Create Content RedHat Sync with two repos.
Traceback (most recent call last):
  File "/home/tkolhar/git/robottelo/tests/foreman/ui/test_sync.py", line 84, in test_sync_rh_repos
    self.sync.enable_rh_repos(repos)
  File "/home/tkolhar/git/robottelo/robottelo/ui/sync.py", line 202, in enable_rh_repos
    "".format(repo_name))
UINoSuchElementError: Could not select the repo: 'Red Hat CloudForms Tools for RHEL 6 RPMs x86_64 6.5'

**Comment by jyejare** [comment]
I found out some of the issues related to this test,

1. Tested this test with selenium 2.46, I found its passing.
Results;
```
[root@jyejare robottelo]# nosetests -m test_sync_rh_repos ./tests/foreman/ui/test_sync.py
.
----------------------------------------------------------------------
Ran 1 test in 187.658s

OK
```

2. Tested this test with selenium 2.42, its failing with same error as @tkolhar mentioned above.
Results:
```
[root@jyejare robottelo]# nosetests -m test_sync_rh_repos ./tests/foreman/ui/test_sync.py
E
======================================================================
ERROR: @Test: Create Content RedHat Sync with two repos.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jyejare/Desktop/RedHat/RobotteloTop/robottelo/tests/foreman/ui/test_sync.py", line 84, in test_sync_rh_repos
    self.sync.enable_rh_repos(repos)
  File "/home/jyejare/Desktop/RedHat/RobotteloTop/robottelo/robottelo/ui/sync.py", line 202, in enable_rh_repos
    "".format(repo_name))
UINoSuchElementError: Could not select the repo: 'Red Hat CloudForms Tools for RHEL 6 RPMs x86_64 6.5'
```

3. Please note that while testing this test locally, I never encountered the error which we are getting in Jenkins. i.e. 'Validation failed: Name must contain at least 1 character'

So needs look in to this, Why this test is only failing on jenkins with error mentioned in point 3?

**Comment by tkolhar** [comment]
this issue occurred again dated 06/18/2015
tests.foreman.ui.test_sync.Sync.test_sync_rh_repos

Error Message

Task e3d0d3f6-0ef9-4d77-92ef-9a1c43900a6a completed with result warning. Error message(s): [u'Validation failed: Name must contain at least 1 character']

Stacktrace

  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel66-ui/tests/foreman/ui/test_sync.py", line 80, in test_sync_rh_repos
    ).upload_manifest(path=manifest_path)
  File "/home/jenkins/shiningpanda/jobs/abb3bf3f/virtualenvs/d41d8cd9/lib/python2.7/site-packages/nailgun/entities.py", line 2294, in upload_manifest
    return _handle_response(response, self._server_config, synchronous)
  File "/home/jenkins/shiningpanda/jobs/abb3bf3f/virtualenvs/d41d8cd9/lib/python2.7/site-packages/nailgun/entities.py", line 104, in _handle_response
    return ForemanTask(server_config, id=response.json()['id']).poll()
  File "/home/jenkins/shiningpanda/jobs/abb3bf3f/virtualenvs/d41d8cd9/lib/python2.7/site-packages/nailgun/entities.py", line 1419, in poll
    timeout
  File "/home/jenkins/shiningpanda/jobs/abb3bf3f/virtualenvs/d41d8cd9/lib/python2.7/site-packages/nailgun/entity_mixins.py", line 104, in _poll_task
    task_info['humanized']['errors']
'Task e3d0d3f6-0ef9-4d77-92ef-9a1c43900a6a completed with result warning. Error message(s): [u\'Validation failed: Name must contain at least 1 character\']\n--------------------

**Comment by tkolhar** [comment]
this issue occurred again dated 06/17/2015
TestNames:
tests.foreman.ui.test_sync.Sync.test_sync_rh_repos

Error Message
Task f253cfdf-982e-427d-8692-7f71b3a2a089 completed with result warning. Error message(s): [u'Validation failed: Name must contain at least 1 character']

Stacktrace
  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel71-ui/tests/foreman/ui/test_sync.py", line 80, in test_sync_rh_repos
    ).upload_manifest(path=manifest_path)
  File "/home/jenkins/shiningpanda/jobs/ca586003/virtualenvs/d41d8cd9/lib/python2.7/site-packages/nailgun/entities.py", line 2294, in upload_manifest
    return _handle_response(response, self._server_config, synchronous)
  File "/home/jenkins/shiningpanda/jobs/ca586003/virtualenvs/d41d8cd9/lib/python2.7/site-packages/nailgun/entities.py", line 104, in _handle_response
    return ForemanTask(server_config, id=response.json()['id']).poll()
  File "/home/jenkins/shiningpanda/jobs/ca586003/virtualenvs/d41d8cd9/lib/python2.7/site-packages/nailgun/entities.py", line 1419, in poll
    timeout
  File "/home/jenkins/shiningpanda/jobs/ca586003/virtualenvs/d41d8cd9/lib/python2.7/site-packages/nailgun/entity_mixins.py", line 104, in _poll_task
    task_info['humanized']['errors']
'Task f253cfdf-982e-427d-8692-7f71b3a2a089 completed with result warning. Error message(s): [u\'Validation failed: Name must contain at least 1 character\']\n--------------------

**Comment by tkolhar** [comment]
this issue occurred again dated 06/23/2015
TestNames:
tests.foreman.ui.test_sync.Sync.test_sync_rh_repos 

Error Message
Task cfa3b22c-2eb2-4a1c-a23b-a41bf99f6827 completed with result warning. Error message(s): [u'Validation failed: Name must contain at least 1 character']

Stacktrace

  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel66-ui/tests/foreman/ui/test_sync.py", line 80, in test_sync_rh_repos
    ).upload_manifest(path=manifest_path)
  File "/home/jenkins/shiningpanda/jobs/abb3bf3f/virtualenvs/d41d8cd9/lib/python2.7/site-packages/nailgun/entities.py", line 2250, in upload_manifest
    return _handle_response(response, self._server_config, synchronous)
  File "/home/jenkins/shiningpanda/jobs/abb3bf3f/virtualenvs/d41d8cd9/lib/python2.7/site-packages/nailgun/entities.py", line 105, in _handle_response
    return ForemanTask(server_config, id=response.json()['id']).poll()
  File "/home/jenkins/shiningpanda/jobs/abb3bf3f/virtualenvs/d41d8cd9/lib/python2.7/site-packages/nailgun/entities.py", line 1416, in poll
    timeout
  File "/home/jenkins/shiningpanda/jobs/abb3bf3f/virtualenvs/d41d8cd9/lib/python2.7/site-packages/nailgun/entity_mixins.py", line 105, in _poll_task
    task_info['humanized']['errors']
'Task cfa3b22c-2eb2-4a1c-a23b-a41bf99f6827 completed with result warning. Error message(s): [u\'Validation failed: Name must contain at least 1 character\']\n--------------------

**Comment by sthirugn** [comment]
failed in Snap 12

**Comment by tkolhar** [comment]
this issue occurred again dated 08/03/2015
TestNames:
tests.foreman.ui.test_sync.Sync.test_sync_rh_repos

Error Message

Task 03a71e48-97dd-4e23-9058-fa61cc8b5bd6 completed with result warning. Error message(s): [u'Validation failed: Name must contain at least 1 character']

Stacktrace

  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel66-ui/tests/foreman/ui/test_sync.py", line 80, in test_sync_rh_repos
    ).upload_manifest(path=manifest_path)
  File "/home/jenkins/shiningpanda/jobs/abb3bf3f/virtualenvs/d41d8cd9/lib/python2.7/site-packages/nailgun/entities.py", line 2380, in upload_manifest
    return _handle_response(response, self._server_config, synchronous)
  File "/home/jenkins/shiningpanda/jobs/abb3bf3f/virtualenvs/d41d8cd9/lib/python2.7/site-packages/nailgun/entities.py", line 112, in _handle_response
    return ForemanTask(server_config, id=response.json()['id']).poll()
  File "/home/jenkins/shiningpanda/jobs/abb3bf3f/virtualenvs/d41d8cd9/lib/python2.7/site-packages/nailgun/entities.py", line 1515, in poll
    timeout
  File "/home/jenkins/shiningpanda/jobs/abb3bf3f/virtualenvs/d41d8cd9/lib/python2.7/site-packages/nailgun/entity_mixins.py", line 111, in _poll_task
    task_info['humanized']['errors']
'Task 03a71e48-97dd-4e23-9058-fa61cc8b5bd6 completed with result warning. Error message(s): [u\'Validation failed: Name must contain at least 1 character\']\n--------------------

**Comment by tkolhar** [comment]
this issue failed again dated 08/07/2015
TestNames:
tests.foreman.ui.test_sync.Sync.test_sync_rh_repos

Error Message

Task 0be74f05-ec25-4675-842a-2123a8996aa3 completed with result warning. Error message(s): [u'Validation failed: Name must contain at least 1 character']

Stacktrace

  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel67-ui/tests/foreman/ui/test_sync.py", line 76, in test_sync_rh_repos
    sub.upload({'organization_id': self.org_id}, manifest)
  File "/home/jenkins/shiningpanda/jobs/1b673361/virtualenvs/d41d8cd9/lib/python2.7/site-packages/nailgun/entities.py", line 3435, in upload
    return _handle_response(response, self._server_config, synchronous)
  File "/home/jenkins/shiningpanda/jobs/1b673361/virtualenvs/d41d8cd9/lib/python2.7/site-packages/nailgun/entities.py", line 113, in _handle_response
    return ForemanTask(server_config, id=response.json()['id']).poll()
  File "/home/jenkins/shiningpanda/jobs/1b673361/virtualenvs/d41d8cd9/lib/python2.7/site-packages/nailgun/entities.py", line 1584, in poll
    timeout
  File "/home/jenkins/shiningpanda/jobs/1b673361/virtualenvs/d41d8cd9/lib/python2.7/site-packages/nailgun/entity_mixins.py", line 111, in _poll_task
    task_info['humanized']['errors']
'Task 0be74f05-ec25-4675-842a-2123a8996aa3 completed with result warning. Error message(s): [u\'Validation failed: Name must contain at least 1 character\']\n--------------------

**Comment by tkolhar** [comment]
this issue failed again dated 08/11/2015
TestNames:
tests.foreman.ui.test_sync.Sync.test_sync_rh_repos 

Error Message

Task 5fd54237-b408-4677-941e-d300aa7b0e78 completed with result warning. Error message(s): [u'Validation failed: Name must contain at least 1 character']

Stacktrace

  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel71-ui/tests/foreman/ui/test_sync.py", line 76, in test_sync_rh_repos
    sub.upload({'organization_id': self.org_id}, manifest)
  File "/home/jenkins/shiningpanda/jobs/ca586003/virtualenvs/d41d8cd9/lib/python2.7/site-packages/nailgun/entities.py", line 3435, in upload
    return _handle_response(response, self._server_config, synchronous)
  File "/home/jenkins/shiningpanda/jobs/ca586003/virtualenvs/d41d8cd9/lib/python2.7/site-packages/nailgun/entities.py", line 113, in _handle_response
    return ForemanTask(server_config, id=response.json()['id']).poll()
  File "/home/jenkins/shiningpanda/jobs/ca586003/virtualenvs/d41d8cd9/lib/python2.7/site-packages/nailgun/entities.py", line 1584, in poll
    timeout
  File "/home/jenkins/shiningpanda/jobs/ca586003/virtualenvs/d41d8cd9/lib/python2.7/site-packages/nailgun/entity_mixins.py", line 111, in _poll_task
    task_info['humanized']['errors']
'Task 5fd54237-b408-4677-941e-d300aa7b0e78 completed with result warning. Error message(s): [u\'Validation failed: Name must contain at least 1 character\']\n--------------------

**Comment by tkolhar** [comment]
this test is failing locally when executed using nosetests:
$  nosetests -c robottelo.properties -m test_sync_rh_repos /home/tkolhar/git/robottelo/tests/foreman/ui/test_sync.py
/usr/lib/python2.7/site-packages/nose/plugins/manager.py:395: RuntimeWarning: Unable to load plugin xunitmp = nose_xunitmp:XunitMP: cannot import name force_unicode
  RuntimeWarning)
2015-08-12 13:47:04 - nailgun.client - DEBUG - Making HTTP POST request to https://ibm-hs22-04.rhts.eng.brq.redhat.com/katello/api/v2/organizations with options {'verify': False, 'auth': ('admin', 'changeme'), 'headers': {'content-type': 'application/json'}} and data {"name": "\ud8ab\udcf1\ud813\udf57\udb2d\udf35"}.
2015-08-12 13:47:05 - py.warnings - WARNING - /usr/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

2015-08-12 13:47:11 - nailgun.client - DEBUG - Received HTTP 201 response: {"ancestry":null,"apply_info_task_id":null,"created_at":"2015-08-12T08:17:09Z","description":null,"id":14,"ignore_types":[],"katello_default":true,"label":"a01952d6-74b1-4132-9a01-642b480f79b4","name":"𺳱𔽗󛜵","title":"𺳱𔽗󛜵","updated_at":"2015-08-12T08:17:09Z","service_levels":[],"service_level":null}
@Test: Create Content RedHat Sync with two repos. ... ERROR
ERROR


ERROR: @Test: Create Content RedHat Sync with two repos.

Traceback (most recent call last):
  File "/home/tkolhar/git/robottelo/tests/foreman/ui/test_sync.py", line 76, in test_sync_rh_repos
    sub.upload({'organization_id': self.org_id}, manifest)
AttributeError: 'Subscription' object has no attribute 'upload'


ERROR: @Test: Create Content RedHat Sync with two repos.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tkolhar/git/robottelo/robottelo/test.py", line 282, in tearDown
    self.take_screenshot(self._testMethodName)
  File "/home/tkolhar/git/robottelo/robottelo/test.py", line 270, in take_screenshot
    directory,
  File "/usr/lib64/python2.7/posixpath.py", line 77, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'

XML: foreman-results.xml

Ran 1 test in 47.630s

FAILED (errors=2)

**Comment by tkolhar** [comment]
this issue occurred again dated 08/19/2015
TestNames:
tests.foreman.ui.test_sync.Sync.test_sync_rh_repos

Error Message

Task a628a685-fa77-44b9-bbb2-1570bb073c4a completed with result warning. Error message(s): [u'Validation failed: Name must contain at least 1 character']

Stacktrace

  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel67-ui/tests/foreman/ui/test_sync.py", line 77, in test_sync_rh_repos
    files={'content': manifest},
  File "/home/jenkins/shiningpanda/jobs/1b673361/virtualenvs/d41d8cd9/lib/python2.7/site-packages/nailgun/entities.py", line 3494, in upload
    return _handle_response(response, self._server_config, synchronous)
  File "/home/jenkins/shiningpanda/jobs/1b673361/virtualenvs/d41d8cd9/lib/python2.7/site-packages/nailgun/entities.py", line 113, in _handle_response
    return ForemanTask(server_config, id=response.json()['id']).poll()
  File "/home/jenkins/shiningpanda/jobs/1b673361/virtualenvs/d41d8cd9/lib/python2.7/site-packages/nailgun/entities.py", line 1633, in poll
    timeout
  File "/home/jenkins/shiningpanda/jobs/1b673361/virtualenvs/d41d8cd9/lib/python2.7/site-packages/nailgun/entity_mixins.py", line 111, in _poll_task
    task_info['humanized']['errors']
'Task a628a685-fa77-44b9-bbb2-1570bb073c4a completed with result warning. Error message(s): [u\'Validation failed: Name must contain at least 1 character\']\n--------------------

**Comment by tkolhar** [comment]
this issue occurred again dated 08/26/2015
TestNames:
tests.foreman.ui.test_sync.Sync.test_sync_rh_repos

Error Message

Task b3c7c3be-8a70-4c38-9454-c4d0f75debe1 completed with result warning. Error message(s): [u'Validation failed: Name must contain at least 1 character']

Stacktrace

  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel67-ui/tests/foreman/ui/test_sync.py", line 76, in test_sync_rh_repos
    upload_manifest(self.org_id, manifest)
  File "robottelo/api/utils.py", line 67, in upload_manifest
    files={'content': manifest},
  File "/home/jenkins/shiningpanda/jobs/1b673361/virtualenvs/d41d8cd9/lib/python2.7/site-packages/nailgun/entities.py", line 3513, in upload
    return _handle_response(response, self._server_config, synchronous)
  File "/home/jenkins/shiningpanda/jobs/1b673361/virtualenvs/d41d8cd9/lib/python2.7/site-packages/nailgun/entities.py", line 113, in _handle_response
    return ForemanTask(server_config, id=response.json()['id']).poll()
  File "/home/jenkins/shiningpanda/jobs/1b673361/virtualenvs/d41d8cd9/lib/python2.7/site-packages/nailgun/entities.py", line 1651, in poll
    timeout
  File "/home/jenkins/shiningpanda/jobs/1b673361/virtualenvs/d41d8cd9/lib/python2.7/site-packages/nailgun/entity_mixins.py", line 111, in _poll_task
    task_info['humanized']['errors']
'Task b3c7c3be-8a70-4c38-9454-c4d0f75debe1 completed with result warning. Error message(s): [u\'Validation failed: Name must contain at least 1 character\']\n--------------------
