### ISSUE TITLE
Automation failure : test_delete_cv_version

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2311]
TestNames:
tests.foreman.cli.test_contentviews.TestContentView.test_delete_cv_version

Error Message
70 != 0
robottelo.common.ssh: DEBUG: >>> [qe-foreman-rhel66.usersys.redhat.com] LANG=en_US.UTF-8 hammer -v -u admin -p changeme  content-view remove-from-environment --lifecycle-environment-id="242" --id="294"
robottelo.common.ssh: INFO: Instantiated Paramiko client 0x261e290
robottelo.common.ssh: INFO: Destroying Paramiko client 0x261e290
robottelo.common.ssh: INFO: Destroyed Paramiko client 0x261e290
robottelo.common.ssh: DEBUG: <<< [ERROR 2015-05-26 21:45:00 Exception] Required lock is already taken by other running tasks.
Please inspect their state, fix their errors and resume them.

Required lock: read
Conflicts with tasks:
- https://qe-foreman-rhel66.usersys.redhat.com/foreman_tasks/tasks/8a72d58c-530a-4ae6-ba6b-a0b0bed8e953
Could not remove the content view from environment:
  Required lock is already taken by other running tasks.
  Please inspect their state, fix their errors and resume them.
  
  Required lock: read
  Conflicts with tasks:
  - https://qe-foreman-rhel66.usersys.redhat.com/foreman_tasks/tasks/8a72d58c-530a-4ae6-ba6b-a0b0bed8e953
[ERROR 2015-05-26 21:45:00 Exception] 

RestClient::InternalServerError (500 Internal Server Error):
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/abstract_response.rb:48:in `return!'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:230:in `process_result'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:178:in `transmit'
    /usr/lib/ruby/1.8/net/http.rb:543:in `start'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:172:in `transmit'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:64:in `execute'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `execute'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/resource.rb:97:in `delete'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.13/lib/apipie_bindings/api.rb:280:in `send'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.13/lib/apipie_bindings/api.rb:280:in `call_client'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.13/lib/apipie_bindings/api.rb:211:in `http_call'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.13/lib/apipie_bindings/api.rb:162:in `call'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.13/lib/apipie_bindings/resource.rb:14:in `call'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.2.0/lib/hammer_cli/./apipie/command.rb:43:in `send_request'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli_foreman-0.2.0/lib/hammer_cli_foreman/commands.rb:185:in `send_request'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli_foreman_tasks-0.0.6/lib/hammer_cli_foreman_tasks/async_command.rb:14:in `execute'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:68:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.2.0/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:68:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.2.0/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:68:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.2.0/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:126:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.2.0/bin/hammer:108
    /usr/bin/hammer:19:in `load'
    /usr/bin/hammer:19

filed a bz https://bugzilla.redhat.com/show_bug.cgi?id=1225444
please fix it thanks

**Comment by tkolhar** [comment]
this issue occurred again dated 06/24/2015
Error Message

Failed to create Repository with data:
{
  "checksum-type": null, 
  "content-type": "yum", 
  "docker-upstream-name": null, 
  "gpg-key": null, 
  "gpg-key-id": null, 
  "label": null, 
  "name": "DGAMenYjFVNHSHH", 
  "organization": null, 
  "organization-id": null, 
  "organization-label": null, 
  "product": null, 
  "product-id": "1841", 
  "publish-via-http": "true", 
  "url": "http://inecas.fedorapeople.org/fakerepos/zoo3/"
}

robottelo.common.ssh: DEBUG: >>> [qe-foreman-rhel71.usersys.redhat.com] LANG=en_US.UTF-8 hammer -v -u admin -p changeme --output=csv repository create --product-id="1841" --name="DGAMenYjFVNHSHH" --publish-via-http="true" --url="http://inecas.fedorapeople.org/fakerepos/zoo3/" --content-type="yum"
robottelo.common.ssh: INFO: Instantiated Paramiko client 0x3be63d0
robottelo.common.ssh: INFO: Destroying Paramiko client 0x3be63d0
robottelo.common.ssh: INFO: Destroyed Paramiko client 0x3be63d0
robottelo.common.ssh: DEBUG: <<< stderr
[ERROR 2015-06-24 21:46:15 Exception] There was an issue with the backend service pulp: Pulp message bus connection issue.
Could not create the repository:
  There was an issue with the backend service pulp: Pulp message bus connection issue.
[ERROR 2015-06-24 21:46:15 Exception] 

RestClient::InternalServerError (500 Internal Server Error):
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/abstract_response.rb:48:in `return!'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:234:in `process_result'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:182:in `block in transmit'
    /usr/share/ruby/net/http.rb:852:in `start'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:176:in `transmit'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:65:in `execute'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:34:in `execute'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/resource.rb:67:in `post'
    /usr/share/gems/gems/apipie-bindings-0.0.13/lib/apipie_bindings/api.rb:280:in `call_client'
    /usr/share/gems/gems/apipie-bindings-0.0.13/lib/apipie_bindings/api.rb:211:in `http_call'
    /usr/share/gems/gems/apipie-bindings-0.0.13/lib/apipie_bindings/api.rb:161:in `call'
    /usr/share/gems/gems/apipie-bindings-0.0.13/lib/apipie_bindings/resource.rb:14:in `call'
    /usr/share/gems/gems/hammer_cli-0.2.0/lib/hammer_cli/apipie/command.rb:43:in `send_request'
    /usr/share/gems/gems/hammer_cli_foreman-0.2.0/lib/hammer_cli_foreman/commands.rb:185:in `send_request'
    /usr/share/gems/gems/hammer_cli-0.2.0/lib/hammer_cli/apipie/command.rb:34:in `execute'
    /usr/share/gems/gems/clamp-1.0.0/lib/clamp/command.rb:68:in `run'
    /usr/share/gems/gems/hammer_cli-0.2.0/lib/hammer_cli/abstract.rb:23:in `run'
    /usr/share/gems/gems/clamp-1.0.0/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/share/gems/gems/clamp-1.0.0/lib/clamp/command.rb:68:in `run'
    /usr/share/gems/gems/hammer_cli-0.2.0/lib/hammer_cli/abstract.rb:23:in `run'
    /usr/share/gems/gems/clamp-1.0.0/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/share/gems/gems/clamp-1.0.0/lib/clamp/command.rb:68:in `run'
    /usr/share/gems/gems/hammer_cli-0.2.0/lib/hammer_cli/abstract.rb:23:in `run'
    /usr/share/gems/gems/clamp-1.0.0/lib/clamp/command.rb:133:in `run'
    /usr/share/gems/gems/hammer_cli-0.2.0/bin/hammer:108:in `<top (required)>'
    /usr/bin/hammer:23:in `load'
    /usr/bin/hammer:23:in `<main>'

Stacktrace

  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "/home/jenkins/workspace/satellite6-automation-upstream-rhel71-cli/tests/foreman/cli/test_contentviews.py", line 288, in test_delete_cv_version
    new_repo = make_repository({u'product-id': new_product['id']})
  File "robottelo/common/decorators.py", line 76, in cacheable_function
    new_object = func(options)
  File "robottelo/cli/factory.py", line 640, in make_repository
    return create_object(Repository, args, options)
  File "robottelo/cli/factory.py", line 94, in create_object
    json.dumps(options, indent=2, sort_keys=True)
'Failed to create Repository with data:\n{\n  "checksum-type": null, \n  "content-type": "yum", \n  "docker-upstream-name": null, \n  "gpg-key": null, \n  "gpg-key-id": null, \n  "label": null, \n  "name": "DGAMenYjFVNHSHH", \n  "organization": null, \n  "organization-id": null, \n  "organization-label": null, \n  "product": null, \n  "product-id": "1841", \n  "publish-via-http": "true", \n  "url": "http://inecas.fedorapeople.org/fakerepos/zoo3/"\n}

**Comment by tkolhar** [comment]
closing this as this issue is added a to a common github issue created for all upstream failures
