### ISSUE TITLE
Automation failure : test_manifest_refresh

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2352]
TestNames:

* tests.foreman.cli.test_subscription.TestSubscription.test_manifest_refresh

```
robottelo.common.ssh: DEBUG: >>> [qe-foreman-rhel66.usersys.redhat.com] LANG=en_US.UTF-8 hammer -v -u admin -p changeme --output=csv subscription list --organization-id="302"
robottelo.common.ssh: INFO: Instantiated Paramiko client 0x5125510
robottelo.common.ssh: INFO: Destroying Paramiko client 0x5125510
robottelo.common.ssh: INFO: Destroyed Paramiko client 0x5125510
robottelo.common.ssh: DEBUG: <<< stdout
Name,Contract,Account,Support,Quantity,Consumed,End Date,ID,Product,Quantity,Attached
Employee SKU,10169793,477931,Self-Support,10,0,2022-01-01,ff8080814dac817b014dace1bb743225,Employee SKU,10,0
Red Hat Satellite Employee Subscription,10461238,477931,Self-Support,1,0,2022-01-01,ff8080814dac817b014dace1ba033206,Red Hat Satellite Employee Subscription,1,0

robottelo.common.ssh: DEBUG: >>> [qe-foreman-rhel66.usersys.redhat.com] LANG=en_US.UTF-8 hammer -v -u admin -p changeme  subscription refresh-manifest --organization-id="302"
robottelo.common.ssh: INFO: Instantiated Paramiko client 0x5125850
robottelo.common.ssh: INFO: Destroying Paramiko client 0x5125850
robottelo.common.ssh: INFO: Destroyed Paramiko client 0x5125850
robottelo.common.ssh: DEBUG: <<< stderr
Task 6d686135-12e2-4ab9-9479-6578ea88bbb4 running: 0.0/1, 0%, elapsed: 00:00:00
Task 6d686135-12e2-4ab9-9479-6578ea88bbb4 warning: 1.0/1, 100%, 0.5/s, elapsed: 00:00:02
Task 6d686135-12e2-4ab9-9479-6578ea88bbb4 warning: 1.0/1, 100%, 0.5/s, elapsed: 00:00:02
Consumer with id 38690dc8-0803-11e5-b8d9-92968d3c3cdf could not be found.

Stacktrace

  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "robottelo/common/decorators.py", line 375, in wrapper_func
    return func(*args, **kwargs)
  File "/home/jenkins/workspace/satellite6-automation-upstream-rhel66-cli/tests/foreman/cli/test_subscription.py", line 172, in test_manifest_refresh
    self.assertEqual(len(result.stderr), 0)
  File "/usr/lib64/python2.7/unittest/case.py", line 553, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib64/python2.7/unittest/case.py", line 546, in _baseAssertEqual
    raise self.failureException(msg)
'74 != 0\n-------------------
```

**Comment by tkolhar** [comment]
will add the nosetests result when system is up and running

**Comment by tkolhar** [comment]
this issue occurred  again dated 7/8/2015
TestNames:
tests.foreman.cli.test_subscription.TestSubscription.test_manifest_refresh

Error Message
69 != 0


robottelo.common.ssh: DEBUG: >>> [qe-sat6-rhel71.usersys.redhat.com] LANG=en_US.UTF-8 hammer -v -u admin -p changeme  subscription refresh-manifest --organization-id="389"
robottelo.common.ssh: INFO: Instantiated Paramiko client 0x431f1d0
robottelo.common.ssh: INFO: Destroying Paramiko client 0x431f1d0
robottelo.common.ssh: INFO: Destroyed Paramiko client 0x431f1d0
robottelo.common.ssh: DEBUG: <<< stderr
Task 29cc795d-6cf8-402e-91d6-0ec8a9732a23 running: 0.0/1, 0%, elapsed: 00:00:00
Task 29cc795d-6cf8-402e-91d6-0ec8a9732a23 running: 0.0/1, 0%, 0.0/s, elapsed: 00:00:02
Task 29cc795d-6cf8-402e-91d6-0ec8a9732a23 running: 0.0/1, 0%, 0.0/s, elapsed: 00:00:04
Task 29cc795d-6cf8-402e-91d6-0ec8a9732a23 running: 0.0/1, 0%, 0.0/s, elapsed: 00:00:06
Task 29cc795d-6cf8-402e-91d6-0ec8a9732a23 running: 0.0/1, 0%, 0.0/s, elapsed: 00:00:08
Task 29cc795d-6cf8-402e-91d6-0ec8a9732a23 running: 0.0/1, 0%, 0.0/s, elapsed: 00:00:10
Task 29cc795d-6cf8-402e-91d6-0ec8a9732a23 warning: 1.0/1, 100%, 0.1/s, elapsed: 00:00:12
Task 29cc795d-6cf8-402e-91d6-0ec8a9732a23 warning: 1.0/1, 100%, 0.1/s, elapsed: 00:00:12
Runtime Error null at org.candlepin.sync.Exporter.exportProducts:517


Stacktrace
  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel71-cli/tests/foreman/cli/test_subscription.py", line 170, in test_manifest_refresh
    self.assertEqual(len(result.stderr), 0)
  File "/usr/lib64/python2.7/unittest/case.py", line 553, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib64/python2.7/unittest/case.py", line 546, in _baseAssertEqual
    raise self.failureException(msg)
'69 != 0\n--------------------

**Comment by sthirugn** [comment]
Failed in Snap 12

**Comment by tkolhar** [comment]
this test is failing when executed locally using nosetests:
$ nosetests -c robottelo.properties -m test_manifest_refresh /home/tkolhar/git/robottelo/tests/foreman/cli/test_subscription.py
FAIL
FAIL: @Test: upload manifest (positive) and refresh
Traceback (most recent call last):
  File "/home/tkolhar/git/robottelo/tests/foreman/cli/test_subscription.py", line 170, in test_manifest_refresh
    self.assertEqual(len(result.stderr), 0)
AssertionError: 59 != 0

XML: foreman-results.xml

Ran 1 test in 106.019s

FAILED (failures=1)

**Comment by sthirugn** [comment]
@tkolhar Did this fail in latest automation run? If it just fails locally, I am not sure if we want to reopen issues.

**Comment by tkolhar** [comment]
@sthirugn  this results for latest snap

**Comment by tkolhar** [comment]
this issue failed again dated 08/10/2015
TestNames:
tests.foreman.cli.test_subscription.TestSubscription.test_manifest_refresh

Error Message
16 != 0

Stacktrace

  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel67-cli/tests/foreman/cli/test_subscription.py", line 170, in test_manifest_refresh
    self.assertEqual(len(result.stderr), 0)
  File "/usr/lib64/python2.7/unittest/case.py", line 553, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib64/python2.7/unittest/case.py", line 546, in _baseAssertEqual
    raise self.failureException(msg)
'16 != 0\n--------------------

**Comment by tkolhar** [comment]
this issue is failing when tested locally using nosetests:
$ nosetests -c robottelo.properties -m test_manifest_refresh /home/tkolhar/git/robottelo/tests/foreman/cli/test_subscription.py
2015-08-12 12:33:48 - robottelo.common.ssh - DEBUG - >>> [ibm-hs22-04.rhts.eng.brq.redhat.com] LANG=en_US.UTF-8  hammer -v -u admin -p changeme --output=csv subscription list --organization-id="13"
2015-08-12 12:33:51 - robottelo.common.ssh - INFO - Instantiated Paramiko client 0x33e0650
2015-08-12 12:33:55 - robottelo.common.ssh - INFO - Destroying Paramiko client 0x33e0650
2015-08-12 12:33:55 - robottelo.common.ssh - INFO - Destroyed Paramiko client 0x33e0650
2015-08-12 12:33:55 - robottelo.common.ssh - DEBUG - <<< stdout
Name,Contract,Account,Support,Quantity,Consumed,End Date,ID,Product,Quantity,Attached
CloudForms Employee Subscription,10041814,477931,Self-Support,10,0,2022-01-01,8aa800eb4f1727aa014f20b87b3501ba,CloudForms Employee Subscription,10,0
Red Hat Employee Subscription,10169793,477931,SELF-SUPPORT,10,0,2022-01-01,8aa800eb4f1727aa014f20b87cc501ca,Red Hat Employee Subscription,10,0

2015-08-12 12:33:55 - robottelo.common.ssh - DEBUG - >>> [ibm-hs22-04.rhts.eng.brq.redhat.com] LANG=en_US.UTF-8  hammer -v -u admin -p changeme  subscription refresh-manifest --organization-id="13"
2015-08-12 12:33:58 - robottelo.common.ssh - INFO - Instantiated Paramiko client 0x33e5c10
2015-08-12 12:34:05 - robottelo.common.ssh - INFO - Destroying Paramiko client 0x33e5c10
2015-08-12 12:34:05 - robottelo.common.ssh - INFO - Destroyed Paramiko client 0x33e5c10
2015-08-12 12:34:05 - robottelo.common.ssh - DEBUG - <<< stderr
Task e232b85f-5804-445e-ae47-2253c220c96c running: 0.0/1, 0%, elapsed: 00:00:00
Task e232b85f-5804-445e-ae47-2253c220c96c warning: 1.0/1, 100%, 0.5/s, elapsed: 00:00:02
Task e232b85f-5804-445e-ae47-2253c220c96c warning: 1.0/1, 100%, 0.5/s, elapsed: 00:00:02
Unit 2f20e47c-8f94-4fcc-a180-243a380b0e76 has been deleted

FAIL
FAIL: @Test: upload manifest (positive) and refresh
Traceback (most recent call last):
  File "/home/tkolhar/git/robottelo/tests/foreman/cli/test_subscription.py", line 170, in test_manifest_refresh
    self.assertEqual(len(result.stderr), 0)
AssertionError: 59 != 0

XML: foreman-results.xml
Ran 1 test in 186.408s

FAILED (failures=1)

**Comment by tkolhar** [comment]
closing this as this issue is added a to a common github issue created for all downstream failures
