### ISSUE TITLE
Automation failure : test_contenthost_apply_errata

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2353]
TestNames:
tests.foreman.cli.test_contenthost.TestCHKatelloAgent.test_contenthost_apply_errata

robottelo.common.ssh: DEBUG: >>> [qe-foreman-rhel66.usersys.redhat.com] LANG=en_US.UTF-8 hammer -v -u admin -p changeme  content-view version promote --id="219" --organization-id="219" --to-lifecycle-environment-id="225"
robottelo.common.ssh: INFO: Instantiated Paramiko client 0x433ecd0
robottelo.common.ssh: INFO: Destroying Paramiko client 0x433ecd0
robottelo.common.ssh: INFO: Destroyed Paramiko client 0x433ecd0
robottelo.common.ssh: DEBUG: <<< stderr
[ERROR 2015-05-31 21:10:06 Exception] Required lock is already taken by other running tasks.
Please inspect their state, fix their errors and resume them.

Required lock: read
Conflicts with tasks:
- https://qe-foreman-rhel66.usersys.redhat.com/foreman_tasks/tasks/360043ca-8b28-4078-9f2f-b5c43beb7f44
Could not promote the content view:
  Required lock is already taken by other running tasks.
  Please inspect their state, fix their errors and resume them.
  
  Required lock: read
  Conflicts with tasks:
  - https://qe-foreman-rhel66.usersys.redhat.com/foreman_tasks/tasks/360043ca-8b28-4078-9f2f-b5c43beb7f44
[ERROR 2015-05-31 21:10:06 Exception] 

RestClient::InternalServerError (500 Internal Server Error):
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/abstract_response.rb:48:in `return!'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:230:in `process_result'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:178:in `transmit'
    /usr/lib/ruby/1.8/net/http.rb:543:in `start'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:172:in `transmit'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:64:in `execute'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `execute'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/resource.rb:71:in `post'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.13/lib/apipie_bindings/api.rb:280:in `send'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.13/lib/apipie_bindings/api.rb:280:in `call_client'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.13/lib/apipie_bindings/api.rb:211:in `http_call'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.13/lib/apipie_bindings/api.rb:162:in `call'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.13/lib/apipie_bindings/resource.rb:14:in `call'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.2.0/lib/hammer_cli/./apipie/command.rb:43:in `send_request'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli_foreman-0.2.0/lib/hammer_cli_foreman/commands.rb:185:in `send_request'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli_foreman_tasks-0.0.6/lib/hammer_cli_foreman_tasks/async_command.rb:14:in `execute'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:68:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.2.0/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:68:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.2.0/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:68:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.2.0/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:68:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.2.0/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:126:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.2.0/bin/hammer:108
    /usr/bin/hammer:19:in `load'
    /usr/bin/hammer:19

Stacktrace

  File "/usr/lib64/python2.7/unittest/case.py", line 360, in run
    self.setUp()
  File "/home/jenkins/workspace/satellite6-automation-upstream-rhel66-cli/tests/foreman/cli/test_contenthost.py", line 594, in setUp
    u'activationkey-id': TestCHKatelloAgent.activation_key['id'],
  File "robottelo/common/decorators.py", line 76, in cacheable_function
    new_object = func(options)
  File "robottelo/cli/factory.py", line 1801, in setup_org_for_a_rh_repo
    raise CLIFactoryError('Failed to promote version to next environment')
'Failed to promote version to next environment\n

**Comment by tkolhar** [comment]
will add the nosetests result when system is up and running

**Comment by tkolhar** [comment]
filed a bz : https://bugzilla.redhat.com/show_bug.cgi?id=1227302
