### ISSUE TITLE
Automation failure : test_contenthost_get_errata_info

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2354]
TestNames:
tests.foreman.cli.test_contenthost.TestCHKatelloAgent.test_contenthost_get_errata_info

robottelo.common.ssh: DEBUG: >>> [qe-foreman-rhel66.usersys.redhat.com] LANG=en_US.UTF-8 hammer -v -u admin -p changeme --output=csv repository-set enable --product="Red Hat Enterprise Linux Server" --basearch="x86_64" --releasever="7Server" --name="Red Hat Satellite Tools 6 Beta (for RHEL 7 Server) (RPMs)" --organization-id="219"
robottelo.common.ssh: INFO: Instantiated Paramiko client 0x4418d50
robottelo.common.ssh: INFO: Destroying Paramiko client 0x4418d50
robottelo.common.ssh: INFO: Destroyed Paramiko client 0x4418d50
robottelo.common.ssh: DEBUG: <<< stderr
[ERROR 2015-05-31 21:10:26 Exception] Error: 409 Conflict
Could not enable repository:
  Error: 409 Conflict
[ERROR 2015-05-31 21:10:26 Exception] 

RestClient::Conflict (409 Conflict):
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/abstract_response.rb:48:in `return!'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:230:in `process_result'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:178:in `transmit'
    /usr/lib/ruby/1.8/net/http.rb:543:in `start'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:172:in `transmit'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:64:in `execute'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `execute'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/resource.rb:80:in `put'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.13/lib/apipie_bindings/api.rb:280:in `send'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.13/lib/apipie_bindings/api.rb:280:in `call_client'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.13/lib/apipie_bindings/api.rb:211:in `http_call'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.13/lib/apipie_bindings/api.rb:162:in `call'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.13/lib/apipie_bindings/resource.rb:14:in `call'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.2.0/lib/hammer_cli/./apipie/command.rb:43:in `send_request'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli_foreman-0.2.0/lib/hammer_cli_foreman/commands.rb:185:in `send_request'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.2.0/lib/hammer_cli/./apipie/command.rb:34:in `execute'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:68:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.2.0/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:68:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.2.0/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:68:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.2.0/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:126:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.2.0/bin/hammer:108
    /usr/bin/hammer:19:in `load'
    /usr/bin/hammer:19

Stacktrace

  File "/usr/lib64/python2.7/unittest/case.py", line 360, in run
    self.setUp()
  File "/home/jenkins/workspace/satellite6-automation-upstream-rhel66-cli/tests/foreman/cli/test_contenthost.py", line 594, in setUp
    u'activationkey-id': TestCHKatelloAgent.activation_key['id'],
  File "robottelo/common/decorators.py", line 76, in cacheable_function
    new_object = func(options)
  File "robottelo/cli/factory.py", line 1759, in setup_org_for_a_rh_repo
    raise CLIFactoryError('Failed to enable repository set')
'Failed to enable repository set\n--------------------

**Comment by tkolhar** [comment]
will add the nosetests result when system is up and running
