### ISSUE TITLE
Automation failure : test_remove_cv_environment 

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2355]
TestNames:
tests.foreman.cli.test_contentviews.TestContentView.test_remove_cv_environment

Error Message
70 != 0

robottelo.common.ssh: DEBUG: >>> [qe-foreman-rhel66.usersys.redhat.com] LANG=en_US.UTF-8 hammer -v -u admin -p changeme  content-view remove --id="282" --organization-id="229" --environment-ids="248"
robottelo.common.ssh: INFO: Instantiated Paramiko client 0x4769c50
robottelo.common.ssh: INFO: Destroying Paramiko client 0x4769c50
robottelo.common.ssh: INFO: Destroyed Paramiko client 0x4769c50
robottelo.common.ssh: DEBUG: <<< stderr
[ERROR 2015-05-31 21:25:06 Exception] Required lock is already taken by other running tasks.
Please inspect their state, fix their errors and resume them.

Required lock: read
Conflicts with tasks:
- https://qe-foreman-rhel66.usersys.redhat.com/foreman_tasks/tasks/2b7dc429-adb5-4e2a-ba70-05be49fba23d
Could not remove objects from content view:
  Required lock is already taken by other running tasks.
  Please inspect their state, fix their errors and resume them.
  
  Required lock: read
  Conflicts with tasks:
  - https://qe-foreman-rhel66.usersys.redhat.com/foreman_tasks/tasks/2b7dc429-adb5-4e2a-ba70-05be49fba23d
[ERROR 2015-05-31 21:25:06 Exception] 

RestClient::InternalServerError (500 Internal Server Error):
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/abstract_response.rb:48:in `return!'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:230:in `process_result'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:178:in `transmit'
    /usr/lib/ruby/1.8/net/http.rb:543:in `start'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:172:in `transmit'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:64:in `execute'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `execute'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/resource.rb:80:in `put'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.13/lib/apipie_bindings/api.rb:280:in `send'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.13/lib/apipie_bindings/api.rb:280:in `call_client'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.13/lib/apipie_bindings/api.rb:211:in `http_call'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.13/lib/apipie_bindings/api.rb:162:in `call'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.13/lib/apipie_bindings/resource.rb:14:in `call'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.2.0/lib/hammer_cli/./apipie/command.rb:43:in `send_request'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli_foreman-0.2.0/lib/hammer_cli_foreman/commands.rb:185:in `send_request'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli_foreman_tasks-0.0.6/lib/hammer_cli_foreman_tasks/async_command.rb:14:in `execute'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:68:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.2.0/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:68:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.2.0/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:68:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.2.0/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:126:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.2.0/bin/hammer:108
    /usr/bin/hammer:19:in `load'
    /usr/bin/hammer:19

Stacktrace

  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "/home/jenkins/workspace/satellite6-automation-upstream-rhel66-cli/tests/foreman/cli/test_contentviews.py", line 340, in test_remove_cv_environment
    self.assertEqual(result.return_code, 0)
  File "/usr/lib64/python2.7/unittest/case.py", line 553, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib64/python2.7/unittest/case.py", line 546, in _baseAssertEqual
    raise self.failureException(msg)
'70 != 0\n--------------------

**Comment by tkolhar** [comment]
will add the nosetests result when system is up and running

**Comment by tkolhar** [comment]
filed a bz : https://bugzilla.redhat.com/show_bug.cgi?id=1227309

**Comment by tkolhar** [comment]
closing this as this issue is added a to a common github issue created for all upstream failures
