### ISSUE TITLE
CLI Automation failure : test_import_orgs_manifests 

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2443]
TestNames:
tests.foreman.cli.test_import.TestImport.test_import_orgs_manifests

Error Message
'Created 3 organizations.' not found in u'Waiting for the task [f9b9200b-e25b-4b78-9b82-1a74de999690] .........Waiting for the task [f8349779-b5d4-447c-a822-5e58d8a4a770] .........Waiting for the task [f389af27-841a-49a5-8f6b-93e2acdbc586] .........Summary  Uploaded 3 manifests.'

Stacktrace

  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel71-cli/tests/foreman/cli/test_import.py", line 129, in test_import_orgs_manifests
    self.assertIn('Created 3 organizations.', ''.join(ssh_import.stdout))
  File "/usr/lib64/python2.7/unittest/case.py", line 843, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/lib64/python2.7/unittest/case.py", line 450, in fail
    raise self.failureException(msg)
'\'Created 3 organizations.\' not found in u\'Waiting for the task [f9b9200b-e25b-4b78-9b82-1a74de999690] .........Waiting for the task [f8349779-b5d4-447c-a822-5e58d8a4a770] .........Waiting for the task [f389af27-841a-49a5-8f6b-93e2acdbc586] .........Summary  Uploaded 3 manifests.\'\n--------------------

**Comment by tkolhar** [comment]
when executed locally using nosetest
$ nosetests -c robottelo.properties -m test_import_orgs_manifests /home/tkolhar/git/robottelo/tests/foreman/cli/test_import.py
/usr/lib/python2.7/site-packages/nose/plugins/manager.py:395: RuntimeWarning: Unable to load plugin xunitmp = nose_xunitmp:XunitMP: cannot import name force_unicode
  RuntimeWarning)
@test: Import all organizations from the default data set ... 2015-06-15 16:33:16 - robottelo - DEBUG - Running test TestImport/test_import_orgs_manifests
2015-06-15 16:33:16 - robottelo.common.ssh - DEBUG - >>> [qe-sat6-rhel71.usersys.redhat.com] mktemp -d
2015-06-15 16:33:19 - robottelo.common.ssh - INFO - Instantiated Paramiko client 0x371ba90
2015-06-15 16:33:20 - robottelo.common.ssh - INFO - Destroying Paramiko client 0x371ba90
2015-06-15 16:33:20 - robottelo.common.ssh - INFO - Destroyed Paramiko client 0x371ba90
2015-06-15 16:33:20 - robottelo.common.ssh - DEBUG - <<< stdout
/tmp/tmp.3xn5RcIkQb

ERROR

======================================================================
ERROR: @test: Import all organizations from the default data set
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tkolhar/git/robottelo/tests/foreman/cli/test_import.py", line 111, in test_import_orgs_manifests
    files = prepare_import_data()[1]
  File "/home/tkolhar/git/robottelo/robottelo/common/helpers.py", line 326, in prepare_import_data
    tar_remote_path = conf.properties['transitions.export_tar.url']
KeyError: 'transitions.export_tar.url'
XML: foreman-results.xml
Ran 1 test in 4.083s

FAILED (errors=1)

**Comment by tkolhar** [comment]
this issue occurred again dated 15th June 2015
Error Message

'Created 3 organizations.' not found in u'Waiting for the task [504590c8-1ac4-45e1-b8d2-53947c51ce60] .........Waiting for the task [7b95db21-9e17-4203-9c0b-ca2bd2d5d6ab] .........Waiting for the task [f50ce983-5c2f-4a8a-8c32-0ea39aa73ef9] .........Summary  Uploaded 3 manifests.'

Stacktrace

  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel66-cli/tests/foreman/cli/test_import.py", line 129, in test_import_orgs_manifests
    self.assertIn('Created 3 organizations.', ''.join(ssh_import.stdout))
  File "/usr/lib64/python2.7/unittest/case.py", line 843, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/lib64/python2.7/unittest/case.py", line 450, in fail
    raise self.failureException(msg)
'\'Created 3 organizations.\' not found in u\'Waiting for the task [504590c8-1ac4-45e1-b8d2-53947c51ce60] .........Waiting for the task [7b95db21-9e17-4203-9c0b-ca2bd2d5d6ab] .........Waiting for the task [f50ce983-5c2f-4a8a-8c32-0ea39aa73ef9] .........Summary  Uploaded 3 manifests.\'\n--------------------

**Comment by rplevka** [comment]
@tkolhar - The issue has occurred again only for `downstream-rhel66-cli` job because it started __before__ the fix  was merged. The `downstream-rhel71-cli` job is fine because it has started later.

You can check the build and see the changes introduced in it by clicking the build number and see the section `Changes`.

**Comment by rplevka** [comment]
Verified - 
Jenkins report for build #48:

Test name | Duration | Status
------------ | ------------| ------------
test_bz1160847_translate_macros	| 15 sec |	Passed
test_import_orgs_default	 | 15 sec |	Passed
test_import_orgs_manifests |	2 min 4 sec |	Fixed
test_import_users_default |	9.4 sec |	Passed
test_reimport_orgs_default |	6.2 sec |	Passed

Closing the issue
