### ISSUE TITLE
CLI Automation failure : test_update_negative_1__u_new_name

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2449]
TestNames:
tests.foreman.cli.test_computeresource.TestComputeResource.test_update_negative_1__u_new_name

Error Message
70 != 0

robottelo.common.ssh: DEBUG: >>> [qe-sat6-rhel66.usersys.redhat.com] LANG=en_US.UTF-8 hammer -v -u admin -p changeme  compute-resource info --id="42"
robottelo.common.ssh: INFO: Instantiated Paramiko client 0x32d3890
robottelo.common.ssh: INFO: Destroying Paramiko client 0x32d3890
robottelo.common.ssh: INFO: Destroyed Paramiko client 0x32d3890
robottelo.common.ssh: DEBUG: <<< stderr
[ERROR 2015-06-15 12:54:17 Exception] Error: Connection refused - connect(2)
Error: Connection refused - connect(2)
[ERROR 2015-06-15 12:54:17 Exception] 

Errno::ECONNREFUSED (Connection refused - connect(2)):
    /usr/lib/ruby/1.8/net/http.rb:560:in `initialize'
    /usr/lib/ruby/1.8/net/http.rb:560:in `open'
    /usr/lib/ruby/1.8/net/http.rb:560:in `connect'
    /usr/lib/ruby/1.8/timeout.rb:53:in `timeout'
    /usr/lib/ruby/1.8/timeout.rb:101:in `timeout'
    /usr/lib/ruby/1.8/net/http.rb:560:in `connect'
    /usr/lib/ruby/1.8/net/http.rb:553:in `do_start'
    /usr/lib/ruby/1.8/net/http.rb:542:in `start'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:172:in `transmit'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:64:in `execute'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `execute'
    /usr/lib/ruby/gems/1.8/gems/rest-client-1.6.7/lib/restclient/resource.rb:54:in `get'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:279:in `send'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:279:in `call_client'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:210:in `http_call'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:161:in `call'
    /usr/lib/ruby/gems/1.8/gems/apipie-bindings-0.0.11/lib/apipie_bindings/resource.rb:14:in `call'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/command.rb:43:in `send_request'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli_foreman-0.1.4.14/lib/hammer_cli_foreman/commands.rb:185:in `send_request'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli_foreman-0.1.4.14/lib/hammer_cli_foreman/commands.rb:369:in `send_request'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/command.rb:34:in `execute'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/lib/hammer_cli/./apipie/../abstract.rb:23:in `run'
    /usr/lib/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:125:in `run'
    /usr/lib/ruby/gems/1.8/gems/hammer_cli-0.1.4.11/bin/hammer:108
    /usr/bin/hammer:19:in `load'
    /usr/bin/hammer:19

Stacktrace

  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "/home/jenkins/shiningpanda/jobs/9514c559/virtualenvs/d41d8cd9/lib/python2.7/site-packages/ddt.py", line 146, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel66-cli/tests/foreman/cli/test_computeresource.py", line 360, in test_update_negative
    self.assertEqual(result.return_code, 0)
  File "/usr/lib64/python2.7/unittest/case.py", line 553, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib64/python2.7/unittest/case.py", line 546, in _baseAssertEqual
    raise self.failureException(msg)
'70 != 0\n--------------------

**Comment by tkolhar** [comment]
when executed tests locally using nosetests:
$ nosetests -c robottelo.properties -m test_update_negative_1 /home/tkolhar/git/robottelo/tests/foreman/cli/test_computeresource.py
2015-06-16 16:58:54 - robottelo.common.ssh - DEBUG - >>> [qe-sat6-rhel66.usersys.redhat.com] LANG=en_US.UTF-8 hammer -v -u admin -p changeme --output=csv compute-resource update --name="UDD3oaE3" --new-name="򿱟󶱞񩌬񮃣򛽣󉱼𑏊񚧼𐍀󒇶󿨄󃶳򫅧𴂀먘򯤒쀿󪥌𠽎򌠵򤙮󑞩򳰉񞌙􌥀󀅂󟨕𓉼󲸀𴢏񓁇𖵗򨎼񙼪寏曹񇘱𮔫񱽕𺔖󽻷󲰕󔌌󜭍󆷷𳟺󮽀􄤗񔿖􈱄򠴉𛹒򧆆󐉋𮑷􌓠󧍄񎝌񭠭񛠧􎣉󾪰򊆌􋐍񫃃󀙵ꐓ󰤡󾎕򽚖𚼮𶮑󛲰񆳮򶎟򭅫𷇚󓘝򃨟󅙡񥌢󥔑󞷁𭵍򎙣񅫝򇤰񹽶󟭬𫊧񖂞󩈓񽶃𓡧񄘨𲝈𣳖󶿻󤅣񥂳󉠹󾄾򫮮򹒴󷝞ꋂ򗾉񒓎𞫖󃕂󱺸􌯒𢔆򩄆𒣦󂇪򚍾򾢜𦙸ꃝ񪊗󱏲󃍌񀲟򳨘򹷋󤎉󈩦򾔦􏞊򢍮򃲅񻛷񋡉񌃮񇐷򎥐񥗴󎩌򆍜󮮦򏁤󽗞񒵣󷴒񄹔񂋿𰢓񜅐𧽴򨸘򸶥򷛷񥱠򇣙󰠜񑋁󎧗򙭹𢖄𖣜󙧋򩥍񽖢𻔒񒥠񬴯𷣄𦝧񓂼𓑅􉰃񨖈񼗹񔸻󲈷𸬒󰅤񐒬񄥽󡷇󏤕򯠱򤚓䓄񍑽𑤪񾝗񏦳𣃤񽀵񖖧򋤷򫟗󲪍󦐪𦍝󯷦򪔨𑔱򥀟򅩷󌰤򙼈󀯒𱕁𨔪󪹌򿷂񜢍񁺜񺫤򛻝󠜬򋌛򷼊󼁠򘻛𙢬􉙩쥏𒔨񥔭񡖆󧸼񃁃󂜳ଐ𻷏񢋂􃈽𣬴򪉜񳴋𷝓򛎟񣜢𝻌󌯯󶷗򝈢𝚳𱣗򺢑󕙜𪰖󭑳񑤃񫎸𷒥𮆎󐓥𭉼򢂴򛈂"
2015-06-16 16:58:57 - robottelo.common.ssh - INFO - Instantiated Paramiko client 0x275c550
2015-06-16 16:59:00 - robottelo.common.ssh - INFO - Destroying Paramiko client 0x275c550
2015-06-16 16:59:00 - robottelo.common.ssh - INFO - Destroyed Paramiko client 0x275c550
2015-06-16 16:59:00 - robottelo.common.ssh - DEBUG - <<< stderr
[ERROR 2015-06-16 07:29:00 Exception] Name is too long (maximum is 255 characters)
Could not update the compute resource:
  Name is too long (maximum is 255 characters)

2015-06-16 16:59:00 - robottelo.common.ssh - DEBUG - >>> [qe-sat6-rhel66.usersys.redhat.com] LANG=en_US.UTF-8 hammer -v -u admin -p changeme  compute-resource info --id="59"
2015-06-16 16:59:18 - robottelo.common.ssh - INFO - Instantiated Paramiko client 0x275fb90
2015-06-16 16:59:20 - robottelo.common.ssh - INFO - Destroying Paramiko client 0x275fb90
2015-06-16 16:59:20 - robottelo.common.ssh - INFO - Destroyed Paramiko client 0x275fb90
2015-06-16 16:59:20 - robottelo.common.ssh - DEBUG - <<< stdout
Id:          59
Name:        UDD3oaE3
Provider:    Libvirt
Url:         qemu+tcp://localhost:16509/system
Description: 
User:        
Created at:  2015/06/16 11:28:49
Updated at:  2015/06/16 11:28:49
ok
XML: foreman-results.xml
Ran 1 test in 35.877s

the test seems to work fine when executed locally

**Comment by sthirugn** [comment]
Passed in Snap 12
