### ISSUE TITLE
UI Automation failure : test_associate_product_1

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2451]
TestNames:
tests.foreman.ui.test_activationkey.ActivationKey.test_associate_product_1

Error Message
403 Client Error: Forbidden

Stacktrace

  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel66-ui/tests/foreman/ui/test_activationkey.py", line 1153, in test_associate_product_1
    repo_id = self.enable_sync_redhat_repo(rh_repo, org_id=org_id)
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel66-ui/tests/foreman/ui/test_activationkey.py", line 85, in enable_sync_redhat_repo
    rh_repo['releasever'])
  File "robottelo/api/utils.py", line 122, in enable_rhrepo_and_fetchid
    reposet_id=reposet_id,
  File "/home/jenkins/shiningpanda/jobs/abb3bf3f/virtualenvs/d41d8cd9/lib/python2.7/site-packages/nailgun/entities.py", line 2652, in enable_rhrepo
    return _handle_response(response, self._server_config, synchronous)
  File "/home/jenkins/shiningpanda/jobs/abb3bf3f/virtualenvs/d41d8cd9/lib/python2.7/site-packages/nailgun/entities.py", line 102, in _handle_response
    response.raise_for_status()
  File "/home/jenkins/shiningpanda/jobs/abb3bf3f/virtualenvs/d41d8cd9/lib/python2.7/site-packages/requests/models.py", line 851, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
'403 Client Error: Forbidden\n--------------------

**Comment by tkolhar** [comment]
when executed locally using nosetests:
$ nosetests -c robottelo.properties -m test_associate_product_1 /home/tkolhar/git/robottelo/tests/foreman/ui/test_activationkey.py 
2015-06-16 17:16:54 - nailgun.client - WARNING - Received HTTP 403 response: {"displayMessage":"CDN loading error: access forbidden to https://cdn.redhat.com:443/content/dist/rhel/server/6/6Server/x86_64/rhev-agent/3/os/repodata/repomd.xml","errors":["CDN loading error: access forbidden to https://cdn.redhat.com:443/content/dist/rhel/server/6/6Server/x86_64/rhev-agent/3/os/repodata/repomd.xml"]}
ERROR
ERROR

======================================================================
ERROR: @Test: Test that RH product can be associated to Activation Keys
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tkolhar/git/robottelo/tests/foreman/ui/test_activationkey.py", line 1153, in test_associate_product_1
    repo_id = self.enable_sync_redhat_repo(rh_repo, org_id=org_id)
  File "/home/tkolhar/git/robottelo/tests/foreman/ui/test_activationkey.py", line 85, in enable_sync_redhat_repo
    rh_repo['releasever'])
  File "/home/tkolhar/git/robottelo/robottelo/api/utils.py", line 122, in enable_rhrepo_and_fetchid
    reposet_id=reposet_id,
  File "/usr/lib/python2.7/site-packages/nailgun/entities.py", line 2486, in enable_rhrepo
    return _handle_response(response, self._server_config, synchronous)
  File "/usr/lib/python2.7/site-packages/nailgun/entities.py", line 102, in _handle_response
    response.raise_for_status()
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 851, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 403 Client Error: Forbidden

======================================================================
ERROR: @Test: Test that RH product can be associated to Activation Keys
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tkolhar/git/robottelo/robottelo/test.py", line 260, in tearDown
    self.take_screenshot(self._testMethodName)
  File "/home/tkolhar/git/robottelo/robottelo/test.py", line 248, in take_screenshot
    directory,
  File "/usr/lib64/python2.7/posixpath.py", line 77, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'
XML: foreman-results.xml
Ran 1 test in 194.905s

FAILED (errors=2)

**Comment by sthirugn** [comment]
Failed in Snap 12

**Comment by elyezer** [comment]
Closing this in favor of #2662
