### ISSUE TITLE
UI Automation failure : test_cv_associate_composite_dupe_repos_negative

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2452]
TestNames:
tests.foreman.ui.test_contentviews.TestContentViewsUI.test_cv_associate_composite_dupe_repos_negative

Error Message
'_AssertRaisesContext' object has no attribute 'exception'

-------------------- >> begin captured logging << --------------------
robottelo.ui.locators: DEBUG: Accessing locator "login.username" by id: "login_login"
robottelo.ui.locators: DEBUG: Accessing locator "login.username" by id: "login_login"
robottelo.ui.locators: DEBUG: Accessing locator "login.password" by id: "login_password"
robottelo.ui.locators: DEBUG: Accessing locator "submit" by name: "commit"
robottelo.ui.locators: DEBUG: Accessing locator "notif.error" by xpath: "//div[contains(@class, 'jnotify-notification-error')]"
robottelo.ui.base: DEBUG: NoSuchElementException: Could not locate element //div[contains(@class, 'jnotify-notification-error')].

**Comment by tkolhar** [comment]
when executed locally using nosetests:
$ nosetests -c robottelo.properties -m test_cv_associate_composite_dupe_repos_negative /home/tkolhar/git/robottelo/tests/foreman/ui/test_contentviews.py
2015-06-16 17:23:48 - robottelo.ui.locators - DEBUG - Accessing locator "kt_search" by xpath: "//input[@ng-model='table.searchTerm']"
2015-06-16 17:23:48 - robottelo.ui.locators - DEBUG - Accessing locator "kt_search_button" by xpath: "//button[@ng-click='table.search(table.searchTerm)']"
2015-06-16 17:23:50 - robottelo.ui.locators - DEBUG - Accessing locator "contentviews.key_name" by xpath: "//tr[contains(@ng-repeat, 'contentView')]/td/a[contains(., '%s')]"
2015-06-16 17:23:50 - robottelo.ui.locators - DEBUG - Accessing locator "contentviews.key_name" by xpath: "//tr[contains(@ng-repeat, 'contentView')]/td/a[contains(., '%s')]"
2015-06-16 17:23:50 - robottelo.ui.locators - DEBUG - Accessing locator "kt_search" by xpath: "//input[@ng-model='table.searchTerm']"
2015-06-16 17:23:51 - robottelo.ui.locators - DEBUG - Accessing locator "kt_search_button" by xpath: "//button[@ng-click='table.search(table.searchTerm)']"
2015-06-16 17:23:57 - robottelo.ui.locators - DEBUG - Accessing locator "contentviews.tab_content" by xpath: "//ul/li/a[@class='dropdown-toggle']/i"
2015-06-16 17:23:58 - robottelo.ui.locators - DEBUG - Accessing locator "contentviews.content_repo" by xpath: "//a[@class='ng-scope' and contains(@href, 'repositories')]"
2015-06-16 17:24:00 - robottelo.ui.locators - DEBUG - Accessing locator "contentviews.select_repo" by xpath: "//div[@bst-table='repositoriesTable']//td[contains(normalize-space(.), '%s')]/preceding-sibling::td[@class='row-select']/input[@type='checkbox']"
2015-06-16 17:24:00 - robottelo.ui.locators - DEBUG - Accessing locator "contentviews.tab_repo_add" by xpath: "//a[contains(@ui-sref, 'repositories.yum.available')]"
2015-06-16 17:24:01 - robottelo.ui.locators - DEBUG - Accessing locator "contentviews.repo_search" by xpath: "//input[@ng-model='repositorySearch']"
2015-06-16 17:24:02 - robottelo.ui.locators - DEBUG - Accessing locator "contentviews.add_repo" by xpath: "//button[contains(@ng-show, 'repositories.yum.available')]"
2015-06-16 17:24:05 - robottelo.ui.locators - DEBUG - Accessing locator "contentviews.tab_repo_remove" by xpath: "//a[contains(@ui-sref, 'repositories.yum.list')]/span[@class='ng-scope' and contains(., 'List/Remove')]"
2015-06-16 17:24:11 - robottelo.ui.locators - DEBUG - Accessing locator "alert.success" by xpath: "//div[contains(@class, 'alert-success')]"
2015-06-16 17:24:11 - robottelo.ui.locators - DEBUG - Accessing locator "contentviews.key_name" by xpath: "//tr[contains(@ng-repeat, 'contentView')]/td/a[contains(., '%s')]"
2015-06-16 17:24:11 - robottelo.ui.locators - DEBUG - Accessing locator "contentviews.key_name" by xpath: "//tr[contains(@ng-repeat, 'contentView')]/td/a[contains(., '%s')]"
2015-06-16 17:24:11 - robottelo.ui.locators - DEBUG - Accessing locator "kt_search" by xpath: "//input[@ng-model='table.searchTerm']"
2015-06-16 17:24:11 - robottelo.ui.locators - DEBUG - Accessing locator "kt_search_button" by xpath: "//button[@ng-click='table.search(table.searchTerm)']"
2015-06-16 17:24:16 - robottelo.ui.locators - DEBUG - Accessing locator "contentviews.tab_content" by xpath: "//ul/li/a[@class='dropdown-toggle']/i"
2015-06-16 17:24:17 - robottelo.ui.locators - DEBUG - Accessing locator "contentviews.content_repo" by xpath: "//a[@class='ng-scope' and contains(@href, 'repositories')]"
2015-06-16 17:24:18 - robottelo.ui.locators - DEBUG - Accessing locator "contentviews.select_repo" by xpath: "//div[@bst-table='repositoriesTable']//td[contains(normalize-space(.), '%s')]/preceding-sibling::td[@class='row-select']/input[@type='checkbox']"
2015-06-16 17:24:18 - robottelo.ui.locators - DEBUG - Accessing locator "contentviews.tab_repo_add" by xpath: "//a[contains(@ui-sref, 'repositories.yum.available')]"
2015-06-16 17:24:18 - robottelo.ui.locators - DEBUG - Accessing locator "contentviews.repo_search" by xpath: "//input[@ng-model='repositorySearch']"
2015-06-16 17:24:21 - robottelo.ui.locators - DEBUG - Accessing locator "contentviews.add_repo" by xpath: "//button[contains(@ng-show, 'repositories.yum.available')]"
2015-06-16 17:24:23 - robottelo.ui.locators - DEBUG - Accessing locator "contentviews.tab_repo_remove" by xpath: "//a[contains(@ui-sref, 'repositories.yum.list')]/span[@class='ng-scope' and contains(., 'List/Remove')]"
ERROR
ERROR


ERROR: @test: attempt to associate the same repo multiple times within a
Traceback (most recent call last):
  File "/home/tkolhar/git/robottelo/tests/foreman/ui/test_contentviews.py", line 684, in test_cv_associate_composite_dupe_repos_negative
    context.exception.message,
AttributeError: '_AssertRaisesContext' object has no attribute 'exception'

ERROR: @test: attempt to associate the same repo multiple times within a
Traceback (most recent call last):
  File "/home/tkolhar/git/robottelo/robottelo/test.py", line 260, in tearDown
    self.take_screenshot(self._testMethodName)
  File "/home/tkolhar/git/robottelo/robottelo/test.py", line 248, in take_screenshot
    directory,
  File "/usr/lib64/python2.7/posixpath.py", line 77, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'

XML: foreman-results.xml
Ran 1 test in 180.330s

FAILED (errors=2)

**Comment by tkolhar** [comment]
this test occured again dated 06/17/2015

TestNames:
tests.foreman.ui.test_contentviews.TestContentViewsUI.test_cv_associate_composite_dupe_repos_negative 

Error Message
'_AssertRaisesContext' object has no attribute 'exception'

Stacktrace

  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel71-ui/tests/foreman/ui/test_contentviews.py", line 684, in test_cv_associate_composite_dupe_repos_negative
    context.exception.message,
'\'_AssertRaisesContext\' object has no attribute \'exception\'\n--------------------

will add nosetests results when system is up and running

**Comment by tkolhar** [comment]
this issue occurred again dated 06/23/2015
TestNames:
tests.foreman.ui.test_contentviews.TestContentViewsUI.test_cv_associate_composite_dupe_repos_negative

Error Message
'_AssertRaisesContext' object has no attribute 'exception'

Stacktrace

  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel66-ui/tests/foreman/ui/test_contentviews.py", line 684, in test_cv_associate_composite_dupe_repos_negative
    context.exception.message,
'\'_AssertRaisesContext\' object has no attribute \'exception\'\n--------------------

**Comment by sthirugn** [comment]
Failed in Snap 12
