### ISSUE TITLE
UI Automation failure : test_delete_version_default

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2453]
TestNames:
tests.foreman.ui.test_contentviews.TestContentViewsUI.test_delete_version_default

Error Message
Selected version "Version 1.0" was not deleted successfully

Stacktrace

  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel66-ui/tests/foreman/ui/test_contentviews.py", line 1237, in test_delete_version_default
    self.content_views.validate_version_deleted(cv.name, version)
  File "robottelo/ui/contentviews.py", line 769, in validate_version_deleted
    .format(version)
'Selected version "Version 1.0" was not deleted successfully\n--------------------

**Comment by tkolhar** [comment]
when executed locally using nosetests:
$ nosetests -c robottelo.properties -m test_delete_version_default /home/tkolhar/git/robottelo/tests/foreman/ui/test_contentviews.py
2015-06-16 17:29:16 - robottelo.ui.locators - DEBUG - Accessing locator "login.username" by id: "login_login"
2015-06-16 17:29:16 - robottelo.ui.locators - DEBUG - Accessing locator "login.username" by id: "login_login"
2015-06-16 17:29:16 - robottelo.ui.locators - DEBUG - Accessing locator "login.password" by id: "login_password"
2015-06-16 17:29:17 - robottelo.ui.locators - DEBUG - Accessing locator "submit" by name: "commit"
2015-06-16 17:29:19 - robottelo.ui.locators - DEBUG - Accessing locator "notif.error" by xpath: "//div[contains(@class, 'jnotify-notification-error')]"
2015-06-16 17:29:25 - robottelo.ui.base - DEBUG - NoSuchElementException: Could not locate element //div[contains(@class, 'jnotify-notification-error')].
2015-06-16 17:29:25 - robottelo.ui.locators - DEBUG - Accessing locator "menu.any_context" by xpath: "//div[contains(@style,'static') or contains(@style,'fixed')]//li[contains(@class,'org-switcher')]/a"
2015-06-16 17:29:25 - robottelo.ui.locators - DEBUG - Accessing locator "org.nav_current_org" by xpath: "(//div[contains(@style,'static') or contains(@style,'fixed')]//li[contains(@class,'org-switcher')]//li/a[@data-toggle='dropdown'])[1]"
2015-06-16 17:29:25 - robottelo.ui.locators - DEBUG - Accessing locator "org.select_org" by xpath: "//div[contains(@style,'static') or contains(@style,'fixed')]//a[@href='/organizations/clear']/../../li/a[contains(.,'%s')]"
2015-06-16 17:29:31 - robottelo.ui.locators - DEBUG - Accessing locator "menu.current_text" by xpath: "//div[contains(@style,'static') or contains(@style,'fixed')]//li[contains(@class,'org-switcher')]/a"
2015-06-16 17:29:32 - robottelo.ui.locators - DEBUG - Accessing locator "menu.fetch_org" by xpath: "//div[contains(@style,'static') or contains(@style, 'fixed')]//li[contains(@class, 'org-menu')]/a"
2015-06-16 17:29:32 - robottelo.ui.locators - DEBUG - Accessing locator "menu.content" by xpath: "//div[contains(@style,'static') or contains(@style, 'fixed')]//a[@id='content_menu']"
2015-06-16 17:29:32 - robottelo.ui.locators - DEBUG - Accessing locator "menu.content_views" by xpath: "//div[contains(@style,'static') or contains(@style, 'fixed')]//a[@id='menu_item_content_views']"
2015-06-16 17:29:51 - robottelo.ui.locators - DEBUG - Accessing locator "contentviews.key_name" by xpath: "//tr[contains(@ng-repeat, 'contentView')]/td/a[contains(., '%s')]"
2015-06-16 17:29:51 - robottelo.ui.locators - DEBUG - Accessing locator "contentviews.key_name" by xpath: "//tr[contains(@ng-repeat, 'contentView')]/td/a[contains(., '%s')]"
2015-06-16 17:29:51 - robottelo.ui.locators - DEBUG - Accessing locator "kt_search" by xpath: "//input[@ng-model='table.searchTerm']"
2015-06-16 17:29:52 - robottelo.ui.locators - DEBUG - Accessing locator "kt_search_button" by xpath: "//button[@ng-click='table.search(table.searchTerm)']"
2015-06-16 17:30:09 - robottelo.ui.base - DEBUG - TimeoutException: Timed out waiting for element '//tr[contains(@ng-repeat, 'contentView')]/td/a[contains(., '↣󁒄񈽆󙩆񹃶򯉬򫎫􇥔𷻶ӌ魡𾳝򙟐񺟗򒛼򧐢􊜦򛢫󴴃򅕮󪻲򸫲򪤉')]' to display.
ERROR
ERROR

ERROR: @Test: Delete a content-view version associated to 'Library'
Traceback (most recent call last):
  File "/home/tkolhar/git/robottelo/tests/foreman/ui/test_contentviews.py", line 1236, in test_delete_version_default
    self.content_views.delete_version(cv.name, version)
  File "/home/tkolhar/git/robottelo/robottelo/ui/contentviews.py", line 128, in delete_version
    u'Could not find the "{0}" content view.'.format(name)
UIError: Could not find the "\u21a3\U000c1484\U00048f46\U000d9a46\U000790f6\U000af26c\U000ab3ab\U00107954\U00037ef6\u04cc\u9b61\U0003ecdd\U000997d0\U0007a7d7\U000926fc\U000a7422\U0010a726\U0009b8ab\U000f4d03\U0008556e\U000eaef2\U000b8af2\U000aa909" content view.

ERROR: @Test: Delete a content-view version associated to 'Library'

Traceback (most recent call last):
  File "/home/tkolhar/git/robottelo/robottelo/test.py", line 260, in tearDown
    self.take_screenshot(self._testMethodName)
  File "/home/tkolhar/git/robottelo/robottelo/test.py", line 248, in take_screenshot
    directory,
  File "/usr/lib64/python2.7/posixpath.py", line 77, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'
XML: foreman-results.xml
Ran 1 test in 197.534s

FAILED (errors=2)

**Comment by tkolhar** [comment]
this issue occurred again dated 06/23/2015
TestNames:
tests.foreman.ui.test_contentviews.TestContentViewsUI.test_delete_version_default 

Error Message
Selected version "Version 1.0" was not deleted successfully

Stacktrace

  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel66-ui/tests/foreman/ui/test_contentviews.py", line 1237, in test_delete_version_default
    self.content_views.validate_version_deleted(cv.name, version)
  File "robottelo/ui/contentviews.py", line 769, in validate_version_deleted
    .format(version)
'Selected version "Version 1.0" was not deleted successfully\n--------------------

**Comment by elyezer** [comment]
Need to double check, but I remember seeing the version using a different name like `Version 1` instead of `Version 1.0`

**Comment by sthirugn** [comment]
Passed in Snap 12
