### ISSUE TITLE
Automation failure : test_repositoryset_disable

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2557]
```
TestNames:
tests.foreman.api.test_product.RepositorySetsTestCase.test_repositoryset_disable 

Error Message
500 Server Error: Internal Server Error

Stacktrace

  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel71-api/tests/foreman/api/test_product.py", line 191, in test_repositoryset_disable
    reposet_id=reposet_id,
  File "/home/jenkins/shiningpanda/jobs/f593b203/virtualenvs/d41d8cd9/lib/python2.7/site-packages/nailgun/entities.py", line 2685, in repository_sets_available_repositories
    return _handle_response(response, self._server_config)['results']
  File "/home/jenkins/shiningpanda/jobs/f593b203/virtualenvs/d41d8cd9/lib/python2.7/site-packages/nailgun/entities.py", line 103, in _handle_response
    response.raise_for_status()
  File "/home/jenkins/shiningpanda/jobs/f593b203/virtualenvs/d41d8cd9/lib/python2.7/site-packages/requests/models.py", line 851, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
'500 Server Error: Internal Server Error\n-------------------- 
```

**Comment by tkolhar** [comment]
tested this locally using nosetests:
$ nosetests -c robottelo.properties -m test_repositoryset_disable /home/tkolhar/git/robottelo/tests/foreman/api/test_product.py
2015-07-28 15:10:39 - nailgun.client - DEBUG - Received HTTP 200 response: {"id":"73ab6594-a5b2-4c70-832a-ce25240da279","label":"Actions::Katello::RepositorySet::DisableRepository","pending":false,"username":"admin","started_at":"2015-07-28T09:40:35Z","ended_at":"2015-07-28T09:40:37Z","state":"stopped","result":"success","progress":1.0,"input":{"repository":{"id":810,"name":"Red Hat Enterprise Virtualization Agents for RHEL 6 Server RPMs x86_64 6Server","label":"Red_Hat_Enterprise_Virtualization_Agents_for_RHEL_6_Server_RPMs_x86_64_6Server"},"product":{"id":9842,"name":"Red Hat Enterprise Linux Server","label":"Red_Hat_Enterprise_Linux_Server","cp_id":"69"},"provider":{"id":1882,"name":"Red Hat"},"organization":{"id":1200,"name":"򀿣𡗚𻎂񷣖񱁋򧗤𭶺䤰򮻅󻟇񳭸񾌬󮷁𭷼","label":"e0a9ca60-ef00-4a93-93d2-e80220a9a5ce"},"services_checked":["elasticsearch","pulp","pulp_auth","candlepin","candlepin_auth"],"locale":"en"},"output":{},"humanized":{"action":"Disable","input":[["repository",{"text":"repository 'Red Hat Enterprise Virtualization Agents for RHEL 6 Server RPMs x86_64 6Server'","link":null}],["product",{"text":"product 'Red Hat Enterprise Linux Server'","link":"#/products/9842/info"}],["organization",{"text":"organization '򀿣𡗚𻎂񷣖񱁋򧗤𭶺䤰򮻅󻟇񳭸񾌬󮷁𭷼'","link":"/organizations/1200/edit"}]],"output":"","errors":[]},"cli_example":null}
ERROR
ERROR: @Test: Disable repo from reposet
Traceback (most recent call last):
  File "/home/tkolhar/git/robottelo/tests/foreman/api/test_product.py", line 190, in test_repositoryset_disable
    repositories = product.repository_sets_available_repositories(
AttributeError: 'Product' object has no attribute 'repository_sets_available_repositories'

XML: foreman-results.xml
Ran 1 test in 76.354s
FAILED (errors=1)

**Comment by elyezer** [comment]
The test passed on latest automation run, closing this.
