### ISSUE TITLE
tests.foreman.ui.test_contentviews.TestContentViewsUI.test_delete_version_non_default

### ISSUE THREAD

**Issue by kbidarkar** [SatelliteQE/robottelo#2586]
Deletion of content-view version fails.

More details in: https://jenkins.redhat.com/view/Compose/job/satellite6-automation-downstream-rhel71-ui/62/testReport/tests.foreman.ui.test_contentviews/TestContentViewsUI/test_delete_version_non_default/

Quick Reference:
```
Selected version "Version 1.0" was not deleted successfully
-------------------- >> begin captured logging << --------------------
nailgun.client: DEBUG: Making HTTP POST request to https://ex1.redhat.com/katello/api/v2/organizations with options {'verify': False, 'auth': ('admin', 'changeme'), 'headers': {'content-type': 'application/json'}} and data {"name": "\u9368\ud16b"}.
nailgun.client: DEBUG: Received HTTP 201 response: {"ancestry":null,"apply_info_task_id":null,"created_at":"2015-07-16T21:50:01Z","description":null,"id":466,"ignore_types":[],"katello_default":true,"label":"55799af8-62c1-4870-a257-d5457231ef86","name":"鍨텫","title":"鍨텫","updated_at":"2015-07-16T21:50:01Z","service_levels":[],"service_level":null}
nailgun.client: DEBUG: Making HTTP GET request to https://ex1.redhat.com/katello/api/v2/organizations/466 with options {'verify': False, 'auth': ('admin', 'changeme'), 'headers': {'content-type': 'application/json'}} and no data.
nailgun.client: DEBUG: Received HTTP 200 response: {"id":466,"name":"鍨텫","title":"鍨텫","created_at":"2015-07-16T21:50:01Z","updated_at":"2015-07-16T21:50:01Z","select_all_types":[],"description":null,"parameters":[],"users":[],"smart_proxies":[{"name":"ex1.redhat.com","id":1,"url":"https://ex1.redhat.com:9090"}],"subnets":[],"compute_resources":[],"media":[],"config_templates":[{"id":44,"name":"Boot disk iPXE - generic host","template_kind_id":1,"template_kind_name":"Bootdisk"},{"id":43,"name":"Boot disk iPXE - host","template_kind_id":1,"template_kind_name":"Bootdisk"},{"id":48,"name":"idm_register","template_kind_id":null,"template_kind_name":null},{"id":22,"name":"Kickstart default iPXE","template_kind_id":4,"template_kind_name":"iPXE"},{"id":21,"name":"Kickstart default PXELinux","template_kind_id":2,"template_kind_name":"PXELinux"},{"id":39,"name":"kickstart_networking_setup","template_kind_id":null,"template_kind_name":null},{"id":40,"name":"puppet.conf","template_kind_id":null,"template_kind_name":null},{"id":2,"name":"PXELinux default local boot","template_kind_id":2,"template_kind_name":"PXELinux"},{"id":1,"name":"PXELinux global default","template_kind_id":2,"template_kind_name":"PXELinux"},{"id":45,"name":"Satellite Kickstart Default","template_kind_id":5,"template_kind_name":"provision"},{"id":47,"name":"Satellite Kickstart Default Finish","template_kind_id":6,"template_kind_name":"finish"},{"id":46,"name":"Satellite Kickstart Default User Data","template_kind_id":8,"template_kind_name":"user_data"},{"id":49,"name":"subscription_manager_registration","template_kind_id":null,"template_kind_name":null}],"domains":[],"environments":[],"hostgroups":[],"locations":[],"label":"55799af8-62c1-4870-a257-d5457231ef86","owner_details":{"parentOwner":null,"id":"ff8080814e97d4b4014e98d880b37ef9","key":"55799af8-62c1-4870-a257-d5457231ef86","displayName":"鍨텫","contentPrefix":"/55799af8-62c1-4870-a257-d5457231ef86/$env","defaultServiceLevel":null,"upstreamConsumer":null,"logLevel":null,"href":"/owners/55799af8-62c1-4870-a257-d5457231ef86","created":"2015-07-16T21:50:02.419+0000","updated":"2015-07-16T21:50:02.419+0000"},"redhat_repository_url":"https://cdn.redhat.com","redhat_docker_registry_url":"https://registry.access.redhat.com","service_levels":[],"service_level":null,"default_content_view_id":669,"library_id":458}
nailgun.client: DEBUG: Making HTTP POST request to https://ex1.redhat.com/katello/api/v2/products with options {'verify': False, 'auth': ('admin', 'changeme'), 'headers': {'content-type': 'application/json'}} and data {"organization_id": 466, "name": "\ud844\udf44\ud868\udd5e\ud856\udc92\ucca9\ub8f5\u3884\uce4f\u554f\ub6ed\u5d53\ub4ac\ud851\udd2f\ud808\udde0\u38e8\ud864\udc86\u876f\ud861\udf6b\ud859\ude8a\ud848\udc78\ud808\udf01\ud842\udf0a\ud144\u343c\ud800\udec2\u4eb9\ud843\udcaa\ud85b\ude3b\u7a4d\ud85b\udf74"}.
nailgun.client: DEBUG: Received HTTP 200 response: {"sync_state":null,"last_sync":null,"last_sync_words":null,"organization":{"name":"鍨텫","label":"55799af8-62c1-4870-a257-d5457231ef86","id":466},"id":4857,"cp_id":null,"name":"10𡍄10𡍄𪅞10𡍄𪅞𥢒첩룵㢄칏問뛭嵓뒬10𡍄𪅞𥢒𤔯10𡍄𪅞𥢒𤔯𒇠㣨10𡍄𪅞𥢒𤔯𒇠𩂆蝯10𡍄𪅞𥢒𤔯𒇠𩂆𨝫10𡍄𪅞𥢒𤔯𒇠𩂆𨝫𦚊10𡍄𪅞𥢒𤔯𒇠𩂆𨝫𦚊𢁸10𡍄𪅞𥢒𤔯𒇠𩂆𨝫𦚊𢁸𒌁10𡍄𪅞𥢒𤔯𒇠𩂆𨝫𦚊𢁸𒌁𠬊텄㐼10𡍄𪅞𥢒𤔯𒇠𩂆𨝫𦚊𢁸𒌁𠬊𐋂亹10𡍄𪅞𥢒𤔯𒇠𩂆𨝫𦚊𢁸𒌁𠬊𐋂𠲪10𡍄𪅞𥢒𤔯𒇠𩂆𨝫𦚊𢁸𒌁𠬊𐋂𠲪𦸻積10𡍄𪅞𥢒𤔯𒇠𩂆𨝫𦚊𢁸𒌁𠬊𐋂𠲪𦸻𦽴","label":"ae5edca2-fb98-4d7f-8512-47e65c2f6fa3","description":null,"provider_id":725,"sync_plan_id":null,"sync_status":{"state":null},"sync_summary":{},"gpg_key_id":null,"redhat":false,"repository_count":0,"":null,"created_at":"2015-07-16T21:50:03Z","updated_at":"2015-07-16T21:50:03Z","product_content":[],"available_content":[],"permissions":{"view_products":true,"edit_products":true,"destroy_products":true,"sync_products":true},"published_content_view_ids":[],"readonly":false,"repositories":[],"provider":{"name":"Anonymous"}}

nailgun.client: DEBUG: Making HTTP POST request to https://ex1.redhat.com/katello/api/v2/repositories with options {'verify': False, 'auth': ('admin', 'changeme'), 'headers': {'content-type': 'application/json'}} and data {"product_id": 4857, "content_type": "yum", "url": "http://inecas.fedorapeople.org/fakerepos/zoo3/", "name": "\ud5db\ud856\udecb\u6e44\u9ae7\ud846\udd84\u511b\ud84c\udcef\ubce4\ud841\udf45\ud85b\udd09\u6b72\u1656\ud835\udfbe\ud844\udd95\uc729\ud849\udde0\u94cc\ud835\udd59\ud80c\udeb2\uce28\ud84e\udf52\ud841\udc98\ud80c\udee1\ud866\udc6a"}.
```
```
robottelo.ui.locators: DEBUG: Accessing locator "contentviews.next_button" by xpath: "//button[@ng-click='processSelection()']"
robottelo.ui.locators: DEBUG: Accessing locator "contentviews.confirm_remove_ver" by xpath: "//button[@ng-click='performDeletion()']"
robottelo.ui.locators: DEBUG: Accessing locator "contentviews.key_name" by xpath: "//tr[contains(@ng-repeat, 'contentView')]/td/a[contains(., '%s')]"
robottelo.ui.locators: DEBUG: Accessing locator "contentviews.key_name" by xpath: "//tr[contains(@ng-repeat, 'contentView')]/td/a[contains(., '%s')]"
robottelo.ui.locators: DEBUG: Accessing locator "kt_search" by xpath: "//input[@ng-model='table.searchTerm']"
robottelo.ui.locators: DEBUG: Accessing locator "kt_search_button" by xpath: "//button[@ng-click='table.search(table.searchTerm)']"
robottelo.ui.locators: DEBUG: Accessing locator "contentviews.version_name" by xpath: "//td/a[contains(., '%s')]"
--------------------- >> end captured logging << ---------------------

Stacktrace

  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel71-ui/tests/foreman/ui/test_contentviews.py", line 1269, in test_delete_version_non_default
    self.content_views.validate_version_deleted(cv.name, version)
  File "robottelo/ui/contentviews.py", line 769, in validate_version_deleted
    .format(version)
'Selected version "Version 1.0" was not deleted successfully\n-------------------- >> begin captured logging << --------------------\nnailgun.client: DEBUG: Making HTTP POST request to https://qe-sat6-rhel71.usersys.redhat.com/katello/api/v2/organizations with options {\'verify\': False, \'auth\': (\'admin\', \'changeme\'), \'headers\': {\'content-type\': \'application/json\'}} and data {"name": "\\u9368\\ud16b"}.\nnailgun.client: DEBUG: Received HTTP 201 response: 
```

**Comment by sghai** [comment]
Another test failing due to same error:

``tests.foreman.ui.test_contentviews.TestContentViewsUI.test_delete_version_default``

**Comment by sghai** [comment]
I tested this locally and looks like we are not checking the progress bar to finish while deleting the version. So I think automation validates whether version is deleted or not while deletion is in-progress.

**Comment by tkolhar** [comment]
tested locally using nosetests:
$ nosetests -c robottelo.properties -m test_delete_version_non_default /home/tkolhar/git/robottelo/tests/foreman/ui/test_contentviews.py
ERROR: @Test: Delete a content-view version associated to non-default
Traceback (most recent call last):
  File "/home/tkolhar/git/robottelo/robottelo/test.py", line 288, in tearDown
    self.take_screenshot(self._testMethodName)
  File "/home/tkolhar/git/robottelo/robottelo/test.py", line 276, in take_screenshot
    directory,
  File "/usr/lib64/python2.7/posixpath.py", line 77, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'


XML: foreman-results.xml
Ran 1 test in 164.104s
FAILED (errors=2)
