### ISSUE TITLE
Automation failure : tests.foreman.ui.test_contentviews.TestContentViewsUI

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2648]
TestNames:
tests.foreman.ui.test_contentviews.TestContentViewsUI.test_cv_promote_rh_1
tests.foreman.ui.test_contentviews.TestContentViewsUI.test_cv_publish_rh_1
tests.foreman.ui.test_contentviews.TestContentViewsUI.test_cv_composite_create 
tests.foreman.ui.test_contentviews.TestContentViewsUI.test_associate_view_rh_1 

Error Message
422 Client Error: Unprocessable Entity

Stacktrace

  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel66-ui/tests/foreman/ui/test_contentviews.py", line 733, in test_cv_promote_rh_1
    self.setup_to_create_cv(rh_repo=rh_repo, org_id=org_id)
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel66-ui/tests/foreman/ui/test_contentviews.py", line 85, in setup_to_create_cv
    rh_repo['releasever'])
  File "robottelo/api/utils.py", line 24, in enable_rhrepo_and_fetchid
    reposet_id=reposet_id,
  File "/home/jenkins/shiningpanda/jobs/abb3bf3f/virtualenvs/d41d8cd9/lib/python2.7/site-packages/nailgun/entities.py", line 2726, in enable_rhrepo
    return _handle_response(response, self._server_config, synchronous)
  File "/home/jenkins/shiningpanda/jobs/abb3bf3f/virtualenvs/d41d8cd9/lib/python2.7/site-packages/nailgun/entities.py", line 110, in _handle_response
    response.raise_for_status()
  File "/home/jenkins/shiningpanda/jobs/abb3bf3f/virtualenvs/d41d8cd9/lib/python2.7/site-packages/requests/models.py", line 851, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
'422 Client Error: Unprocessable Entity\n--------------------

**Comment by abalakh** [comment]
#2633 should fix this

**Comment by tkolhar** [comment]
this issue occurred again dated 08/05/2015
TestNames:
tests.foreman.ui.test_contentviews.TestContentViewsUI.test_cv_promote_rh_1
tests.foreman.ui.test_contentviews.TestContentViewsUI.test_cv_publish_rh_1
tests.foreman.ui.test_contentviews.TestContentViewsUI.test_cv_composite_create
tests.foreman.ui.test_contentviews.TestContentViewsUI.test_associate_view_rh_1 

Error Message

422 Client Error: Unprocessable Entity

Stacktrace

  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel67-ui/tests/foreman/ui/test_contentviews.py", line 555, in test_associate_view_rh_1
    self.setup_to_create_cv(rh_repo=rh_repo, org_id=org_id)
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel67-ui/tests/foreman/ui/test_contentviews.py", line 85, in setup_to_create_cv
    rh_repo['releasever'])
  File "robottelo/api/utils.py", line 24, in enable_rhrepo_and_fetchid
    reposet_id=reposet_id,
  File "/home/jenkins/shiningpanda/jobs/1b673361/virtualenvs/d41d8cd9/lib/python2.7/site-packages/nailgun/entities.py", line 2802, in enable_rhrepo
    return _handle_response(response, self._server_config, synchronous)
  File "/home/jenkins/shiningpanda/jobs/1b673361/virtualenvs/d41d8cd9/lib/python2.7/site-packages/nailgun/entities.py", line 110, in _handle_response
    response.raise_for_status()
  File "/home/jenkins/shiningpanda/jobs/1b673361/virtualenvs/d41d8cd9/lib/python2.7/site-packages/requests/models.py", line 851, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
'422 Client Error: Unprocessable Entity\n--------------------

**Comment by tkolhar** [comment]
this issue failed again dated 08/07/2015
TestNames:
tests.foreman.ui.test_contentviews.TestContentViewsUI.test_associate_view_rh_1
tests.foreman.ui.test_contentviews.TestContentViewsUI.test_cv_publish_rh_1 
tests.foreman.ui.test_contentviews.TestContentViewsUI.test_cv_promote_rh_1
tests.foreman.ui.test_contentviews.TestContentViewsUI.test_cv_composite_create

Error Message
list index out of range

Stacktrace

  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel67-ui/tests/foreman/ui/test_contentviews.py", line 553, in test_associate_view_rh_1
    self.setup_to_create_cv(rh_repo=rh_repo, org_id=org_id)
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel67-ui/tests/foreman/ui/test_contentviews.py", line 83, in setup_to_create_cv
    releasever=rh_repo['releasever'],
  File "robottelo/api/utils.py", line 28, in enable_rhrepo_and_fetchid
    query={'organization_id': org_id})[0].id
'list index out of range\n--------------------

**Comment by tkolhar** [comment]
this test is failing when executed locally using nosetests:
$ nosetests -c robottelo.properties -m test_cv_promote_rh_1 /home/tkolhar/git/robottelo/tests/foreman/ui/test_contentviews.py
2015-08-11 13:59:29 - nailgun.client - DEBUG - Received HTTP 201 response: {"ancestry":null,"apply_info_task_id":null,"created_at":"2015-08-11T08:29:26Z","description":null,"id":568,"ignore_types":[],"katello_default":true,"label":"cb06559a-577b-45be-81e6-659feb5d22a4","name":"򱵪򃲀󡄗񴶻𜥝󜮶񲉳񓛹򄫞뚊󣒒𻑢髭󇺽𡞊󾔈񸬰𕲄","title":"򱵪򃲀󡄗񴶻𜥝󜮶񲉳񓛹򄫞뚊󣒒𻑢髭󇺽𡞊󾔈񸬰𕲄","updated_at":"2015-08-11T08:29:26Z","service_levels":[],"service_level":null}
@test: attempt to promote a content view containing RH content ... 2015-08-11 13:59:47 - robottelo.ui.locators - DEBUG - Accessing locator "content_env.select_name" by xpath: "//a[contains(@ui-sref, 'environment.details') and contains(.,'%s')]"
2015-08-11 13:59:47 - nailgun.client - DEBUG - Making HTTP POST request to https://qe-sat6-rhel71.usersys.redhat.com/katello/api/v2/organizations with options {'verify': False, 'auth': ('admin', 'changeme'), 'headers': {'content-type': 'application/json'}} and data {"name": "\ud9b1\udca7\ud8de\udf4a\udb0e\udeda\udb46\ude5d\udb2b\ude20\udb93\udc71\ud87b\udc1a\ud948\udfbc\ucde0\uda28\ude87\u0ee1\ud9d1\udf0b\udbdc\udf24\uda51\udda7\udb69\udd0c\ud97f\udc46\ud8b3\udc85\udbf5\udd48\udb82\udea5\uda45\ude3a\uda01\udfc9\ud9b4\udd29\uda45\udc6d"}.
2015-08-11 13:59:47 - py.warnings - WARNING - /usr/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

2015-08-11 13:59:52 - nailgun.client - DEBUG - Received HTTP 201 response: {"ancestry":null,"apply_info_task_id":null,"created_at":"2015-08-11T08:29:49Z","description":null,"id":569,"ignore_types":[],"katello_default":true,"label":"6c639229-d01b-4511-8093-558cf0ae2e64","name":"񼒧񇭊󓫚󡩝󚸠󴱱𮰚񢎼췠򚊇໡򄜋􇌤򤖧󪔌񯱆𼲅􍕈󰪥򡘺򐟉񽄩򡑭","title":"񼒧񇭊󓫚󡩝󚸠󴱱𮰚񢎼췠򚊇໡򄜋􇌤򤖧󪔌񯱆𼲅􍕈󰪥򡘺򐟉񽄩򡑭","updated_at":"2015-08-11T08:29:49Z","service_levels":[],"service_level":null}
2015-08-11 13:59:52 - robottelo.ui.locators - DEBUG - Accessing locator "login.username" by id: "login_login"
2015-08-11 13:59:52 - robottelo.ui.locators - DEBUG - Accessing locator "login.username" by id: "login_login"
2015-08-11 13:59:52 - robottelo.ui.locators - DEBUG - Accessing locator "login.password" by id: "login_password"
2015-08-11 13:59:53 - robottelo.ui.locators - DEBUG - Accessing locator "submit" by name: "commit"
2015-08-11 13:59:54 - robottelo.ui.locators - DEBUG - Accessing locator "notif.error" by xpath: "//div[contains(@class, 'jnotify-notification-error')]"
2015-08-11 13:59:59 - robottelo.ui.base - DEBUG - NoSuchElementException: Could not locate element //div[contains(@class, 'jnotify-notification-error')].
2015-08-11 13:59:59 - robottelo.ui.locators - DEBUG - Accessing locator "menu.current_text" by xpath: "//div[contains(@style,'static') or contains(@style,'fixed')]//li[contains(@class,'org-switcher')]/a"
2015-08-11 14:00:01 - robottelo.ui.locators - DEBUG - Accessing locator "menu.fetch_org" by xpath: "//div[contains(@style,'static') or contains(@style, 'fixed')]//li[contains(@class, 'org-menu')]/a"
2015-08-11 14:00:01 - robottelo.ui.locators - DEBUG - Accessing locator "menu.fetch_loc" by xpath: "//div[contains(@style,'static') or contains(@style, 'fixed')]//li[contains(@class, 'loc-menu')]/a"
2015-08-11 14:00:01 - robottelo.ui.locators - DEBUG - Accessing locator "menu.any_context" by xpath: "//div[contains(@style,'static') or contains(@style,'fixed')]//li[contains(@class,'org-switcher')]/a"
2015-08-11 14:00:01 - robottelo.ui.locators - DEBUG - Accessing locator "org.nav_current_org" by xpath: "(//div[contains(@style,'static') or contains(@style,'fixed')]//li[contains(@class,'org-switcher')]//li/a[@data-toggle='dropdown'])[1]"
2015-08-11 14:00:01 - robottelo.ui.locators - DEBUG - Accessing locator "org.select_org" by xpath: "//div[contains(@style,'static') or contains(@style,'fixed')]//a[@href='/organizations/clear']/../../li/a[contains(.,'%s')]"
2015-08-11 14:00:05 - robottelo.ui.locators - DEBUG - Accessing locator "menu.current_text" by xpath: "//div[contains(@style,'static') or contains(@style,'fixed')]//li[contains(@class,'org-switcher')]/a"
2015-08-11 14:00:06 - robottelo.ui.locators - DEBUG - Accessing locator "menu.fetch_org" by xpath: "//div[contains(@style,'static') or contains(@style, 'fixed')]//li[contains(@class, 'org-menu')]/a"
2015-08-11 14:00:06 - robottelo.ui.locators - DEBUG - Accessing locator "menu.content" by xpath: "//div[contains(@style,'static') or contains(@style, 'fixed')]//a[@id='content_menu']"
2015-08-11 14:00:06 - robottelo.ui.locators - DEBUG - Accessing locator "menu.life_cycle_environments" by xpath: "//div[contains(@style,'static') or contains(@style, 'fixed')]//a[@id='menu_item_environments']"
2015-08-11 14:00:19 - robottelo.ui.locators - DEBUG - Accessing locator "content_env.new" by xpath: "//a[contains(@ui-sref, 'environments.new')]"
2015-08-11 14:00:20 - robottelo.ui.locators - DEBUG - Accessing locator "name" by id: "name"
2015-08-11 14:00:23 - robottelo.ui.locators - DEBUG - Accessing locator "name" by id: "name"
2015-08-11 14:00:24 - robottelo.ui.locators - DEBUG - Accessing locator "create" by xpath: "//button[contains(@ng-click,'Save')]"
ERROR
ERROR

ERROR: @test: attempt to promote a content view containing RH content

Traceback (most recent call last):
  File "/home/tkolhar/git/robottelo/tests/foreman/ui/test_contentviews.py", line 731, in test_cv_promote_rh_1
    self.setup_to_create_cv(rh_repo=rh_repo, org_id=org_id)
  File "/home/tkolhar/git/robottelo/tests/foreman/ui/test_contentviews.py", line 75, in setup_to_create_cv
    sub.upload({'organization_id': org_id}, manifest)
AttributeError: 'Subscription' object has no attribute 'upload'

XML: foreman-results.xml
Ran 1 test in 82.565s

FAILED (errors=1)

**Comment by tkolhar** [comment]
closing this as this issue is added a to a common github issue created for all downstream failures
