### ISSUE TITLE
Automation failure : test_host_collection and test_activationkey

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2679]
TestNames:
tests.foreman.cli.test_activationkey.TestActivationKey.test_remove_host_collection_by_id 
tests.foreman.cli.test_activationkey.TestActivationKey.test_remove_host_collection_by_name_1
tests.foreman.cli.test_host_collection.TestHostCollection.test_content_hosts
tests.foreman.cli.test_host_collection.TestHostCollection.test_positive_create_1
tests.foreman.cli.test_host_collection.TestHostCollection.test_positive_delete_1
tests.foreman.cli.test_host_collection.TestHostCollection.test_positive_update_1
tests.foreman.cli.test_host_collection.TestHostCollection.test_remove_content_host 
tests.foreman.cli.test_host_collection.TestHostCollection.test_add_content_host 
Error Message
string indices must be integers

Stacktrace

  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel71-cli/tests/foreman/cli/test_activationkey.py", line 1316, in test_remove_host_collection_by_id
    u'host-collection-id': new_host_col['id'],
'string indices must be integers\n--------------------

**Comment by tkolhar** [comment]
this test is failing when executed locally using nosetests:
$  nosetests -c robottelo.properties -m test_remove_host_collection_by_id /home/tkolhar/git/robottelo/tests/foreman/cli/test_activationkey.py
/usr/lib/python2.7/site-packages/nose/plugins/manager.py:395: RuntimeWarning: Unable to load plugin xunitmp = nose_xunitmp:XunitMP: cannot import name force_unicode
  RuntimeWarning)
@Test: Test that hosts associated to Activation Keys can be removed ... 2015-08-13 12:11:18 - robottelo - DEBUG - Running test TestActivationKey/test_remove_host_collection_by_id
2015-08-13 12:11:18 - robottelo.common.ssh - DEBUG - >>> [dell-pe1955-02.rhts.eng.bos.redhat.com] LANG=en_US.UTF-8  hammer -v -u admin -p changeme --output=csv organization create --name="qsSf4M"
2015-08-13 12:11:21 - robottelo.common.ssh - INFO - Instantiated Paramiko client 0x376eb90
2015-08-13 12:11:25 - robottelo.common.ssh - INFO - Destroying Paramiko client 0x376eb90
2015-08-13 12:11:25 - robottelo.common.ssh - INFO - Destroyed Paramiko client 0x376eb90
2015-08-13 12:11:25 - robottelo.common.ssh - DEBUG - <<< stdout
Message,Id,Name
Organization created,4,qsSf4M

2015-08-13 12:11:25 - robottelo.common.ssh - DEBUG - >>> [dell-pe1955-02.rhts.eng.bos.redhat.com] LANG=en_US.UTF-8  hammer -v -u admin -p changeme  organization info --id="4"
2015-08-13 12:11:28 - robottelo.common.ssh - INFO - Instantiated Paramiko client 0x376f110
2015-08-13 12:11:30 - robottelo.common.ssh - INFO - Destroying Paramiko client 0x376f110
2015-08-13 12:11:30 - robottelo.common.ssh - INFO - Destroyed Paramiko client 0x376f110
2015-08-13 12:11:30 - robottelo.common.ssh - DEBUG - <<< stdout
Id:                     4
Name:                   qsSf4M
Users:                  

Smart proxies:          
    dell-pe1955-02.rhts.eng.bos.redhat.com
Subnets:                

Compute resources:      

Installation media:     

Templates:              
    Boot disk iPXE - generic host (Bootdisk)
    Boot disk iPXE - host (Bootdisk)
    idm_register ()
    Kickstart default iPXE (iPXE)
    Kickstart default PXELinux (PXELinux)
    kickstart_networking_setup ()
    puppet.conf ()
    PXELinux default local boot (PXELinux)
    PXELinux global default (PXELinux)
    Satellite Kickstart Default (provision)
    Satellite Kickstart Default Finish (finish)
    Satellite Kickstart Default User Data (user_data)
    subscription_manager_registration ()
Domains:                

Environments:           

Hostgroups:             

Parameters:             

Created at:             2015/08/13 06:41:24
Updated at:             2015/08/13 06:41:24
Label:                  qsSf4M
Description:            
Red Hat Repository URL: https://cdn.redhat.com


2015-08-13 12:11:30 - robottelo.common.ssh - DEBUG - >>> [dell-pe1955-02.rhts.eng.bos.redhat.com] LANG=en_US.UTF-8  hammer -v -u admin -p changeme --output=csv lifecycle-environment create --prior="Library" --organization-id="4" --name="ehf9mL"
2015-08-13 12:11:33 - robottelo.common.ssh - INFO - Instantiated Paramiko client 0x376edd0
2015-08-13 12:11:36 - robottelo.common.ssh - INFO - Destroying Paramiko client 0x376edd0
2015-08-13 12:11:36 - robottelo.common.ssh - INFO - Destroyed Paramiko client 0x376edd0
2015-08-13 12:11:36 - robottelo.common.ssh - DEBUG - <<< stdout
Message,Id,Name
Environment created,4,ehf9mL

2015-08-13 12:11:36 - robottelo.common.ssh - DEBUG - >>> [dell-pe1955-02.rhts.eng.bos.redhat.com] LANG=en_US.UTF-8  hammer -v -u admin -p changeme  lifecycle-environment info --id="4" --organization-id="4"
2015-08-13 12:11:39 - robottelo.common.ssh - INFO - Instantiated Paramiko client 0x376f090
2015-08-13 12:11:41 - robottelo.common.ssh - INFO - Destroying Paramiko client 0x376f090
2015-08-13 12:11:41 - robottelo.common.ssh - INFO - Destroyed Paramiko client 0x376f090
2015-08-13 12:11:41 - robottelo.common.ssh - DEBUG - <<< stdout
ID:                          4
Name:                        ehf9mL
Label:                       ehf9mL
Description:                 
Organization:                qsSf4M
Library:                     false
Prior Lifecycle Environment: Library


2015-08-13 12:11:41 - robottelo.common.ssh - DEBUG - >>> [dell-pe1955-02.rhts.eng.bos.redhat.com] LANG=en_US.UTF-8  hammer -v -u admin -p changeme --output=csv lifecycle-environment create --prior="ehf9mL" --organization-id="4" --name="yhTYQ7"
2015-08-13 12:11:44 - robottelo.common.ssh - INFO - Instantiated Paramiko client 0x376eed0
2015-08-13 12:11:46 - robottelo.common.ssh - INFO - Destroying Paramiko client 0x376eed0
2015-08-13 12:11:46 - robottelo.common.ssh - INFO - Destroyed Paramiko client 0x376eed0
2015-08-13 12:11:46 - robottelo.common.ssh - DEBUG - <<< stdout
Message,Id,Name
Environment created,5,yhTYQ7

2015-08-13 12:11:46 - robottelo.common.ssh - DEBUG - >>> [dell-pe1955-02.rhts.eng.bos.redhat.com] LANG=en_US.UTF-8  hammer -v -u admin -p changeme  lifecycle-environment info --id="5" --organization-id="4"
2015-08-13 12:11:49 - robottelo.common.ssh - INFO - Instantiated Paramiko client 0x3773c50
2015-08-13 12:11:51 - robottelo.common.ssh - INFO - Destroying Paramiko client 0x3773c50
2015-08-13 12:11:51 - robottelo.common.ssh - INFO - Destroyed Paramiko client 0x3773c50
2015-08-13 12:11:51 - robottelo.common.ssh - DEBUG - <<< stdout
ID:                          5
Name:                        yhTYQ7
Label:                       yhTYQ7
Description:                 
Organization:                qsSf4M
Library:                     false
Prior Lifecycle Environment: ehf9mL


2015-08-13 12:11:51 - robottelo.common.ssh - DEBUG - >>> [dell-pe1955-02.rhts.eng.bos.redhat.com] LANG=en_US.UTF-8  hammer -v -u admin -p changeme --output=csv product create --organization-id="4" --description="cMCdhpfVLqFoHeYORJJQ" --name="beJsHYFeFugQuHmMWahg" --label="gSPnhZSPNjZJrbMmVLNS"
2015-08-13 12:11:54 - robottelo.common.ssh - INFO - Instantiated Paramiko client 0x376ef90
2015-08-13 12:11:58 - robottelo.common.ssh - INFO - Destroying Paramiko client 0x376ef90
2015-08-13 12:11:58 - robottelo.common.ssh - INFO - Destroyed Paramiko client 0x376ef90
2015-08-13 12:11:58 - robottelo.common.ssh - DEBUG - <<< stdout
Message,Id,Name
Product created,2,beJsHYFeFugQuHmMWahg

2015-08-13 12:11:58 - robottelo.common.ssh - DEBUG - >>> [dell-pe1955-02.rhts.eng.bos.redhat.com] LANG=en_US.UTF-8  hammer -v -u admin -p changeme  product info --id="2" --organization-id="4"
2015-08-13 12:12:00 - robottelo.common.ssh - INFO - Instantiated Paramiko client 0x3773cd0
2015-08-13 12:12:03 - robottelo.common.ssh - INFO - Destroying Paramiko client 0x3773cd0
2015-08-13 12:12:03 - robottelo.common.ssh - INFO - Destroyed Paramiko client 0x3773cd0
2015-08-13 12:12:03 - robottelo.common.ssh - DEBUG - <<< stdout
ID:           2
Name:         beJsHYFeFugQuHmMWahg
Label:        gSPnhZSPNjZJrbMmVLNS
Description:  cMCdhpfVLqFoHeYORJJQ
Sync State:   
Sync Plan ID: 
GPG:          
    GPG Key ID: 
    GPG Key:
Organization: qsSf4M
Readonly:     false
Deletable:    
Content:


2015-08-13 12:12:03 - robottelo.common.ssh - DEBUG - >>> [dell-pe1955-02.rhts.eng.bos.redhat.com] LANG=en_US.UTF-8  hammer -v -u admin -p changeme  lifecycle-environment info --name="Library" --organization-id="4"
2015-08-13 12:12:06 - robottelo.common.ssh - INFO - Instantiated Paramiko client 0x376f150
2015-08-13 12:12:08 - robottelo.common.ssh - INFO - Destroying Paramiko client 0x376f150
2015-08-13 12:12:08 - robottelo.common.ssh - INFO - Destroyed Paramiko client 0x376f150
2015-08-13 12:12:08 - robottelo.common.ssh - DEBUG - <<< stdout
ID:                          3
Name:                        Library
Label:                       Library
Description:                 
Organization:                qsSf4M
Library:                     true
Prior Lifecycle Environment:


2015-08-13 12:12:08 - robottelo.common.ssh - DEBUG - >>> [dell-pe1955-02.rhts.eng.bos.redhat.com] LANG=en_US.UTF-8  hammer -v -u admin -p changeme --output=csv activation-key create --organization-id="4" --name="VsCM65aHYO" --unlimited-content-hosts="true"
2015-08-13 12:12:11 - robottelo.common.ssh - INFO - Instantiated Paramiko client 0x3773490
2015-08-13 12:12:15 - robottelo.common.ssh - INFO - Destroying Paramiko client 0x3773490
2015-08-13 12:12:15 - robottelo.common.ssh - INFO - Destroyed Paramiko client 0x3773490
2015-08-13 12:12:15 - robottelo.common.ssh - DEBUG - <<< stdout
Message,Id,Name
Activation key created,1,VsCM65aHYO

2015-08-13 12:12:15 - robottelo.common.ssh - DEBUG - >>> [dell-pe1955-02.rhts.eng.bos.redhat.com] LANG=en_US.UTF-8  hammer -v -u admin -p changeme  activation-key info --id="1"
2015-08-13 12:12:18 - robottelo.common.ssh - INFO - Instantiated Paramiko client 0x376f090
2015-08-13 12:12:20 - robottelo.common.ssh - INFO - Destroying Paramiko client 0x376f090
2015-08-13 12:12:21 - robottelo.common.ssh - INFO - Destroyed Paramiko client 0x376f090
2015-08-13 12:12:21 - robottelo.common.ssh - DEBUG - <<< stdout
Name:                  VsCM65aHYO
ID:                    1
Description:           
Content Host Limit:    Unlimited
Auto Attach:           true
Lifecycle Environment: 
Content View:          
Host Collections:


2015-08-13 12:12:21 - robottelo.common.ssh - DEBUG - >>> [dell-pe1955-02.rhts.eng.bos.redhat.com] LANG=en_US.UTF-8  hammer -v -u admin -p changeme --output=csv host-collection create --organization-id="4" --name="qRCqQHaTsO"
2015-08-13 12:12:23 - robottelo.common.ssh - INFO - Instantiated Paramiko client 0x376ef90
2015-08-13 12:12:26 - robottelo.common.ssh - INFO - Destroying Paramiko client 0x376ef90
2015-08-13 12:12:26 - robottelo.common.ssh - INFO - Destroyed Paramiko client 0x376ef90
2015-08-13 12:12:26 - robottelo.common.ssh - DEBUG - <<< stdout
Message,Id,Name
Host collection created,1,qRCqQHaTsO

2015-08-13 12:12:26 - robottelo.common.ssh - DEBUG - >>> [dell-pe1955-02.rhts.eng.bos.redhat.com] LANG=en_US.UTF-8  hammer -v -u admin -p changeme  host-collection info --id="1"
2015-08-13 12:12:28 - robottelo.common.ssh - INFO - Instantiated Paramiko client 0x376f150
2015-08-13 12:12:31 - robottelo.common.ssh - INFO - Destroying Paramiko client 0x376f150
2015-08-13 12:12:31 - robottelo.common.ssh - INFO - Destroyed Paramiko client 0x376f150
2015-08-13 12:12:31 - robottelo.common.ssh - DEBUG - <<< stdout
ID:                  1
Name:                qRCqQHaTsO
Limit:               None
Description:         
Total Content Hosts: 0


ERROR

ERROR: @Test: Test that hosts associated to Activation Keys can be removed

Traceback (most recent call last):
  File "/home/tkolhar/git/robottelo/tests/foreman/cli/test_activationkey.py", line 1316, in test_remove_host_collection_by_id
    u'host-collection-id': new_host_col['id'],
TypeError: string indices must be integers


XML: foreman-results.xml

Ran 1 test in 72.472s

FAILED (errors=1)

**Comment by tkolhar** [comment]
closing this as this issue is added a to a common github issue created for all downstream failures
