### ISSUE TITLE
Automation failure : tests.foreman.cli.test_repository.TestRepository

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2680]
TestNames:
tests.foreman.cli.test_repository.TestRepository.test_positive_create_6

Error Message

Failed to create Repository with data:
{
  "checksum-type": null, 
  "content-type": "yum", 
  "docker-upstream-name": null, 
  "gpg-key": "pQWMl2R1Da", 
  "gpg-key-id": null, 
  "label": null, 
  "name": "\ud85c\udef1\ud854\udd79\ud852\udee0\ud85c\udf59\ud840\udfc8\u1b83\ud86a\ude72\u55fb\u78f5\u7cac\uaf1e\ud85f\ude4e\ud856\udee9\ud869\udcbe\ud85f\udef4", 
  "organization": null, 
  "organization-id": null, 
  "organization-label": null, 
  "product": null, 
  "product-id": "1372", 
  "publish-via-http": "true", 
  "url": "http://inecas.fedorapeople.org/fakerepos/zoo3/"
}

robottelo.common.ssh: DEBUG: >>> [qe-sat6-rhel71.usersys.redhat.com] LANG=en_US.UTF-8  hammer -v -u admin -p changeme --output=csv repository create --product-id="1372" --name="10𧋱10𧋱𥅹10𧋱𥅹𤫠10𧋱𥅹𤫠𧍙10𧋱𥅹𤫠𧍙𠏈ᮃ10𧋱𥅹𤫠𧍙𠏈𪩲嗻磵粬꼞10𧋱𥅹𤫠𧍙𠏈𪩲𧹎10𧋱𥅹𤫠𧍙𠏈𪩲𧹎𥫩10𧋱𥅹𤫠𧍙𠏈𪩲𧹎𥫩𪒾10𧋱𥅹𤫠𧍙𠏈𪩲𧹎𥫩𪒾𧻴" --publish-via-http="true" --url="http://inecas.fedorapeople.org/fakerepos/zoo3/" --gpg-key="pQWMl2R1Da" --content-type="yum"
robottelo.common.ssh: INFO: Instantiated Paramiko client 0x4605d50
robottelo.common.ssh: INFO: Destroying Paramiko client 0x4605d50
robottelo.common.ssh: INFO: Destroyed Paramiko client 0x4605d50
robottelo.common.ssh: DEBUG: <<< stderr
[ERROR 2015-08-13 00:03:34 Exception] Error: Could not find organization, please set one of options --organization, --organization-label, --organization-id.
Could not create the repository:
  Error: Could not find organization, please set one of options --organization, --organization-label, --organization-id.
[ERROR 2015-08-13 00:03:34 Exception] 

HammerCLIForeman::MissingSeachOptions (Could not find organization, please set one of options --organization, --organization-label, --organization-id.):
    /usr/share/gems/gems/hammer_cli_foreman-0.1.4.14/lib/hammer_cli_foreman/commands.rb:198:in `rescue in send_request'
    /usr/share/gems/gems/hammer_cli_foreman-0.1.4.14/lib/hammer_cli_foreman/commands.rb:185:in `send_request'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/lib/hammer_cli/apipie/command.rb:34:in `execute'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/lib/hammer_cli/abstract.rb:23:in `run'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/lib/hammer_cli/abstract.rb:23:in `run'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/lib/hammer_cli/abstract.rb:23:in `run'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:125:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/bin/hammer:108:in `<top (required)>'
    /usr/bin/hammer:23:in `load'
    /usr/bin/hammer:23:in `<main>'

Stacktrace

  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "/home/jenkins/shiningpanda/jobs/107b379a/virtualenvs/d41d8cd9/lib/python2.7/site-packages/ddt.py", line 146, in wrapper
    return func(self, *args, **kwargs)
  File "robottelo/common/decorators.py", line 372, in wrapper_func
    return func(*args, **kwargs)
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel71-cli/tests/foreman/cli/test_repository.py", line 241, in test_positive_create_6
    u'gpg-key': new_gpg_key['name'],
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel71-cli/tests/foreman/cli/test_repository.py", line 66, in _make_repository
    return make_repository(options)
  File "robottelo/common/decorators.py", line 73, in cacheable_function
    new_object = func(options)
  File "robottelo/cli/factory.py", line 640, in make_repository
    return create_object(Repository, args, options)
  File "robottelo/cli/factory.py", line 94, in create_object
    json.dumps(options, indent=2, sort_keys=True)
'Failed to create Repository with data:\n{\n  "checksum-type": null, \n  "content-type": "yum", \n  "docker-upstream-name": null, \n  "gpg-key": "pQWMl2R1Da", \n  "gpg-key-id": null, \n  "label": null, \n  "name": "\\ud85c\\udef1\\ud854\\udd79\\ud852\\udee0\\ud85c\\udf59\\ud840\\udfc8\\u1b83\\ud86a\\ude72\\u55fb\\u78f5\\u7cac\\uaf1e\\ud85f\\ude4e\\ud856\\udee9\\ud869\\udcbe\\ud85f\\udef4", \n  "organization": null, \n  "organization-id": null, \n  "organization-label": null, \n  "product": null, \n  "product-id": "1372", \n  "publish-via-http": "true", \n  "url": "http://inecas.fedorapeople.org/fakerepos/zoo3/"\n}\n--------------------

**Comment by tkolhar** [comment]
this test is failing when executed locally using nosetest:
$  nosetests -c robottelo.properties -m test_positive_create_6 /home/tkolhar/git/robottelo/tests/foreman/cli/test_repository.py
/usr/lib/python2.7/site-packages/nose/plugins/manager.py:395: RuntimeWarning: Unable to load plugin xunitmp = nose_xunitmp:XunitMP: cannot import name force_unicode
  RuntimeWarning)
@Test: Check if repository can be created with gpg key name ... 2015-08-13 12:05:20 - robottelo - DEBUG - Running test TestRepository/test_positive_create_6_1_GkLAMCokxgwjlwp
2015-08-13 12:05:20 - robottelo.common.ssh - DEBUG - >>> [dell-pe1955-02.rhts.eng.bos.redhat.com] LANG=en_US.UTF-8  hammer -v -u admin -p changeme --output=csv organization create --name="tSVEdO"
2015-08-13 12:05:22 - robottelo.common.ssh - INFO - Instantiated Paramiko client 0x3675d90
2015-08-13 12:05:29 - robottelo.common.ssh - INFO - Destroying Paramiko client 0x3675d90
2015-08-13 12:05:29 - robottelo.common.ssh - INFO - Destroyed Paramiko client 0x3675d90
2015-08-13 12:05:29 - robottelo.common.ssh - DEBUG - <<< stdout
Message,Id,Name
Organization created,3,tSVEdO

2015-08-13 12:05:29 - robottelo.common.ssh - DEBUG - >>> [dell-pe1955-02.rhts.eng.bos.redhat.com] LANG=en_US.UTF-8  hammer -v -u admin -p changeme  organization info --id="3"
2015-08-13 12:05:32 - robottelo.common.ssh - INFO - Instantiated Paramiko client 0x3676250
2015-08-13 12:05:35 - robottelo.common.ssh - INFO - Destroying Paramiko client 0x3676250
2015-08-13 12:05:35 - robottelo.common.ssh - INFO - Destroyed Paramiko client 0x3676250
2015-08-13 12:05:35 - robottelo.common.ssh - DEBUG - <<< stdout
Id:                     3
Name:                   tSVEdO
Users:                  

Smart proxies:          
    dell-pe1955-02.rhts.eng.bos.redhat.com
Subnets:                

Compute resources:      

Installation media:     

Templates:              
    Boot disk iPXE - generic host (Bootdisk)
    Boot disk iPXE - host (Bootdisk)
    idm_register ()
    Kickstart default iPXE (iPXE)
    Kickstart default PXELinux (PXELinux)
    kickstart_networking_setup ()
    puppet.conf ()
    PXELinux default local boot (PXELinux)
    PXELinux global default (PXELinux)
    Satellite Kickstart Default (provision)
    Satellite Kickstart Default Finish (finish)
    Satellite Kickstart Default User Data (user_data)
    subscription_manager_registration ()
Domains:                

Environments:           

Hostgroups:             

Parameters:             

Created at:             2015/08/13 06:35:26
Updated at:             2015/08/13 06:35:26
Label:                  tSVEdO
Description:            
Red Hat Repository URL: https://cdn.redhat.com


2015-08-13 12:05:35 - robottelo.common.ssh - DEBUG - >>> [dell-pe1955-02.rhts.eng.bos.redhat.com] LANG=en_US.UTF-8  hammer -v -u admin -p changeme --output=csv product create --organization-id="3" --description="IfTmCxPSyGDFohFuFQfw" --name="BodFEyikbTzqkOqFOvIl" --label="YPqXQttksRpMoMwMZvdv"
2015-08-13 12:05:37 - robottelo.common.ssh - INFO - Instantiated Paramiko client 0x3675d90
2015-08-13 12:05:43 - robottelo.common.ssh - INFO - Destroying Paramiko client 0x3675d90
2015-08-13 12:05:43 - robottelo.common.ssh - INFO - Destroyed Paramiko client 0x3675d90
2015-08-13 12:05:43 - robottelo.common.ssh - DEBUG - <<< stdout
Message,Id,Name
Product created,1,BodFEyikbTzqkOqFOvIl

2015-08-13 12:05:43 - robottelo.common.ssh - DEBUG - >>> [dell-pe1955-02.rhts.eng.bos.redhat.com] LANG=en_US.UTF-8  hammer -v -u admin -p changeme  product info --id="1" --organization-id="3"
2015-08-13 12:05:45 - robottelo.common.ssh - INFO - Instantiated Paramiko client 0x3676250
2015-08-13 12:05:48 - robottelo.common.ssh - INFO - Destroying Paramiko client 0x3676250
2015-08-13 12:05:48 - robottelo.common.ssh - INFO - Destroyed Paramiko client 0x3676250
2015-08-13 12:05:48 - robottelo.common.ssh - DEBUG - <<< stdout
ID:           1
Name:         BodFEyikbTzqkOqFOvIl
Label:        YPqXQttksRpMoMwMZvdv
Description:  IfTmCxPSyGDFohFuFQfw
Sync State:   
Sync Plan ID: 
GPG:          
    GPG Key ID: 
    GPG Key:
Organization: tSVEdO
Readonly:     false
Deletable:    
Content:


2015-08-13 12:05:48 - robottelo.common.decorators - INFO - Bugzilla bug 1103944 not in cache. Fetching.
2015-08-13 12:05:48 - py.warnings - WARNING - /usr/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

2015-08-13 12:05:52 - robottelo.common.ssh - INFO - Instantiated Paramiko client 0x367ad10
2015-08-13 12:05:54 - robottelo.common.ssh - INFO - Destroying Paramiko client 0x367ad10
2015-08-13 12:05:54 - robottelo.common.ssh - INFO - Destroyed Paramiko client 0x367ad10
2015-08-13 12:05:54 - robottelo.common.ssh - DEBUG - >>> [dell-pe1955-02.rhts.eng.bos.redhat.com] LANG=en_US.UTF-8  hammer -v -u admin -p changeme --output=csv gpg create --organization-id="3" --name="tWvJuOXdmq" --key="/tmp/OXb09Nk7aI"
2015-08-13 12:05:57 - robottelo.common.ssh - INFO - Instantiated Paramiko client 0x367e610
2015-08-13 12:05:59 - robottelo.common.ssh - INFO - Destroying Paramiko client 0x367e610
2015-08-13 12:05:59 - robottelo.common.ssh - INFO - Destroyed Paramiko client 0x367e610
2015-08-13 12:05:59 - robottelo.common.ssh - DEBUG - <<< stdout
Message,Id,Name
GPG Key created,1,tWvJuOXdmq

2015-08-13 12:05:59 - robottelo.common.ssh - DEBUG - >>> [dell-pe1955-02.rhts.eng.bos.redhat.com] LANG=en_US.UTF-8  hammer -v -u admin -p changeme --output=csv gpg info --id="1" --organization-id="3"
2015-08-13 12:06:02 - robottelo.common.ssh - INFO - Instantiated Paramiko client 0x367af10
2015-08-13 12:06:04 - robottelo.common.ssh - INFO - Destroying Paramiko client 0x367af10
2015-08-13 12:06:04 - robottelo.common.ssh - INFO - Destroyed Paramiko client 0x367af10
2015-08-13 12:06:04 - robottelo.common.ssh - DEBUG - <<< stdout
ID,Name,Organization,Content
1,tWvJuOXdmq,tSVEdO,n8qnCl0mkERjr5zbrcCUf0XSLaH3Ml

2015-08-13 12:06:04 - robottelo.common.ssh - DEBUG - >>> [dell-pe1955-02.rhts.eng.bos.redhat.com] LANG=en_US.UTF-8  hammer -v -u admin -p changeme --output=csv repository create --product-id="1" --name="GkLAMCokxgwjlwp" --publish-via-http="true" --url="http://inecas.fedorapeople.org/fakerepos/zoo3/" --gpg-key="tWvJuOXdmq" --content-type="yum"
2015-08-13 12:06:06 - robottelo.common.ssh - INFO - Instantiated Paramiko client 0x367e650
2015-08-13 12:06:09 - robottelo.common.ssh - INFO - Destroying Paramiko client 0x367e650
2015-08-13 12:06:09 - robottelo.common.ssh - INFO - Destroyed Paramiko client 0x367e650
2015-08-13 12:06:09 - robottelo.common.ssh - DEBUG - <<< stderr
[ERROR 2015-08-13 02:36:08 Exception] Error: Could not find organization, please set one of options --organization, --organization-label, --organization-id.
Could not create the repository:
  Error: Could not find organization, please set one of options --organization, --organization-label, --organization-id.
[ERROR 2015-08-13 02:36:08 Exception] 

HammerCLIForeman::MissingSeachOptions (Could not find organization, please set one of options --organization, --organization-label, --organization-id.):
    /usr/share/gems/gems/hammer_cli_foreman-0.1.4.14/lib/hammer_cli_foreman/commands.rb:198:in `rescue in send_request'
    /usr/share/gems/gems/hammer_cli_foreman-0.1.4.14/lib/hammer_cli_foreman/commands.rb:185:in `send_request'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/lib/hammer_cli/apipie/command.rb:34:in `execute'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/lib/hammer_cli/abstract.rb:23:in `run'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/lib/hammer_cli/abstract.rb:23:in `run'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/lib/hammer_cli/abstract.rb:23:in `run'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:125:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.11/bin/hammer:108:in `<top (required)>'
    /usr/bin/hammer:23:in `load'
    /usr/bin/hammer:23:in `<main>'



ERROR

======================================================================
ERROR: @Test: Check if repository can be created with gpg key name
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ddt.py", line 146, in wrapper
    return func(self, *args, **kwargs)
  File "/home/tkolhar/git/robottelo/robottelo/common/decorators.py", line 372, in wrapper_func
    return func(*args, **kwargs)
  File "/home/tkolhar/git/robottelo/tests/foreman/cli/test_repository.py", line 241, in test_positive_create_6
    u'gpg-key': new_gpg_key['name'],
  File "/home/tkolhar/git/robottelo/tests/foreman/cli/test_repository.py", line 66, in _make_repository
    return make_repository(options)
  File "/home/tkolhar/git/robottelo/robottelo/common/decorators.py", line 73, in cacheable_function
    new_object = func(options)
  File "/home/tkolhar/git/robottelo/robottelo/cli/factory.py", line 640, in make_repository
    return create_object(Repository, args, options)
  File "/home/tkolhar/git/robottelo/robottelo/cli/factory.py", line 94, in create_object
    json.dumps(options, indent=2, sort_keys=True)
CLIFactoryError: Failed to create Repository with data:
{
  "checksum-type": null, 
  "content-type": "yum", 
  "docker-upstream-name": null, 
  "gpg-key": "tWvJuOXdmq", 
  "gpg-key-id": null, 
  "label": null, 
  "name": "GkLAMCokxgwjlwp", 
  "organization": null, 
  "organization-id": null, 
  "organization-label": null, 
  "product": null, 
  "product-id": "1", 
  "publish-via-http": "true", 
  "url": "http://inecas.fedorapeople.org/fakerepos/zoo3/"
}


XML: foreman-results.xml

Ran 1 test in 48.883s

FAILED (errors=1)

**Comment by tkolhar** [comment]
closing this as this issue is added a to a common github issue created for all downstream failures
