### ISSUE TITLE
api: test_user.py -> test_create() fails when running locally

### ISSUE THREAD

**Issue by sthirugn** [SatelliteQE/robottelo#2805]
jenkins doesnt show any failures but local runs fails:

```sh
Finding files... done.
Importing test modules ... done.

======================================================================
ERROR: test_create_14__u_lastname___u__U0002a345_U000fb471_U000362dc_U00033aba_U0005c9f6__ (tests.foreman.api.test_user.UsersTestCase)
@Test: Create a user with attributes ``attrs`` and delete it.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ddt.py", line 163, in wrapper
    return func(self, *args, **kwargs)
  File "/home/suresh/hacking/framework/robottelo/tests/foreman/api/test_user.py", line 94, in test_create
    user = entities.User(**attrs).create()
  File "/home/suresh/hacking/framework/nailgun/nailgun/entity_mixins.py", line 845, in create
    return self.read(attrs=self.create_json(create_missing))
  File "/home/suresh/hacking/framework/nailgun/nailgun/entity_mixins.py", line 816, in create_json
    response.raise_for_status()
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 851, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity

======================================================================
ERROR: test_create_20__u_login___u__U000e4f43__ (tests.foreman.api.test_user.UsersTestCase)
@Test: Create a user with attributes ``attrs`` and delete it.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ddt.py", line 163, in wrapper
    return func(self, *args, **kwargs)
  File "/home/suresh/hacking/framework/robottelo/tests/foreman/api/test_user.py", line 94, in test_create
    user = entities.User(**attrs).create()
  File "/home/suresh/hacking/framework/nailgun/nailgun/entity_mixins.py", line 845, in create
    return self.read(attrs=self.create_json(create_missing))
  File "/home/suresh/hacking/framework/nailgun/nailgun/entity_mixins.py", line 816, in create_json
    response.raise_for_status()
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 851, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity

======================================================================
ERROR: test_create_8__u_firstname___u__U0001f50f_U000e1598_U00099b10_U001017fb_U0005c17c_U000701bf_U0006f458_U000eafb3_u49c1_U00101d72_U000c4309_U000cdc29_U00014695_U00062413_U000f21c1_U0001ebaf__ (tests.foreman.api.test_user.UsersTestCase)
@Test: Create a user with attributes ``attrs`` and delete it.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ddt.py", line 163, in wrapper
    return func(self, *args, **kwargs)
  File "/home/suresh/hacking/framework/robottelo/tests/foreman/api/test_user.py", line 94, in test_create
    user = entities.User(**attrs).create()
  File "/home/suresh/hacking/framework/nailgun/nailgun/entity_mixins.py", line 845, in create
    return self.read(attrs=self.create_json(create_missing))
  File "/home/suresh/hacking/framework/nailgun/nailgun/entity_mixins.py", line 816, in create_json
    response.raise_for_status()
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 851, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity

======================================================================
ERROR: test_create_9__u_lastname___u_sqPipSKwF73JJDVc8woRFLo5aUUOJlw8tgduNVUBNAlCtKePt__ (tests.foreman.api.test_user.UsersTestCase)
@Test: Create a user with attributes ``attrs`` and delete it.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ddt.py", line 163, in wrapper
    return func(self, *args, **kwargs)
  File "/home/suresh/hacking/framework/robottelo/tests/foreman/api/test_user.py", line 94, in test_create
    user = entities.User(**attrs).create()
  File "/home/suresh/hacking/framework/nailgun/nailgun/entity_mixins.py", line 845, in create
    return self.read(attrs=self.create_json(create_missing))
  File "/home/suresh/hacking/framework/nailgun/nailgun/entity_mixins.py", line 816, in create_json
    response.raise_for_status()
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 851, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity

----------------------------------------------------------------------
Ran 20 tests in 29.355s

FAILED (errors=4)
```

**Comment by sthirugn** [comment]
I checked the failed values in UI and it failed there too.  Now I am curious how jenkins passes each time.

**Comment by sthirugn** [comment]
I saw this in downstream build

**Comment by elyezer** [comment]
Maybe automation leaves the server on a state that raises this. Or have you tested on a clean machine?

**Comment by oshtaier** [comment]
Smoke (like in Jenkins):
```
nosetests tests/foreman/api/test_user.py -m test_create
..
----------------------------------------------------------------------
Ran 2 tests in 11.159s

OK
```
Full:
```
nosetests tests/foreman/api/test_user.py -m test_create
.....................
----------------------------------------------------------------------
Ran 21 tests in 47.370s

OK
```
So maybe something wrong with your environment
I am using latest sources of robottelo and Nailgun + 6.1.2 (RHEL 7.1) Sat

**Comment by sthirugn** [comment]
I recreated the problem outside of robottelo and just using nailgun.  So it is not my environment problem.  I will try to come up with a fix for this:
```sh
>>> lastname = gen_string('utf8', randint(1,16))
>>> lastname
u'\U0006f2b0\U000ed684\U0003cb1d\U0002a56f\U000729c1\U00109b53\U000ebcbc\U000cd89d\U000328f8\U000868cd\U00040583\U0002757d\U0009cc71\U0010a9ff\U000b7883\U000f051b'
>>> len(lastname)
16
>>> user = entities.User(lastname = lastname).create()

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "nailgun/entity_mixins.py", line 842, in create
    return self.read(attrs=self.create_json(create_missing))
  File "nailgun/entity_mixins.py", line 813, in create_json
    response.raise_for_status()
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 851, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity

```
error in log:
```sh
2015-09-28 11:04:13 [I]   Parameters: {"user"=>{"lastname"=>"􄼲\u{97E82}􄗩ﯾ\u{2DB98}\u{A6BFB}\u{D8502}\u{53366}\u{BE96B}\u{84131}", "mail"=>"pKtUqRoC@example.gov", "login"=>"èøÌÍÓàÛßôËíòýôÙëÄçÃáÏÛÕâùìçïääøÝÁïÈÐÛÓøÛÄþÌäìãÊûïÄëÇÐàÕñëÙåÂÛßÞÈÈÒçèÔßåÁØÐñÃÑÄõËèÉôøþüÛÔÍþÝ", "password"=>"[FILTERED]", "auth_source_id"=>1}, "apiv"=>"v2"}
2015-09-28 11:04:14 [I] Authorized user admin(Admin User)
2015-09-28 11:04:17 [E] Unprocessable entity User (id: new):
  Surname is invalid
```

**Comment by oshtaier** [comment]
Is it about length of the string?

**Comment by sthirugn** [comment]
I entered the same lastname 
```py
u'\U0006f2b0\U000ed684\U0003cb1d\U0002a56f\U000729c1\U00109b53\U000ebcbc\U000cd89d\U000328f8\U000868cd\U00040583\U0002757d\U0009cc71\U0010a9ff\U000b7883\U000f051b' 
```
in UI and I got the error '(lastname)'is invalid and is too long (maximum is 50 characters)'

**Comment by Ichimonji10** [comment]
That makes sense. That string contains more than 50 bytes. I'm still a little curious what happens if just `u'\U0006f2b0'` or `u'\U0006f2b0\U000ed684'` is pasted in.

**Comment by sthirugn** [comment]
u'\U0006f2b0\U000ed684\' says invalid in UI.  Now the error message does not refer to length but just `is invalid`

**Comment by sthirugn** [comment]
Fix 1 - https://github.com/SatelliteQE/nailgun/pull/226

**Comment by sthirugn** [comment]
Fix 2 - https://github.com/SatelliteQE/robottelo/pull/2818/files#diff-c216909e77fa7019eceb3463fc6bfc08R18

**Comment by sthirugn** [comment]
There are two root causes in this issue:
* nailgun returning utf8 for login.  This error is not seen consistently as nailgun was returning one of alpha, alphanumeric, cjk, latin1 and utf8.  This is fixed in https://github.com/SatelliteQE/nailgun/pull/226
* tests returning utf8 for firstname, lastname and login.  This is addressed in https://github.com/SatelliteQE/robottelo/pull/2818/files#diff-c216909e77fa7019eceb3463fc6bfc08R18
