### ISSUE TITLE
Check stderr for db errors presence

### ISSUE THREAD

**Issue by abalakh** [SatelliteQE/robottelo#3790]
When hammer command fails, it should show error message explaining the root cause (e.g. `Error: Request Timeout`, `Error: Could not find organization, please set one of options --organization, --organization-label, --organization-id.` etc.), but sometimes instead of error message it shows DB error which is a bug that we should capture.
As per our friday's discussion, i18n testing is not our priority right now, so instead of comparing error message of each hammer command that should fail with some expected message (and creating a huge list of expected error messages, plus reworking all our negative tests), we can try to check db error presence in error message - for example, by forming up some kind of keywords or regular expressions list to compare with. E.g.  `INSERT INTO`, `LEFT OUTER JOIN`, `SELECT(.*)FROM(.*)WHERE(.*)` etc.
All the executed hammer commands are getting analyzed in `cli.Base._handle_response()` method so this should be a good place to interfere. Also negative tests are expecting `CLIReturnCodeError` to be risen, so in case db error was found in stderr - any another exception should be risen and then we won't miss it.
Few examples of db errors in stderr:
```
# hammer role filters
PGError: ERROR:  invalid input syntax for integer: ""
LINE 1: ..."id" = "filters"."role_id" WHERE (("roles"."id" = '')) ORDER...
                                                             ^
: SELECT  "filters"."id" AS t0_r0, "filters"."search" AS t0_r1, "filters"."role_id" AS t0_r2, "filters"."created_at" AS t0_r3, "filters"."updated_at" AS t0_r4, "filters"."taxonomy_search" AS t0_r5, "roles"."id" AS t1_r0, "roles"."name" AS t1_r1, "roles"."builtin" AS t1_r2, "roles"."permissions" AS t1_r3 FROM "filters" LEFT OUTER JOIN "roles" ON "roles"."id" = "filters"."role_id" WHERE (("roles"."id" = '')) ORDER BY role_id, filters.id LIMIT 20 OFFSET 0
```
```
\Error: PG::Error: ERROR:  duplicate key value violates unique constraint "index_katello_subscriptions_on_cp_id"
DETAIL:  Key (cp_id)=(ff80808156a722610156b7811da51b17) already exists.
: INSERT INTO "katello_subscriptions" ("cp_id", "created_at", "updated_at") VALUES ($1, $2, $3) RETURNING "id"
```

**Comment by renzon** [comment]
@abalakh @sghai I started work on this. But would be nice to have some concrete examples to test against. So do you guys have test examples where we are having this kind of false positive?

**Comment by renzon** [comment]
Providing more context: I edited text code to match @sghai example on #3611:
```python
    @run_only_on('sat')
    @tier1
    def test_negative_delete_by_id(self):
        """Create HostGroup then delete it by wrong ID

        @id: 047c9f1a-4dd6-4fdc-b7ed-37cc725c68d3

        @assert: HostGroup is not deleted
        """
        for entity_id in invalid_id_list():
            with self.subTest(entity_id):
                with self.assertRaises(CLIReturnCodeError) as ctx:
                    HostGroup.delete({'id': '097860978249'})
                print(ctx)
```

In this specific case, not found id, error message has nothing DB related:

``` console
[ERROR 2016-09-08 11:24:41 Exception] Resource hostgroup not found by id '097860978249'
Could not delete the hostgroup:
  Resource hostgroup not found by id '097860978249'
[ERROR 2016-09-08 11:24:41 Exception] 

RestClient::ResourceNotFound (404 Resource Not Found):
    /opt/theforeman/tfm/root/usr/share/gems/gems/rest-client-1.6.7/lib/restclient/abstract_response.rb:48:in `return!'
    /opt/theforeman/tfm/root/usr/share/gems/gems/apipie-bindings-0.0.16/lib/apipie_bindings/api.rb:308:in `block in rest_client_call_block'
    /opt/theforeman/tfm/root/usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:228:in `call'
    /opt/theforeman/tfm/root/usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:228:in `process_result'
    /opt/theforeman/tfm/root/usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:178:in `block in transmit'
    /opt/rh/rh-ruby22/root/usr/share/ruby/net/http.rb:853:in `start'
    /opt/theforeman/tfm/root/usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:172:in `transmit'
    /opt/theforeman/tfm/root/usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:64:in `execute'
    /opt/theforeman/tfm/root/usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `execute'
    /opt/theforeman/tfm/root/usr/share/gems/gems/rest-client-1.6.7/lib/restclient/resource.rb:94:in `delete'
    /opt/theforeman/tfm/root/usr/share/gems/gems/apipie-bindings-0.0.16/lib/apipie_bindings/api.rb:295:in `call_client'
    /opt/theforeman/tfm/root/usr/share/gems/gems/apipie-bindings-0.0.16/lib/apipie_bindings/api.rb:224:in `http_call'
    /opt/theforeman/tfm/root/usr/share/gems/gems/apipie-bindings-0.0.16/lib/apipie_bindings/api.rb:174:in `call_action'
    /opt/theforeman/tfm/root/usr/share/gems/gems/apipie-bindings-0.0.16/lib/apipie_bindings/api.rb:169:in `call'
    /opt/theforeman/tfm/root/usr/share/gems/gems/apipie-bindings-0.0.16/lib/apipie_bindings/resource.rb:14:in `call'
    /opt/theforeman/tfm/root/usr/share/gems/gems/hammer_cli-0.5.1.11/lib/hammer_cli/apipie/command.rb:43:in `send_request'
    /opt/theforeman/tfm/root/usr/share/gems/gems/hammer_cli_foreman-0.5.1.9/lib/hammer_cli_foreman/commands.rb:190:in `send_request'
    /opt/theforeman/tfm/root/usr/share/gems/gems/hammer_cli-0.5.1.11/lib/hammer_cli/apipie/command.rb:34:in `execute'
    /opt/theforeman/tfm/root/usr/share/gems/gems/clamp-1.0.0/lib/clamp/command.rb:68:in `run'
    /opt/theforeman/tfm/root/usr/share/gems/gems/hammer_cli-0.5.1.11/lib/hammer_cli/abstract.rb:22:in `run'
    /opt/theforeman/tfm/root/usr/share/gems/gems/clamp-1.0.0/lib/clamp/subcommand/execution.rb:11:in `execute'
    /opt/theforeman/tfm/root/usr/share/gems/gems/clamp-1.0.0/lib/clamp/command.rb:68:in `run'
    /opt/theforeman/tfm/root/usr/share/gems/gems/hammer_cli-0.5.1.11/lib/hammer_cli/abstract.rb:22:in `run'
    /opt/theforeman/tfm/root/usr/share/gems/gems/clamp-1.0.0/lib/clamp/subcommand/execution.rb:11:in `execute'
    /opt/theforeman/tfm/root/usr/share/gems/gems/clamp-1.0.0/lib/clamp/command.rb:68:in `run'
    /opt/theforeman/tfm/root/usr/share/gems/gems/hammer_cli-0.5.1.11/lib/hammer_cli/abstract.rb:22:in `run'
    /opt/theforeman/tfm/root/usr/share/gems/gems/clamp-1.0.0/lib/clamp/command.rb:133:in `run'
    /opt/theforeman/tfm/root/usr/share/gems/gems/hammer_cli-0.5.1.11/bin/hammer:125:in `<top (required)>'
    /usr/bin/hammer:23:in `load'
    /usr/bin/hammer:23:in `<main>'
```

**Comment by sghai** [comment]
@renzon : If you create a hostgroup with invalid `architecture-id` you will see error like below:
```console 
~]# hammer -u admin -p changeme hostgroup create --name 'text' --architecture-id 1122222
Could not create the hostgroup:
  ERROR:  insert or update on table "hostgroups" violates foreign key constraint "hostgroups_architecture_id_fk"
  DETAIL:  Key (architecture_id)=(1122222) is not present in table "architectures".
```

**Comment by sghai** [comment]
Similar way, same issue with invalid domain-id
```console
~]# hammer -u admin -p changeme hostgroup create --name 'text1' --domain-id 12345
Could not create the hostgroup:
  ERROR:  insert or update on table "hostgroups" violates foreign key constraint "hostgroups_domain_id_fk"
  DETAIL:  Key (domain_id)=(12345) is not present in table "domains".
```

**Comment by svtkachenko** [comment]
@sghai @renzon  Btw, it is also applicable for API tests.
```
2016-09-09 15:20:30 - nailgun.client - DEBUG - Making HTTP POST request to https://qexample.com/api/v2/hostgroups with options {'verify': False, 'auth': ('admin', 'changeme'), 'headers': {'content-type': 'application/json'}} and data {"hostgroup": {"domain_id": "123", "name": "123"}}.
2016-09-09 15:20:31 - nailgun.client - WARNING - Received HTTP 500 response: {
  "error": {"message":"ERROR:  insert or update on table \"hostgroups\" violates foreign key constraint \"hostgroups_domain_id_fk\"\nDETAIL:  Key (domain_id)=(123) is not present in table \"domains\".\n"}
}
```

**Comment by renzon** [comment]
So I see 2 classes of errors here: DB errors when you are not passing some required parameters and errors related do foreign key values. So my approach will be: Creating a CLIBaseError for all CLI errors. Creating CLIMissingParamError, CLIForeignKeyViolation. Both siblings for the existing CLIReturnError. Once we we handle only the last on negative test scenarios, false positives regarding db errors will decrease.
