### ISSUE TITLE
DiscoveredTestCase.test_positive_pxe_based_discovery failing

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#4053]
https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/cli/test_discoveredhost.py#L120
the VM seems to be created just fine, however the test times out waiting for it to appear in discovered hosts (even after ~6 mins).
There's seems to be some problem on the VM side (booting the discovery iso? sending the facts?), but we currently haven't got any mechanism to read from its console to check on its status.
Requires manual debugging.
```
016-10-19 00:25:20 - robottelo.ssh - DEBUG - >>> LANG=en_US.UTF-8  hammer -v -u admin -p changeme  discovery info --name="macd62a6271e9d3"
2016-10-19 00:25:22 - robottelo.ssh - DEBUG - <<< stderr
[ERROR 2016-10-19 00:25:22 Exception] Error: discovered_host not found
Error: discovered_host not found
[ERROR 2016-10-19 00:25:22 Exception] 

HammerCLIForeman::ResolverError (discovered_host not found):
    /opt/theforeman/tfm/root/usr/share/gems/gems/hammer_cli_foreman-0.8.0/lib/hammer_cli_foreman/id_resolver.rb:208:in `pick_result'
    /opt/theforeman/tfm/root/usr/share/gems/gems/hammer_cli_foreman-0.8.0/lib/hammer_cli_foreman/id_resolver.rb:168:in `find_resource'
    /opt/theforeman/tfm/root/usr/share/gems/gems/hammer_cli_foreman-0.8.0/lib/hammer_cli_foreman/id_resolver.rb:143:in `get_id'
    /opt/theforeman/tfm/root/usr/share/gems/gems/hammer_cli_foreman-0.8.0/lib/hammer_cli_foreman/id_resolver.rb:133:in `block (2 levels) in define_id_finders'
    /opt/theforeman/tfm/root/usr/share/gems/gems/hammer_cli_foreman-0.8.0/lib/hammer_cli_foreman/commands.rb:154:in `get_resource_id'
    /opt/theforeman/tfm/root/usr/share/gems/gems/hammer_cli_foreman-0.8.0/lib/hammer_cli_foreman/commands.rb:143:in `get_identifier'
    /opt/theforeman/tfm/root/usr/share/gems/gems/hammer_cli_foreman-0.8.0/lib/hammer_cli_foreman/commands.rb:239:in `customized_options'
    /opt/theforeman/tfm/root/usr/share/gems/gems/hammer_cli_foreman-0.8.0/lib/hammer_cli_foreman/commands.rb:244:in `request_params'
    /opt/theforeman/tfm/root/usr/share/gems/gems/hammer_cli-0.8.0/lib/hammer_cli/apipie/command.rb:43:in `send_request'
    /opt/theforeman/tfm/root/usr/share/gems/gems/hammer_cli_foreman-0.8.0/lib/hammer_cli_foreman/commands.rb:190:in `send_request'
    /opt/theforeman/tfm/root/usr/share/gems/gems/hammer_cli_foreman-0.8.0/lib/hammer_cli_foreman/commands.rb:383:in `send_request'
    /opt/theforeman/tfm/root/usr/share/gems/gems/hammer_cli-0.8.0/lib/hammer_cli/apipie/command.rb:34:in `execute'
    /opt/theforeman/tfm/root/usr/share/gems/gems/clamp-1.0.0/lib/clamp/command.rb:68:in `run'
    /opt/theforeman/tfm/root/usr/share/gems/gems/hammer_cli-0.8.0/lib/hammer_cli/abstract.rb:22:in `run'
    /opt/theforeman/tfm/root/usr/share/gems/gems/clamp-1.0.0/lib/clamp/subcommand/execution.rb:11:in `execute'
    /opt/theforeman/tfm/root/usr/share/gems/gems/clamp-1.0.0/lib/clamp/command.rb:68:in `run'
    /opt/theforeman/tfm/root/usr/share/gems/gems/hammer_cli-0.8.0/lib/hammer_cli/abstract.rb:22:in `run'
    /opt/theforeman/tfm/root/usr/share/gems/gems/clamp-1.0.0/lib/clamp/subcommand/execution.rb:11:in `execute'
    /opt/theforeman/tfm/root/usr/share/gems/gems/clamp-1.0.0/lib/clamp/command.rb:68:in `run'
    /opt/theforeman/tfm/root/usr/share/gems/gems/hammer_cli-0.8.0/lib/hammer_cli/abstract.rb:22:in `run'
    /opt/theforeman/tfm/root/usr/share/gems/gems/clamp-1.0.0/lib/clamp/command.rb:133:in `run'
    /opt/theforeman/tfm/root/usr/share/gems/gems/hammer_cli-0.8.0/bin/hammer:125:in `<top (required)>'
    /usr/bin/hammer:23:in `load'
    /usr/bin/hammer:23:in `<main>'

```

**Comment by sghai** [comment]
should be covered w/ PR #4090

**Comment by sghai** [comment]
Correction: Original issue is for CLI and #4090 on UI. I'll see the test failure again.

**Comment by sghai** [comment]
I ran the test against 6.3 box and test is working fine:

```console
 robottelo]$ py.test -v tests/foreman/cli/test_discoveredhost.py::DiscoveredTestCase -k test_positive_pxe_based_discovery
================================================================ test session starts =================================================================
platform linux2 -- Python 2.7.12, pytest-3.0.2, py-1.4.31, pluggy-0.3.1 -- /usr/bin/python
cachedir: .cache
rootdir: /home/sghai/QE/robottelo, inifile: 
collected 17 items 

tests/foreman/cli/test_discoveredhost.py::DiscoveredTestCase::test_positive_pxe_based_discovery <- robottelo/decorators/__init__.py PASSED

================================================================ 16 tests deselected =================================================================
===================================================== 1 passed, 16 deselected in 176.16 seconds ======================================================

```

**Comment by sghai** [comment]
I see discovery tests were failing w/ sat6.2 on rhel7. But I don't see any failure w/ rhel6 platform. That means its most likely an issue w/ infra or could be setup part.

```
 robottelo]$ py.test -v tests/foreman/ui/test_discoveredhost.py::DiscoveryTestCase -k test_positive_delete
================================================================ test session starts =================================================================
platform linux2 -- Python 2.7.12, pytest-3.0.2, py-1.4.31, pluggy-0.3.1 -- /usr/bin/python
cachedir: .cache
rootdir: /home/sghai/QE/robottelo, inifile: 
collected 42 items 

tests/foreman/ui/test_discoveredhost.py::DiscoveryTestCase::test_positive_delete <- robottelo/decorators/__init__.py PASSED
tests/foreman/ui/test_discoveredhost.py::DiscoveryTestCase::test_positive_delete_from_facts <- robottelo/decorators/__init__.py PASSED
tests/foreman/ui/test_discoveredhost.py::DiscoveryTestCase::test_positive_delete_multiple <- robottelo/decorators/__init__.py PASSED

================================================================ 39 tests deselected =================================================================
===================================================== 3 passed, 39 deselected in 674.57 seconds ======================================================
```

**Comment by rplevka** [comment]
@sghai I finally figured it out :D 
The bug is in the test logic.

There is another test from the same class executed exlusively before our failing test: ` test_positive_provision_without_auto_provision`

This test creates a `discovery rule` with a vague condition: `cpu_count == 1`. Since the test belongs to the same TestClass, they operate on the same Organization. After the test is finished, it leaves the rule in place and turns the `auto provisioning` flag back `on`, which makes sour next test hit the rule and auto-provision the host.

I analyzed the logs and can clearly see, the host got discovered:

```
2018-02-16 08:04:46 f8e0c057 [app] [I] Started POST "/api/v2/discovered_hosts/facts" for 10.8.211.66 at 2018-02-16 08:04:46 -0500
2018-02-16 08:04:46 f8e0c057 [app] [I] Processing by Api::V2::DiscoveredHostsController#facts as JSON
2018-02-16 08:04:46 f8e0c057 [app] [I]   Parameters: {"facts"=>"[FILTERED]", "apiv"=>"v2", "discovered_host"=>{"facts"=>"[FILTERED]"}}
2018-02-16 08:04:47 f8e0c057 [app] [I] Import facts for 'mac52c86ab4a436' completed. Added: 144, Updated: 0, Deleted 0 facts
2018-02-16 08:04:47 f8e0c057 [app] [I] Detected subnet: Default Subnet with taxonomy ["mSzffJzHXN", "xfg9kH"]/["c50nH5ninS", "yuWonEZQcy"]
2018-02-16 08:04:47 f8e0c057 [app] [I] Assigned location: yuWonEZQcy
2018-02-16 08:04:47 f8e0c057 [app] [I] Assigned organization: mSzffJzHXN
```
and then, briefly after discovered, it got provisioned - and that all happened before/between our 2 discovered_host searches:

```
2018-02-16 08:04:47 f8e0c057 [app] [I] Match found for host mac52c86ab4a436 (101) rule MQSleHVXmz (3)
2018-02-16 08:04:48 f8e0c057 [app] [I] Create DHCP reservation mac52c86ab4a436.foo.bar.com for mac52c86ab4a436.foo.bar.com-52:c8:6a:b4:a4:36/10.8.211.66
2018-02-16 08:04:48 f8e0c057 [app] [I] Add DNS A record for mac52c86ab4a436.foo.barcom/10.8.211.66
2018-02-16 08:04:48 f8e0c057 [app] [I] Add DNS AAAA record for mac52c86ab4a436.foo.bar.com/2620:52:0:8d3:50c8:6aff:feb4:a436
2018-02-16 08:04:48 f8e0c057 [app] [I] Add DNS PTR record for 10.8.211.66/mac52c86ab4a436.foo.bar.com
2018-02-16 08:04:48 f8e0c057 [app] [I] Completed 201 Created in 1917ms (Views: 4.8ms | ActiveRecord: 167.4ms)
2018-02-16 08:04:49 88553203 [app] [I] Started GET "/discovered_hosts/auto_complete_search?search=name+%3D+%22mac52c86ab4a436%22" for 10.8.0.99 at 2018-02-16 08:04:49 -0500
```
There are multiple options how to remediate the situation:
- delete the rule as a cleanup after the previous test is done (quick solution)
- modify the discovery rule to only apply to a host related to the test that created the rule - e.g. exact match to a hostname (probably the quickest solution)
- have the `auto_discovery` flag set to `False` as default and only turn it on explicitly in the tests that need that (this is IMHO right thing to do)

There's one more thing slightly related to this test, although it is not blocking it:
the current way of executing `virt-install` makes the domain shut down on reboot and never go up automatically. You can see this as a side effect at the test `tear down`, where we try to `virsh destroy` and the output is, that the domain is not running.
- this might block some real PXE-based provisioning tests.
anyway, the solution is to specify the BIOS boot option (to make the domain boot from the NW interface - pxe).


- i will submit a PR soon

**Comment by rplevka** [comment]
marking `High` as this makes the test to take 30 minutes and always fail - fixing in will bring in the benefit of saving a lot of execution time.

**Comment by sghai** [comment]
Great analysis. thank you catching the real issue @rplevka

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
