### ISSUE TITLE
cli.test_contenthost.ContentHostTestCase.test_positive_delete_by_id - host not removed

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#4202]
The host is being unregistered but keep showing up on listing the hosts.

```
2017-01-18 01:51:06 - robottelo.ssh - DEBUG - >>> LANG=en_US.UTF-8  hammer -v -u admin -p changeme  host subscription unregister --host-id="64"
2017-01-18 01:51:09 - robottelo.ssh - DEBUG - <<< stdout
Host unregistered


2017-01-18 01:51:10 - robottelo.ssh - DEBUG - Connected to [qe-sat62-rhel6.satqe.com]
2017-01-18 01:51:10 - robottelo.ssh - DEBUG - >>> LANG=en_US.UTF-8  hammer -v -u admin -p changeme  content-host info --id="58fad2b1-db3e-4ad5-a969-c49f25f3a2d9"
2017-01-18 01:51:12 - robottelo.ssh - DEBUG - <<< stdout
Name:                    ohYCnPSdcmXgmgY
ID:                      6610c4d8-f4df-48cd-b9bc-85ad4e50f8ee
Katello Agent Installed: no
Location:                None
Lifecycle Environment:   KAGrTd
Content View:            qsQDEVOWGu
Entitlement Status:      valid
Release Version:·········
Autoheal:                true
Security Errata:         0   
Bugfix Errata:           0   
Enhancement Errata:      0   
```

the previous builds passed, however the assertion might be refined as the `info` command finished with 400:

```
2017-01-06 07:05:06 - robottelo.ssh - DEBUG - >>> LANG=en_US.UTF-8  hammer -v -u admin -p changeme  content-host info --id="cc4f6c63-cd38-4376-b4bd-0bff761cc042"
2017-01-06 07:05:08 - robottelo.ssh - DEBUG - <<< stderr
[ERROR 2017-01-06 07:05:08 Exception] Katello::Resources::Candlepin::Consumer: 410 Gone {"displayMessage":"Unit cc4f6c63-cd38-4376-b4bd-0bff761cc042 has been deleted","requestUuid":"12840916-f2e9-41d2-a4a0-071c344dbf25","deletedId":"cc4f6c63-cd38-4376-b4bd-0bff761cc042"} (GET /candlepin/consumers/cc4f6c63-cd38-4376-b4bd-0bff761cc042)
Katello::Resources::Candlepin::Consumer: 410 Gone {"displayMessage":"Unit cc4f6c63-cd38-4376-b4bd-0bff761cc042 has been deleted","requestUuid":"12840916-f2e9-41d2-a4a0-071c344dbf25","deletedId":"cc4f6c63-cd38-4376-b4bd-0bff761cc042"} (GET /candlepin/consumers/cc4f6c63-cd38-4376-b4bd-0bff761cc042)
[ERROR 2017-01-06 07:05:08 Exception] 

RestClient::BadRequest (400 Bad Request):
    /opt/theforeman/tfm/root/usr/share/gems/gems/rest-client-1.6.7/lib/restclient/abstract_response.rb:48:in `return!'
    /opt/theforeman/tfm/root/usr/share/gems/gems/apipie-bindings-0.0.16/lib/apipie_bindings/api.rb:308:in `block in rest_client_call_block'
    /opt/theforeman/tfm/root/usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:228:in `call'
    /opt/theforeman/tfm/root/usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:228:in `process_result'
    /opt/theforeman/tfm/root/usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:178:in `block in transmit'
    /opt/rh/rh-ruby22/root/usr/share/ruby/net/http.rb:853:in `start'
    /opt/theforeman/tfm/root/usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:172:in `transmit'
    /opt/theforeman/tfm/root/usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:64:in `execute'
    /opt/theforeman/tfm/root/usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `execute'
    /opt/theforeman/tfm/root/usr/share/gems/gems/rest-client-1.6.7/lib/restclient/resource.rb:51:in `get'
    /opt/theforeman/tfm/root/usr/share/gems/gems/apipie-bindings-0.0.16/lib/apipie_bindings/api.rb:295:in `call_client'
    /opt/theforeman/tfm/root/usr/share/gems/gems/apipie-bindings-0.0.16/lib/apipie_bindings/api.rb:224:in `http_call'
    /opt/theforeman/tfm/root/usr/share/gems/gems/apipie-bindings-0.0.16/lib/apipie_bindings/api.rb:174:in `call_action'
    /opt/theforeman/tfm/root/usr/share/gems/gems/apipie-bindings-0.0.16/lib/apipie_bindings/api.rb:169:in `call'
    /opt/theforeman/tfm/root/usr/share/gems/gems/apipie-bindings-0.0.16/lib/apipie_bindings/resource.rb:14:in `call'
    /opt/theforeman/tfm/root/usr/share/gems/gems/hammer_cli-0.5.1.12/lib/hammer_cli/apipie/command.rb:43:in `send_request'
    /opt/theforeman/tfm/root/usr/share/gems/gems/hammer_cli_foreman-0.5.1.10/lib/hammer_cli_foreman/commands.rb:190:in `send_request'
    /opt/theforeman/tfm/root/usr/share/gems/gems/hammer_cli_foreman-0.5.1.10/lib/hammer_cli_foreman/commands.rb:383:in `send_request'
    /opt/theforeman/tfm/root/usr/share/gems/gems/hammer_cli-0.5.1.12/lib/hammer_cli/apipie/command.rb:34:in `execute'
    /opt/theforeman/tfm/root/usr/share/gems/gems/clamp-1.0.0/lib/clamp/command.rb:68:in `run'
    /opt/theforeman/tfm/root/usr/share/gems/gems/hammer_cli-0.5.1.12/lib/hammer_cli/abstract.rb:24:in `run'
    /opt/theforeman/tfm/root/usr/share/gems/gems/clamp-1.0.0/lib/clamp/subcommand/execution.rb:11:in `execute'
    /opt/theforeman/tfm/root/usr/share/gems/gems/clamp-1.0.0/lib/clamp/command.rb:68:in `run'
    /opt/theforeman/tfm/root/usr/share/gems/gems/hammer_cli-0.5.1.12/lib/hammer_cli/abstract.rb:24:in `run'
    /opt/theforeman/tfm/root/usr/share/gems/gems/clamp-1.0.0/lib/clamp/subcommand/execution.rb:11:in `execute'
    /opt/theforeman/tfm/root/usr/share/gems/gems/clamp-1.0.0/lib/clamp/command.rb:68:in `run'
    /opt/theforeman/tfm/root/usr/share/gems/gems/hammer_cli-0.5.1.12/lib/hammer_cli/abstract.rb:24:in `run'
    /opt/theforeman/tfm/root/usr/share/gems/gems/clamp-1.0.0/lib/clamp/command.rb:133:in `run'
    /opt/theforeman/tfm/root/usr/share/gems/gems/hammer_cli-0.5.1.12/bin/hammer:125:in `<top (required)>'
    /usr/bin/hammer:23:in `load'
    /usr/bin/hammer:23:in `<main>'
```

**Comment by rplevka** [comment]
this occurs no more. closing as fixed
