### ISSUE TITLE
test test_host::HostCreateTestCase::test_negative_update_content_source

### ISSUE THREAD

**Issue by ldjebran** [SatelliteQE/robottelo#5778]
This test passed even if the main test command (hammer proxy update) failed , this CLI command has not raised an exception, in plus the cleanup functions was not invoked, this has affected other tests to fail that tests was searching for the default proxy.
This test need a refactoring, as fake capsule and default capsule host has the same name, and we cannot ensure that the proxy was updated relayed on proxy  host name 
```console
2018-01-12 14:38:59 - robottelo.ssh - INFO - Connected to [XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX]
2018-01-12 14:38:59 - robottelo.ssh - INFO - >>> LANG=en_US.UTF-8  hammer -v -u admin -p changeme --output=csv host update --id="94" --content-source-id="19914"
2018-01-12 14:39:03 - robottelo.ssh - INFO - <<< stderr
[ERROR 2018-01-12 14:39:02 API] 500 Internal Server Error
[ERROR 2018-01-12 14:39:02 Exception] ERROR:  insert or update on table "katello_content_facets" violates foreign key constraint "katello_content_facets_content_source_id_fk"
DETAIL:  Key (content_source_id)=(19914) is not present in table "smart_proxies".

Could not update the host:
  ERROR:  insert or update on table "katello_content_facets" violates foreign key constraint "katello_content_facets_content_source_id_fk"
  DETAIL:  Key (content_source_id)=(19914) is not present in table "smart_proxies".
[ERROR 2018-01-12 14:39:02 Exception] 

RestClient::InternalServerError (500 Internal Server Error):
    /opt/theforeman/tfm/root/usr/share/gems/gems/rest-client-1.8.0/lib/restclient/abstract_response.rb:74:in `return!'
    /opt/theforeman/tfm/root/usr/share/gems/gems/apipie-bindings-0.2.0/lib/apipie_bindings/api.rb:352:in `block in rest_client_call_block'
    /opt/theforeman/tfm/root/usr/share/gems/gems/rest-client-1.8.0/lib/restclient/request.rb:493:in `process_result'
    /opt/theforeman/tfm/root/usr/share/gems/gems/rest-client-1.8.0/lib/restclient/request.rb:421:in `block in transmit'
    /opt/rh/rh-ruby23/root/usr/share/ruby/net/http.rb:853:in `start'
    /opt/theforeman/tfm/root/usr/share/gems/gems/rest-client-1.8.0/lib/restclient/request.rb:413:in `transmit'
    /opt/theforeman/tfm/root/usr/share/gems/gems/rest-client-1.8.0/lib/restclient/request.rb:176:in `execute'
    /opt/theforeman/tfm/root/usr/share/gems/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'
    /opt/theforeman/tfm/root/usr/share/gems/gems/rest-client-1.8.0/lib/restclient/resource.rb:76:in `put'
    /opt/theforeman/tfm/root/usr/share/gems/gems/apipie-bindings-0.2.0/lib/apipie_bindings/api.rb:324:in `call_client'
    /opt/theforeman/tfm/root/usr/share/gems/gems/apipie-bindings-0.2.0/lib/apipie_bindings/api.rb:240:in `http_call'
    /opt/theforeman/tfm/root/usr/share/gems/gems/apipie-bindings-0.2.0/lib/apipie_bindings/api.rb:190:in `call_action'
    /opt/theforeman/tfm/root/usr/share/gems/gems/apipie-bindings-0.2.0/lib/apipie_bindings/api.rb:185:in `call'
    /opt/theforeman/tfm/root/usr/share/gems/gems/apipie-bindings-0.2.0/lib/apipie_bindings/resource.rb:21:in `call'
    /opt/theforeman/tfm/root/usr/share/gems/gems/hammer_cli-0.11.0.1/lib/hammer_cli/apipie/command.rb:43:in `send_request'
    /opt/theforeman/tfm/root/usr/share/gems/gems/hammer_cli_foreman-0.11.0.5/lib/hammer_cli_foreman/commands.rb:166:in `send_request'
    /opt/theforeman/tfm/root/usr/share/gems/gems/hammer_cli-0.11.0.1/lib/hammer_cli/apipie/command.rb:34:in `execute'
    /opt/theforeman/tfm/root/usr/share/gems/gems/clamp-1.0.0/lib/clamp/command.rb:68:in `run'
    /opt/theforeman/tfm/root/usr/share/gems/gems/hammer_cli-0.11.0.1/lib/hammer_cli/abstract.rb:29:in `run'
    /opt/theforeman/tfm/root/usr/share/gems/gems/clamp-1.0.0/lib/clamp/subcommand/execution.rb:11:in `execute'
    /opt/theforeman/tfm/root/usr/share/gems/gems/clamp-1.0.0/lib/clamp/command.rb:68:in `run'
    /opt/theforeman/tfm/root/usr/share/gems/gems/hammer_cli-0.11.0.1/lib/hammer_cli/abstract.rb:29:in `run'
    /opt/theforeman/tfm/root/usr/share/gems/gems/clamp-1.0.0/lib/clamp/subcommand/execution.rb:11:in `execute'
    /opt/theforeman/tfm/root/usr/share/gems/gems/clamp-1.0.0/lib/clamp/command.rb:68:in `run'
    /opt/theforeman/tfm/root/usr/share/gems/gems/hammer_cli-0.11.0.1/lib/hammer_cli/abstract.rb:29:in `run'
    /opt/theforeman/tfm/root/usr/share/gems/gems/clamp-1.0.0/lib/clamp/command.rb:133:in `run'
    /opt/theforeman/tfm/root/usr/share/gems/gems/hammer_cli-0.11.0.1/bin/hammer:147:in `<top (required)>'
    /usr/bin/hammer:23:in `load'
    /usr/bin/hammer:23:in `<main>'



2018-01-12 14:39:03 - robottelo.ssh - DEBUG - Destroyed Paramiko client 0x7fe55a46a950
2018-01-12 14:39:03 - robottelo.ssh - DEBUG - Instantiated Paramiko client 0x7fe55a576350
2018-01-12 14:39:03 - robottelo.ssh - INFO - Connected to [XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX]
2018-01-12 14:39:03 - robottelo.ssh - INFO - >>> LANG=en_US.UTF-8  hammer -v -u admin -p changeme  host info --id="94"
2018-01-12 14:39:05 - robottelo.ssh - INFO - <<< stdout
Id:                       94
Name:                     rulybfrxwv.XXXX.XXXXXXXXXXXXXXXXXXXXXXXXX
Organization:             ZQERyM
Location:                 Default Location
Puppet CA Id:             
Puppet Master Id:         
Cert name:                rulybfrxwv.XXXX.XXXXXXXXXXXXXXXXXXXXXXXXX
Managed:                  yes
Installed at:             
Last report:              
... [HOST INFO REMOVED, TOO LONG]

2018-01-12 14:39:05 - robottelo.ssh - DEBUG - Destroyed Paramiko client 0x7fe55a576350
2018-01-12 14:39:05 - robottelo - DEBUG - Finished Test: HostCreateTestCase/test_negative_update_content_source
```
Notice that the test continued working after the failure

**Comment by ldjebran** [comment]
The test have the same behavior on all builds, the proxy is even not created.
Locally the test is creating the proxy, and the proxy for the host is updated successfully.

**Comment by ldjebran** [comment]
The logs was from negative test
