### ISSUE TITLE
robottelo.cli.hammer.parse_info sometimes throws TypeError: list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by jhutar** [SatelliteQE/robottelo#6119]
[output.txt](https://github.com/SatelliteQE/robottelo/files/2162306/output.txt)

Reproduce with:

```
python -c "import robottelo.cli.hammer; robottelo.cli.hammer.parse_info(open('output.txt', 'r').readlines())"
```

When I have added some prints:

```
                    else:
                        print(">>> sub_prop %s" % sub_prop)
                        print(">>> key %s" % key)
                        print(">>> contents %s" % contents)
                        contents[sub_prop][key] = value
```

data are like this:

```
[...]
>>> sub_prop parameters
>>> key xnbtjmxoua
>>> contents {'id': '76\n', 'name': 'ddedcbtuh.0w8rilaqqm\n', 'organization': 'poZGvDS\n', 'location': 'vfFjRNNVkQcr\n', 'puppet-environment': 'jj6cF3c0KXS\n', 'puppet-master-proxy': 'qe-sat64-rhel7-tier3.satqe.lab.eng.rdu2.redhat.com\n', 'cert-name': 'ddedcbtuh.0w8rilaqqm\n', 'managed': 'yes\n', 'installed-at': {}, 'last-report': {}, 'network': {'ipv4-address': '92.5.122.168\n', 'mac': '40:da:d7:b3:11:e4\n', 'domain': '0w8rilaqqm\n'}, 'network-interfaces': [{'id': '76\n', 'identifier': '', 'type': 'interface (primary, provision)\n', 'mac-address': '40:da:d7:b3:11:e4\n', 'ipv4-address': '92.5.122.168\n', 'fqdn': 'ddedcbtuh.0w8rilaqqm\n'}], 'operating-system': {'architecture': 'oDXBDnLSchmP\n', 'operating-system': 'YwaiwEJk 8551\n', 'build': 'yes\n', 'medium': 'lIroyCjBHPa\n', 'partition-table': 'woGMkBxVldDjpnWKZGehuMBboUS\n', 'custom-partition-table': ''}, 'parameters': ['account     include                  password-auth']}
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/pok/Checkouts/robottelo/robottelo/cli/hammer.py", line 280, in parse_info
    contents[sub_prop][key] = value
TypeError: list indices must be integers or slices, not str
```

**Comment by jhutar** [comment]
Ping @ldjebran and @elyezer (based on blame of robottelo/cli/hammer.py in parse_info() :-))

**Comment by ldjebran** [comment]
@jhutar @elyezer think the parameter with multi line broke the login of parsing  
```
Operating system:         
    Architecture:           awgHyEGmpe
    Operating System:       oNXeJAXA 2
    Build:                  yes
    Medium:                 GFqCxQX
    Partition Table:        hgPGNMZGCNGLXPNt
    Custom partition table:
Parameters:               
    gxjzoujaed => 3590Fm3pSw
    kbheuzxudj => SmPIQEa1K7
    thumjhkdjj => auth                          include              password-auth
    account     include                  password-auth
    yzjmxsodee => 9BIPyI1dri
All parameters:           
    gxjzoujaed => 3590Fm3pSw
    kbheuzxudj => SmPIQEa1K7
    thumjhkdjj => auth                          include              password-auth
    account     include                  password-auth
    yzjmxsodee => 9BIPyI1dri
    enable-puppet5 => true
    enable-epel => false
```

**Comment by ldjebran** [comment]
Fix merged
