### ISSUE TITLE
some AirGun tests: http.client.RemoteDisconnected: Remote end closed connection without response

### ISSUE THREAD

**Issue by jhutar** [SatelliteQE/robottelo#6157]
Some AirGun/Widgetastic/UI tests:

* tests.foreman.ui_airgun.test_contentview.test_positive_add_unpublished_cv_to_composite
* tests.foreman.ui_airgun.test_user.test_positive_create_with_multiple_orgs
* tests.foreman.ui_airgun.test_user.test_positive_create_with_all_roles
* tests.foreman.ui_airgun.test_role.test_positive_create_filter_without_override
* tests.foreman.ui_airgun.test_partitiontable.test_positive_create_default_for_organization
* tests.foreman.ui_airgun.test_organization.test_positive_update_template
* tests.foreman.ui_airgun.test_organization.test_positive_update_hostgroup
* tests.foreman.ui_airgun.test_organization.test_positive_update_environment
* tests.foreman.ui_airgun.test_organization.test_positive_update_domain
* tests.foreman.ui_airgun.test_organization.test_positive_update_compresource
* tests.foreman.ui_airgun.test_location.test_positive_update_user

are failing with:

```
session = <airgun.session.Session object at 0x7f213c04bb70>

    @tier2
    def test_positive_add_unpublished_cv_to_composite(session):
        """Attempt to associate unpublished non-composite content view with
        composite content view.
    
        :id: dc253606-3425-489d-bc01-266787d36841
    
        :steps:
    
            1. Create an empty non-composite content view. Do not publish it.
            2. Create a new composite content view
    
        :expectedresults: Non-composite content view is added to composite one
    
        :CaseLevel: Integration
    
        :BZ: 1367123
        """
        unpublished_cv_name = gen_string('alpha')
        composite_cv_name = gen_string('alpha')
        with session:
            # Create unpublished component CV
            session.contentview.create({'name': unpublished_cv_name})
            assert session.contentview.search(
                unpublished_cv_name)[0]['Name'] == unpublished_cv_name
            # Create composite CV
            session.contentview.create({
                'name': composite_cv_name,
>               'composite_view': True,
            })
```
...
```
self = <http.client.HTTPResponse object at 0x7f213ce6a358>

    def _read_status(self):
        line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
        if len(line) > _MAXLINE:
            raise LineTooLong("status line")
        if self.debuglevel > 0:
            print("reply:", repr(line))
        if not line:
            # Presumably, the server closed the connection before
            # sending a valid response.
>           raise RemoteDisconnected("Remote end closed connection without"
                                     " response")
E           http.client.RemoteDisconnected: Remote end closed connection without response

/usr/lib64/python3.6/http/client.py:266: RemoteDisconnected
```
Stdout have this traceback:
```
2018-07-28 01:39:07 - widgetastic_null - ERROR - [ContentViewCreateView/name]: An exception happened during fill('oyRUiVlMyE') call (elapsed 3169 ms)
2018-07-28 01:39:07 - widgetastic_null - ERROR - [ContentViewCreateView/name]: Remote end closed connection without response
Traceback (most recent call last):
  File "/home/jenkins/shiningpanda/jobs/54c9a7ae/virtualenvs/d41d8cd9/lib/python3.6/site-packages/widgetastic/log.py", line 117, in wrapped
    result = f(self, *args, **kwargs)
  File "/home/jenkins/shiningpanda/jobs/54c9a7ae/virtualenvs/d41d8cd9/lib/python3.6/site-packages/widgetastic/widget.py", line 41, in wrapped
    return method(self, Fillable.coerce(value), *args, **kwargs)
  File "/home/jenkins/shiningpanda/jobs/54c9a7ae/virtualenvs/d41d8cd9/lib/python3.6/site-packages/widgetastic/widget.py", line 1138, in fill
    self.browser.click(self)
  File "/home/jenkins/shiningpanda/jobs/54c9a7ae/virtualenvs/d41d8cd9/lib/python3.6/site-packages/widgetastic/browser.py", line 354, in click
    el = self.move_to_element(locator, *args, **kwargs)
  File "/home/jenkins/shiningpanda/jobs/54c9a7ae/virtualenvs/d41d8cd9/lib/python3.6/site-packages/airgun/browser.py", line 605, in move_to_element
    ActionChains(self.selenium).move_to_element(el).perform()
  File "/home/jenkins/shiningpanda/jobs/54c9a7ae/virtualenvs/d41d8cd9/lib/python3.6/site-packages/selenium/webdriver/common/action_chains.py", line 83, in perform
    action()
  File "/home/jenkins/shiningpanda/jobs/54c9a7ae/virtualenvs/d41d8cd9/lib/python3.6/site-packages/selenium/webdriver/common/action_chains.py", line 293, in <lambda>
    Command.MOVE_TO, {'element': to_element.id}))
  File "/home/jenkins/shiningpanda/jobs/54c9a7ae/virtualenvs/d41d8cd9/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 310, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/home/jenkins/shiningpanda/jobs/54c9a7ae/virtualenvs/d41d8cd9/lib/python3.6/site-packages/selenium/webdriver/remote/remote_connection.py", line 466, in execute
    return self._request(command_info[0], url, body=data)
  File "/home/jenkins/shiningpanda/jobs/54c9a7ae/virtualenvs/d41d8cd9/lib/python3.6/site-packages/selenium/webdriver/remote/remote_connection.py", line 528, in _request
    resp = opener.open(request, timeout=self._timeout)
  File "/usr/lib64/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib64/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib64/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib64/python3.6/urllib/request.py", line 1321, in do_open
    r = h.getresponse()
  File "/usr/lib64/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib64/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
2018-07-28 01:39:07 - widgetastic_null - ERROR - [ContentViewCreateView]: An exception happened during fill({'name': 'oyRUiVlMyE', 'composite_view': True}) call (elapsed 3177 ms)
2018-07-28 01:39:07 - widgetastic_null - ERROR - [ContentViewCreateView]: Remote end closed connection without response
Traceback (most recent call last):
  File "/home/jenkins/shiningpanda/jobs/54c9a7ae/virtualenvs/d41d8cd9/lib/python3.6/site-packages/widgetastic/log.py", line 117, in wrapped
    result = f(self, *args, **kwargs)
  File "/home/jenkins/shiningpanda/jobs/54c9a7ae/virtualenvs/d41d8cd9/lib/python3.6/site-packages/widgetastic/widget.py", line 41, in wrapped
    return method(self, Fillable.coerce(value), *args, **kwargs)
  File "/home/jenkins/shiningpanda/jobs/54c9a7ae/virtualenvs/d41d8cd9/lib/python3.6/site-packages/widgetastic/widget.py", line 786, in fill
    if widget.fill(value):
  File "/home/jenkins/shiningpanda/jobs/54c9a7ae/virtualenvs/d41d8cd9/lib/python3.6/site-packages/widgetastic/log.py", line 117, in wrapped
    result = f(self, *args, **kwargs)
  File "/home/jenkins/shiningpanda/jobs/54c9a7ae/virtualenvs/d41d8cd9/lib/python3.6/site-packages/widgetastic/widget.py", line 41, in wrapped
    return method(self, Fillable.coerce(value), *args, **kwargs)
  File "/home/jenkins/shiningpanda/jobs/54c9a7ae/virtualenvs/d41d8cd9/lib/python3.6/site-packages/widgetastic/widget.py", line 1138, in fill
    self.browser.click(self)
  File "/home/jenkins/shiningpanda/jobs/54c9a7ae/virtualenvs/d41d8cd9/lib/python3.6/site-packages/widgetastic/browser.py", line 354, in click
    el = self.move_to_element(locator, *args, **kwargs)
  File "/home/jenkins/shiningpanda/jobs/54c9a7ae/virtualenvs/d41d8cd9/lib/python3.6/site-packages/airgun/browser.py", line 605, in move_to_element
    ActionChains(self.selenium).move_to_element(el).perform()
  File "/home/jenkins/shiningpanda/jobs/54c9a7ae/virtualenvs/d41d8cd9/lib/python3.6/site-packages/selenium/webdriver/common/action_chains.py", line 83, in perform
    action()
  File "/home/jenkins/shiningpanda/jobs/54c9a7ae/virtualenvs/d41d8cd9/lib/python3.6/site-packages/selenium/webdriver/common/action_chains.py", line 293, in <lambda>
    Command.MOVE_TO, {'element': to_element.id}))
  File "/home/jenkins/shiningpanda/jobs/54c9a7ae/virtualenvs/d41d8cd9/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 310, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/home/jenkins/shiningpanda/jobs/54c9a7ae/virtualenvs/d41d8cd9/lib/python3.6/site-packages/selenium/webdriver/remote/remote_connection.py", line 466, in execute
    return self._request(command_info[0], url, body=data)
  File "/home/jenkins/shiningpanda/jobs/54c9a7ae/virtualenvs/d41d8cd9/lib/python3.6/site-packages/selenium/webdriver/remote/remote_connection.py", line 528, in _request
    resp = opener.open(request, timeout=self._timeout)
  File "/usr/lib64/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib64/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib64/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib64/python3.6/urllib/request.py", line 1321, in do_open
    r = h.getresponse()
  File "/usr/lib64/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib64/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
```

Fail in `tests.foreman.ui_airgun.test_provisioningtemplate.test_positive_clone` which says `selenium.common.exceptions.WebDriverException: Message: <html><body><h1>502 Bad Gateway</h1> The server returned an invalid or incomplete response. </body></html>` might be relevant as well.

**Comment by jhutar** [comment]
I assume this is some issue with infrastructure - how we run Selenium tests, but before just ignoring such an issue, wanted to ask somebody knowledgeable to review... @oshtaier  and @abalakh, please could you take a look?

**Comment by JacobCallahan** [comment]
Closing this issue since it has not been acted upon up until this point. Future component owners can reopen if they are going to address this.
