### ISSUE TITLE
Airgun Import Error when Running Robottelo in Python2.x

### ISSUE THREAD

**Issue by latran** [SatelliteQE/robottelo#6409]
```
Testing started at 10:54 AM ...
/home/ltran/Projects/robottelo/py2env/bin/python /app/pycharm/helpers/pycharm/_jb_unittest_runner.py --target test_setting.SettingTestCase.test_positive_update_hostname_default_prefix
Launching unittests with arguments python -m unittest test_setting.SettingTestCase.test_positive_update_hostname_default_prefix in /home/ltran/Projects/robottelo/tests/foreman/api

Traceback (most recent call last):
  File "/app/pycharm/helpers/pycharm/_jb_unittest_runner.py", line 35, in <module>
    main(argv=args, module=None, testRunner=unittestpy.TeamcityTestRunner, buffer=not JB_DISABLE_BUFFERING)
  File "/usr/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python2.7/unittest/loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "/home/ltran/Projects/robottelo/tests/foreman/api/test_setting.py", line 19, in <module>
    from robottelo.cleanup import setting_cleanup
  File "/home/ltran/Projects/robottelo/robottelo/cleanup.py", line 6, in <module>
    from robottelo.cli.base import CLIReturnCodeError
  File "/home/ltran/Projects/robottelo/robottelo/cli/base.py", line 6, in <module>
    from robottelo import ssh
  File "/home/ltran/Projects/robottelo/robottelo/ssh.py", line 14, in <module>
    from robottelo.config import settings
  File "/home/ltran/Projects/robottelo/robottelo/config/__init__.py", line 1, in <module>
    from robottelo.config.base import Settings
  File "/home/ltran/Projects/robottelo/robottelo/config/base.py", line 19, in <module>
    import airgun.settings
  File "/home/ltran/Projects/robottelo/py2env/lib/python2.7/site-packages/airgun/__init__.py", line 1, in <module>
    from airgun.settings import Settings
  File "/home/ltran/Projects/robottelo/py2env/lib/python2.7/site-packages/airgun/settings.py", line 4, in <module>
    from configparser import ConfigParser
ImportError: No module named configparser

Process finished with exit code 1
Empty test suite.
```

@SatelliteQE/robottelo-automation @oshtaier @abalakh @ldjebran - Do you guys plan on making airgun compatible with robottelo python2.x?

**Comment by abalakh** [comment]
@latran no plans, robottelo and airgun are python3 only

**Comment by oshtaier** [comment]
nope, it was compatible, but we removed support not so long ago

**Comment by oshtaier** [comment]
I meant robottelo had that support, airgun was python 3 only from the start
