### ISSUE TITLE
[6.4] test_positive_sync_custom_repo_puppet fails with ''NoneType' object has no attribute 'selenium''

### ISSUE THREAD

**Issue by vijay8451** [SatelliteQE/robottelo#6544]
'NoneType' object has no attribute 'selenium'
Traceback (most recent call last):
  File "/home/jenkins/shiningpanda/jobs/54c9a7ae/virtualenvs/d41d8cd9/lib/python3.6/site-packages/airgun/session.py", line 168, in __enter__
    selenium_browser = self._factory.get_browser()
  File "/home/jenkins/shiningpanda/jobs/54c9a7ae/virtualenvs/d41d8cd9/lib/python3.6/site-packages/airgun/browser.py", line 113, in get_browser
    return self._get_saucelabs_browser()
  File "/home/jenkins/shiningpanda/jobs/54c9a7ae/virtualenvs/d41d8cd9/lib/python3.6/site-packages/airgun/browser.py", line 261, in _get_saucelabs_browser
    desired_capabilities=desired_capabilities
  File "/home/jenkins/shiningpanda/jobs/54c9a7ae/virtualenvs/d41d8cd9/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 156, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/jenkins/shiningpanda/jobs/54c9a7ae/virtualenvs/d41d8cd9/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 251, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/jenkins/shiningpanda/jobs/54c9a7ae/virtualenvs/d41d8cd9/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/home/jenkins/shiningpanda/jobs/54c9a7ae/virtualenvs/d41d8cd9/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Sauce could not start your job. For more information on what happened, please visit https://saucelabs.com/jobs/ce509c2ea545485999c1e159baa942b5

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jenkins/shiningpanda/jobs/54c9a7ae/virtualenvs/d41d8cd9/lib/python3.6/site-packages/airgun/session.py", line 199, in __exit__
    self.take_screenshot()
  File "/home/jenkins/shiningpanda/jobs/54c9a7ae/virtualenvs/d41d8cd9/lib/python3.6/site-packages/airgun/session.py", line 232, in take_screenshot
    self.browser.selenium.save_screenshot(path)
AttributeError: 'NoneType' object has no attribute 'selenium'
2018-12-08 07:38:03
keyboard_arrow_down
self = &lt;airgun.session.Session object at 0x7fda852b02e8&gt;

    def __enter__(self):
        """Starts the browser, navigates to satellite, performs post-init
        browser tweaks, initializes navigator and UI entities, and logs in to
        satellite.
        """
        LOGGER.info(
            u'Starting UI session %r for user %r', self.name, self._user)
        self._factory = SeleniumBrowserFactory(test_name=self.name)
        try:
&gt; selenium_browser = self._factory.get_browser()

../../shiningpanda/jobs/54c9a7ae/virtualenvs/d41d8cd9/lib/python3.6/site-packages/airgun/session.py:168:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = &lt;airgun.browser.SeleniumBrowserFactory object at 0x7fda741b8eb8&gt;

    def get_browser(self):
        """Returns selenium webdriver instance of selected ``provider`` and
        ``browser``.
    
        :return: selenium webdriver instance
        :raises: ValueError: If wrong ``provider`` or ``browser`` specified.
        """
        if self.provider == 'selenium':
            return self._get_selenium_browser()
        elif self.provider == 'saucelabs':
&gt; return self._get_saucelabs_browser()

../../shiningpanda/jobs/54c9a7ae/virtualenvs/d41d8cd9/lib/python3.6/site-packages/airgun/browser.py:113:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = &lt;airgun.browser.SeleniumBrowserFactory object at 0x7fda741b8eb8&gt;

    def _get_saucelabs_browser(self):
        """Returns saucelabs webdriver instance of selected ``browser``.
    
        Note: should not be called directly, use :meth:`get_browser` instead.
    
        :raises: ValueError: If wrong ``browser`` specified.
        """
        if self.browser == 'chrome':
            desired_capabilities = webdriver.DesiredCapabilities.CHROME.copy()
            enable_downloading = {
                'chromeOptions': {
                    'args': ['disable-web-security'],
                    'prefs': {'download.prompt_for_download': False}
                }
            }
            desired_capabilities.update(enable_downloading)
            if settings.webdriver_desired_capabilities:
                desired_capabilities.update(
                    vars(settings.webdriver_desired_capabilities))
        elif self.browser == 'firefox':
            desired_capabilities = webdriver.DesiredCapabilities.FIREFOX.copy()
            if settings.webdriver_desired_capabilities:
                desired_capabilities.update(
                    vars(settings.webdriver_desired_capabilities))
        elif self.browser == 'ie':
            desired_capabilities = (
                webdriver.DesiredCapabilities.INTERNETEXPLORER.copy())
            if settings.webdriver_desired_capabilities:
                desired_capabilities.update(
                    vars(settings.webdriver_desired_capabilities))
        elif self.browser == 'edge':
            desired_capabilities = webdriver.DesiredCapabilities.EDGE.copy()
            desired_capabilities['acceptSslCerts'] = True
            desired_capabilities['javascriptEnabled'] = True
            if settings.webdriver_desired_capabilities:
                desired_capabilities.update(
                    vars(settings.webdriver_desired_capabilities))
        else:
            raise ValueError(
                '"{}" webdriver on saucelabs is currently not supported. '
                'Please use one of {}'
                .format(self.provider, ('chrome', 'firefox', 'ie', 'edge'))
            )
    
        self._webdriver = webdriver.Remote(
            command_executor=_sauce_ondemand_url(
                settings.selenium.saucelabs_user,
                settings.selenium.saucelabs_key
            ),
&gt; desired_capabilities=desired_capabilities
        )

../../shiningpanda/jobs/54c9a7ae/virtualenvs/d41d8cd9/lib/python3.6/site-packages/airgun/browser.py:261:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = &lt;selenium.webdriver.remote.webdriver.WebDriver (session="None")&gt;
command_executor = 'http://satellite6qe:391bc5fc-4102-42a2-aef9-676290869e32@ondemand.saucelabs.com:80/wd/hub'
desired_capabilities = {'browserName': 'chrome', 'build': 'Satellite 6.4.1-2.3', 'chromeOptions': {'args': ['disable-web-security'], 'prefs': {'download.prompt_for_download': False}}, 'idleTimeout': '1000', ...}
browser_profile = None, proxy = None, keep_alive = False, file_detector = None
options = None

    def __init__(self, command_executor='http://127.0.0.1:4444/wd/hub',
                 desired_capabilities=None, browser_profile=None, proxy=None,
                 keep_alive=False, file_detector=None, options=None):
        """
        Create a new driver that will issue commands using the wire protocol.
    
        :Args:
         - command_executor - Either a string representing URL of the remote server or a custom
             remote_connection.RemoteConnection object. Defaults to 'http://127.0.0.1:4444/wd/hub'.
         - desired_capabilities - A dictionary of capabilities to request when
             starting the browser session. Required parameter.
         - browser_profile - A selenium.webdriver.firefox.firefox_profile.FirefoxProfile object.
             Only used if Firefox is requested. Optional.
         - proxy - A selenium.webdriver.common.proxy.Proxy object. The browser session will
             be started with given proxy settings, if possible. Optional.
         - keep_alive - Whether to configure remote_connection.RemoteConnection to use
             HTTP keep-alive. Defaults to False.
         - file_detector - Pass custom file detector object during instantiation. If None,
             then default LocalFileDetector() will be used.
         - options - instance of a driver options.Options class
        """
        capabilities = {}
        if options is not None:
            capabilities = options.to_capabilities()
        if desired_capabilities is not None:
            if not isinstance(desired_capabilities, dict):
                raise WebDriverException("Desired Capabilities must be a dictionary")
            else:
                capabilities.update(desired_capabilities)
        if proxy is not None:
            warnings.warn("Please use FirefoxOptions to set proxy",
                          DeprecationWarning)
            proxy.add_to_capabilities(capabilities)
        self.command_executor = command_executor
        if type(self.command_executor) is bytes or isinstance(self.command_executor, str):
            self.command_executor = RemoteConnection(command_executor, keep_alive=keep_alive)
        self._is_remote = True
        self.session_id = None
        self.capabilities = {}
        self.error_handler = ErrorHandler()
        self.start_client()
        if browser_profile is not None:
            warnings.warn("Please use FirefoxOptions to set browser profile",
                          DeprecationWarning)
&gt; self.start_session(capabilities, browser_profile)

../../shiningpanda/jobs/54c9a7ae/virtualenvs/d41d8cd9/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py:156:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = &lt;selenium.webdriver.remote.webdriver.WebDriver (session="None")&gt;
capabilities = {'browserName': 'chrome', 'build': 'Satellite 6.4.1-2.3', 'chromeOptions': {'args': ['disable-web-security'], 'prefs': {'download.prompt_for_download': False}}, 'idleTimeout': '1000', ...}
browser_profile = None

    def start_session(self, capabilities, browser_profile=None):
        """
        Creates a new session with the desired capabilities.
    
        :Args:
         - browser_name - The name of the browser to request.
         - version - Which browser version to request.
         - platform - Which platform to request the browser on.
         - javascript_enabled - Whether the new session should support JavaScript.
         - browser_profile - A selenium.webdriver.firefox.firefox_profile.FirefoxProfile object. Only used if Firefox is requested.
        """
        if not isinstance(capabilities, dict):
            raise InvalidArgumentException("Capabilities must be a dictionary")
        if browser_profile:
            if "moz:firefoxOptions" in capabilities:
                capabilities["moz:firefoxOptions"]["profile"] = browser_profile.encoded
            else:
                capabilities.update({'firefox_profile': browser_profile.encoded})
        w3c_caps = _make_w3c_caps(capabilities)
        parameters = {"capabilities": w3c_caps,
                      "desiredCapabilities": capabilities}
&gt; response = self.execute(Command.NEW_SESSION, parameters)

../../shiningpanda/jobs/54c9a7ae/virtualenvs/d41d8cd9/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py:251:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = &lt;selenium.webdriver.remote.webdriver.WebDriver (session="None")&gt;
driver_command = 'newSession'
params = {'capabilities': {'alwaysMatch': {'browserName': 'chrome', 'browserVersion': '63.0', 'platformName': 'macos 10.12'}, '...ns': {'args': ['disable-web-security'], 'prefs': {'download.prompt_for_download': False}}, 'idleTimeout': '1000', ...}}

    def execute(self, driver_command, params=None):
        """
        Sends a command to be executed by a command.CommandExecutor.
    
        :Args:
         - driver_command: The name of the command to execute as a string.
         - params: A dictionary of named parameters to send with the command.
    
        :Returns:
          The command's JSON response loaded into a dictionary object.
        """
        if self.session_id is not None:
            if not params:
                params = {'sessionId': self.session_id}
            elif 'sessionId' not in params:
                params['sessionId'] = self.session_id
    
        params = self._wrap_value(params)
        response = self.command_executor.execute(driver_command, params)
        if response:
&gt; self.error_handler.check_response(response)

../../shiningpanda/jobs/54c9a7ae/virtualenvs/d41d8cd9/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py:320:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = &lt;selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7fda742534a8&gt;
response = {'status': 500, 'value': '{"status": 13, "sessionId": "ce509c2ea545485999c1e159baa942b5", "value": {"message": "Sauce ...b. For more information on what happened, please visit https://saucelabs.com/jobs/ce509c2ea545485999c1e159baa942b5"}}'}

    def check_response(self, response):
        """
        Checks that a JSON response from the WebDriver does not have an error.
    
        :Args:
         - response - The JSON response from the WebDriver server as a dictionary
           object.
    
        :Raises: If the response contains an error message.
        """
        status = response.get('status', None)
        if status is None or status == ErrorCode.SUCCESS:
            return
        value = None
        message = response.get("message", "")
        screen = response.get("screen", "")
        stacktrace = None
        if isinstance(status, int):
            value_json = response.get('value', None)
            if value_json and isinstance(value_json, basestring):
                import json
                try:
                    value = json.loads(value_json)
                    if len(value.keys()) == 1:
                        value = value['value']
                    status = value.get('error', None)
                    if status is None:
                        status = value["status"]
                        message = value["value"]
                        if not isinstance(message, basestring):
                            value = message
                            message = message.get('message')
                    else:
                        message = value.get('message', None)
                except ValueError:
                    pass
    
        exception_class = ErrorInResponseException
        if status in ErrorCode.NO_SUCH_ELEMENT:
            exception_class = NoSuchElementException
        elif status in ErrorCode.NO_SUCH_FRAME:
            exception_class = NoSuchFrameException
        elif status in ErrorCode.NO_SUCH_WINDOW:
            exception_class = NoSuchWindowException
        elif status in ErrorCode.STALE_ELEMENT_REFERENCE:
            exception_class = StaleElementReferenceException
        elif status in ErrorCode.ELEMENT_NOT_VISIBLE:
            exception_class = ElementNotVisibleException
        elif status in ErrorCode.INVALID_ELEMENT_STATE:
            exception_class = InvalidElementStateException
        elif status in ErrorCode.INVALID_SELECTOR \
                or status in ErrorCode.INVALID_XPATH_SELECTOR \
                or status in ErrorCode.INVALID_XPATH_SELECTOR_RETURN_TYPER:
            exception_class = InvalidSelectorException
        elif status in ErrorCode.ELEMENT_IS_NOT_SELECTABLE:
            exception_class = ElementNotSelectableException
        elif status in ErrorCode.ELEMENT_NOT_INTERACTABLE:
            exception_class = ElementNotInteractableException
        elif status in ErrorCode.INVALID_COOKIE_DOMAIN:
            exception_class = InvalidCookieDomainException
        elif status in ErrorCode.UNABLE_TO_SET_COOKIE:
            exception_class = UnableToSetCookieException
        elif status in ErrorCode.TIMEOUT:
            exception_class = TimeoutException
        elif status in ErrorCode.SCRIPT_TIMEOUT:
            exception_class = TimeoutException
        elif status in ErrorCode.UNKNOWN_ERROR:
            exception_class = WebDriverException
        elif status in ErrorCode.UNEXPECTED_ALERT_OPEN:
            exception_class = UnexpectedAlertPresentException
        elif status in ErrorCode.NO_ALERT_OPEN:
            exception_class = NoAlertPresentException
        elif status in ErrorCode.IME_NOT_AVAILABLE:
            exception_class = ImeNotAvailableException
        elif status in ErrorCode.IME_ENGINE_ACTIVATION_FAILED:
            exception_class = ImeActivationFailedException
        elif status in ErrorCode.MOVE_TARGET_OUT_OF_BOUNDS:
            exception_class = MoveTargetOutOfBoundsException
        elif status in ErrorCode.JAVASCRIPT_ERROR:
            exception_class = JavascriptException
        elif status in ErrorCode.SESSION_NOT_CREATED:
            exception_class = SessionNotCreatedException
        elif status in ErrorCode.INVALID_ARGUMENT:
            exception_class = InvalidArgumentException
        elif status in ErrorCode.NO_SUCH_COOKIE:
            exception_class = NoSuchCookieException
        elif status in ErrorCode.UNABLE_TO_CAPTURE_SCREEN:
            exception_class = ScreenshotException
        elif status in ErrorCode.ELEMENT_CLICK_INTERCEPTED:
            exception_class = ElementClickInterceptedException
        elif status in ErrorCode.INSECURE_CERTIFICATE:
            exception_class = InsecureCertificateException
        elif status in ErrorCode.INVALID_COORDINATES:
            exception_class = InvalidCoordinatesException
        elif status in ErrorCode.INVALID_SESSION_ID:
            exception_class = InvalidSessionIdException
        elif status in ErrorCode.UNKNOWN_METHOD:
            exception_class = UnknownMethodException
        else:
            exception_class = WebDriverException
        if value == '' or value is None:
            value = response['value']
        if isinstance(value, basestring):
            if exception_class == ErrorInResponseException:
                raise exception_class(response, value)
            raise exception_class(value)
        if message == "" and 'message' in value:
            message = value['message']
    
        screen = None
        if 'screen' in value:
            screen = value['screen']
    
        stacktrace = None
        if 'stackTrace' in value and value['stackTrace']:
            stacktrace = []
            try:
                for frame in value['stackTrace']:
                    line = self._value_or_default(frame, 'lineNumber', '')
                    file = self._value_or_default(frame, 'fileName', '&lt;anonymous&gt;')
                    if line:
                        file = "%s:%s" % (file, line)
                    meth = self._value_or_default(frame, 'methodName', '&lt;anonymous&gt;')
                    if 'className' in frame:
                        meth = "%s.%s" % (frame['className'], meth)
                    msg = " at %s (%s)"
                    msg = msg % (meth, file)
                    stacktrace.append(msg)
            except TypeError:
                pass
        if exception_class == ErrorInResponseException:
            raise exception_class(response, message)
        elif exception_class == UnexpectedAlertPresentException:
            alert_text = None
            if 'data' in value:
                alert_text = value['data'].get('text')
            elif 'alert' in value:
                alert_text = value['alert'].get('text')
            raise exception_class(message, screen, stacktrace, alert_text)
&gt; raise exception_class(message, screen, stacktrace)
E selenium.common.exceptions.WebDriverException: Message: Sauce could not start your job. For more information on what happened, please visit https://saucelabs.com/jobs/ce509c2ea545485999c1e159baa942b5

../../shiningpanda/jobs/54c9a7ae/virtualenvs/d41d8cd9/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py:242: WebDriverException

During handling of the above exception, another exception occurred:

session = &lt;airgun.session.Session object at 0x7fda852b02e8&gt;
module_org = nailgun.entities.Organization(compute_resource=[], config_template=[nailgun.entities.ConfigTemplate(id=10), nailgun.en...fault_content_view=nailgun.entities.ContentView(id=737), library=nailgun.entities.LifecycleEnvironment(id=576), id=576)

    @tier2
    @upgrade
    def test_positive_sync_custom_repo_puppet(session, module_org):
        """Create Custom puppet repos and sync it via the repos page.
    
        :id: 135176cc-7664-41ee-8c41-b77e193f2f22
    
        :expectedresults: Sync procedure for specific puppet repository is
            successful
    
        :CaseLevel: Integration
        """
        product = entities.Product(organization=module_org).create()
        repo = entities.Repository(
            url=FAKE_0_PUPPET_REPO,
            product=product,
            content_type=REPO_TYPE['puppet'],
        ).create()
&gt; with session:

tests/foreman/ui_airgun/test_repository.py:348:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../shiningpanda/jobs/54c9a7ae/virtualenvs/d41d8cd9/lib/python3.6/site-packages/airgun/session.py:181: in __enter__
    self.__exit__(*sys.exc_info())
../../shiningpanda/jobs/54c9a7ae/virtualenvs/d41d8cd9/lib/python3.6/site-packages/airgun/session.py:203: in __exit__
    self._factory.finalize(passed)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = &lt;airgun.browser.SeleniumBrowserFactory object at 0x7fda741b8eb8&gt;
passed = False

    def finalize(self, passed=True):
        """Finalize browser - close browser window, report results to saucelabs
        or close docker container if needed.
    
        :param bool passed: Boolean value indicating whether test passed
            or not. Is only used for ``saucelabs`` provider.
        :return: None
        """
        if self.provider == 'selenium':
            self._webdriver.quit()
            return
        elif self.provider == 'saucelabs':
&gt; self._webdriver.quit()
E AttributeError: 'NoneType' object has no attribute 'quit'

../../shiningpanda/jobs/54c9a7ae/virtualenvs/d41d8cd9/lib/python3.6/site-packages/airgun/browser.py:154: AttributeError

**Comment by vijay8451** [comment]
same test case run fine during manual run so worth to wait till next snap push.
