### ISSUE TITLE
unable to run pytest after installing content of requirements-optional.txt 

### ISSUE THREAD

**Issue by jameerpathan111** [SatelliteQE/robottelo#6902]
I am trying to setup robottelo environment.
Everything works fine if I just install content of `requirements.txt`, but 
when I also install `requirements-optional.txt` then I get below given traceback.

```
(env-robottelo2) [jpathan@jpathan robottelo]$ pytest tests/foreman/cli/test_ping.py -svvv
Traceback (most recent call last):
  File "/home/jpathan/projects/env-robottelo2/lib64/python3.6/site-packages/pluggy/manager.py", line 274, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/home/jpathan/projects/env-robottelo2/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2433, in load
    self.require(*args, **kwargs)
  File "/home/jpathan/projects/env-robottelo2/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2456, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/jpathan/projects/env-robottelo2/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (pytest 4.0.2 (/home/jpathan/projects/env-robottelo2/lib/python3.6/site-packages), Requirement.parse('pytest>=4.4.0'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jpathan/projects/env-robottelo2/bin/pytest", line 11, in <module>
    sys.exit(main())
  File "/home/jpathan/projects/env-robottelo2/lib64/python3.6/site-packages/_pytest/config/__init__.py", line 58, in main
    config = _prepareconfig(args, plugins)
  File "/home/jpathan/projects/env-robottelo2/lib64/python3.6/site-packages/_pytest/config/__init__.py", line 196, in _prepareconfig
    pluginmanager=pluginmanager, args=args
  File "/home/jpathan/projects/env-robottelo2/lib64/python3.6/site-packages/pluggy/hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/jpathan/projects/env-robottelo2/lib64/python3.6/site-packages/pluggy/manager.py", line 68, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/jpathan/projects/env-robottelo2/lib64/python3.6/site-packages/pluggy/manager.py", line 62, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/jpathan/projects/env-robottelo2/lib64/python3.6/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/home/jpathan/projects/env-robottelo2/lib64/python3.6/site-packages/_pytest/helpconfig.py", line 93, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/home/jpathan/projects/env-robottelo2/lib64/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/jpathan/projects/env-robottelo2/lib64/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/jpathan/projects/env-robottelo2/lib64/python3.6/site-packages/_pytest/config/__init__.py", line 675, in pytest_cmdline_parse
    self.parse(args)
  File "/home/jpathan/projects/env-robottelo2/lib64/python3.6/site-packages/_pytest/config/__init__.py", line 854, in parse
    self._preparse(args, addopts=addopts)
  File "/home/jpathan/projects/env-robottelo2/lib64/python3.6/site-packages/_pytest/config/__init__.py", line 808, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/home/jpathan/projects/env-robottelo2/lib64/python3.6/site-packages/pluggy/manager.py", line 280, in load_setuptools_entrypoints
    message="Plugin %r could not be loaded: %s!" % (ep.name, e),
pluggy.manager.PluginValidationError: Plugin 'xdist' could not be loaded: (pytest 4.0.2 (/home/jpathan/projects/env-robottelo2/lib/python3.6/site-packages), Requirement.parse('pytest>=4.4.0'))!
```
- Currently I am commenting out `pytest-xdist` module listed in `requirements-optional.txt` as a work around. 
- If someone can tell how to resolve this problem then that would be great.

**Comment by ntkathole** [comment]
@jameerpathan111 We are using old pytest and requirement-optional will fetch latest pytest-xdist which is not compatible. In our automation we have tag it with` pytest-xdist==1.25.0` 
https://github.com/SatelliteQE/robottelo-ci/blob/master/scripts/satellite6-standalone-automation.sh#L6

**Comment by vijay8451** [comment]
@ntkathole can not we tag the version in requirement-optional?

**Comment by ntkathole** [comment]
@vijay8451 yes we can. @jameerpathan111 feel free raise PR for this!
