### ISSUE TITLE
[Regression] There is no such setting as settings.server.version

### ISSUE THREAD

**Issue by ntkathole** [SatelliteQE/robottelo#7476]
https://github.com/SatelliteQE/robottelo/blob/b16661c1eeb851c311fec33dd8e99e58ba39101c/robottelo/helpers.py#L929

We are missing server version settings in robottelo properties sample in robottelo as well as robottelo properties from gitlab.

```
pytest tests/foreman/cli/test_auth.py 
============================================================== test session starts ===============================================================
platform linux -- Python 3.6.3, pytest-4.6.3, py-1.8.0, pluggy-0.13.0
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/nkathole/satQE/robottelo
plugins: mock-1.10.4, services-1.3.1
collecting ... 2019-11-13 08:02:31 - conftest - DEBUG - Collected 9 test cases

collected 9 items                                                                                                                                
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/nkathole/satQE/robottelo/env/lib64/python3.6/site-packages/_pytest/main.py", line 206, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/home/nkathole/satQE/robottelo/env/lib64/python3.6/site-packages/_pytest/main.py", line 249, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "/home/nkathole/satQE/robottelo/env/lib64/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/nkathole/satQE/robottelo/env/lib64/python3.6/site-packages/pluggy/manager.py", line 92, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/nkathole/satQE/robottelo/env/lib64/python3.6/site-packages/pluggy/manager.py", line 86, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/home/nkathole/satQE/robottelo/env/lib64/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/nkathole/satQE/robottelo/env/lib64/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/nkathole/satQE/robottelo/env/lib64/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/nkathole/satQE/robottelo/env/lib64/python3.6/site-packages/_pytest/main.py", line 259, in pytest_collection
INTERNALERROR>     return session.perform_collect()
INTERNALERROR>   File "/home/nkathole/satQE/robottelo/env/lib64/python3.6/site-packages/_pytest/main.py", line 498, in perform_collect
INTERNALERROR>     session=self, config=self.config, items=items
INTERNALERROR>   File "/home/nkathole/satQE/robottelo/env/lib64/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/nkathole/satQE/robottelo/env/lib64/python3.6/site-packages/pluggy/manager.py", line 92, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/nkathole/satQE/robottelo/env/lib64/python3.6/site-packages/pluggy/manager.py", line 86, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/home/nkathole/satQE/robottelo/env/lib64/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/nkathole/satQE/robottelo/env/lib64/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/nkathole/satQE/robottelo/env/lib64/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/nkathole/satQE/robottelo/tests/foreman/conftest.py", line 132, in pytest_collection_modifyitems
INTERNALERROR>     pytest.issue_data = generate_issue_collection(items, config)
INTERNALERROR>   File "/home/nkathole/satQE/robottelo/robottelo/helpers.py", line 929, in generate_issue_collection
INTERNALERROR>     "version": settings.server.version,
INTERNALERROR>   File "/home/nkathole/satQE/robottelo/robottelo/config/base.py", line 170, in version
INTERNALERROR>     self._version = get_sat_version()
INTERNALERROR>   File "/home/nkathole/satQE/robottelo/robottelo/host_info.py", line 170, in get_sat_version
INTERNALERROR>     return Version(os.environ.get('SAT_VERSION') or get_host_sat_version())
INTERNALERROR>   File "/home/nkathole/satQE/robottelo/robottelo/host_info.py", line 51, in get_host_sat_version


========================================================== no tests ran in 0.12 seconds ====================================================
```

**Comment by ntkathole** [comment]
regression from https://github.com/SatelliteQE/robottelo/pull/7404

**Comment by mirekdlugosz** [comment]
`server.version` is not really supposed to be in robottelo.properties - it is property that will try to read env variable `SAT_VERSION` or call `robottelo.host_info.get_host_sat_version`.

In your case, it tried calling this last function, but looks like something was wrong with your connection at this point of time.

**Comment by ntkathole** [comment]
I am curious even if bugzilla settings are disabled, generate_issue_collection function should not be called.
https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/conftest.py#L132

**Comment by mirekdlugosz** [comment]
From what I see, `generate_issue_collection` is called unconditionally. It calls `robottelo.issue_handlers.bugzilla.collect_data_bz`, which will return empty data structures if bugzilla settings are disabled. If I remember correctly, reported issue that resulted in this addition was about crash when bugzilla settings are not there, disabling entire `generate_issue_collection` was not a part of conversation (probably because in the future we might have bugzilla, redmine and github, and disabling bugzilla shouldn't disable others).

@rochacbruno is better suited to answer all questions here.

**Comment by rochacbruno** [comment]
Even when the Bugzilla settings are not there we can use the bz_cache.json file with previous fetched data.

To decide if a BZ is open we need to know the version of the system we are running against.

I am open for suggestion of which default we should assume if we cannot talk to sat system bur right now the solution is to export SAT_VERSION variable.

**Comment by ntkathole** [comment]
Thanks @rochacbruno for clarification. Issue resolved for me.
