### ISSUE TITLE
Get error when installing pycurl through pip install -r requirement.txt

### ISSUE THREAD

**Issue by hkx303** [SatelliteQE/robottelo#7548]
**Description**
Follow the [document ](https://robottelo.readthedocs.io/en/latest/index.html)to build a new environment in Fedora-31
Steps:
`dnf install -y gcc git libffi-devel openssl-devel python-devel redhat-rpm-config`
`git clone git://github.com/SatelliteQE/robottelo.git`
`pip install -r requirements.txt`

Got error:
```
Collecting pycurl
  Using cached https://files.pythonhosted.org/packages/ac/b3/0f3979633b7890bab6098d84c84467030b807a1e2b31f5d30103af5a71ca/pycurl-7.43.0.3.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /home/hkx303/env/robotenv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4il7g9t9/pycurl/setup.py'"'"'; __file__='"'"'/tmp/pip-install-4il7g9t9/pycurl/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-4il7g9t9/pycurl/pip-egg-info
         cwd: /tmp/pip-install-4il7g9t9/pycurl/
    Complete output (22 lines):
    Traceback (most recent call last):
      File "/tmp/pip-install-4il7g9t9/pycurl/setup.py", line 229, in configure_unix
        stdout=subprocess.PIPE, stderr=subprocess.PIPE)
      File "/usr/lib64/python3.7/subprocess.py", line 800, in __init__
        restore_signals, start_new_session)
      File "/usr/lib64/python3.7/subprocess.py", line 1551, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'curl-config': 'curl-config'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-4il7g9t9/pycurl/setup.py", line 944, in <module>
        ext = get_extension(sys.argv, split_extension_source=split_extension_source)
      File "/tmp/pip-install-4il7g9t9/pycurl/setup.py", line 606, in get_extension
        ext_config = ExtensionConfiguration(argv)
      File "/tmp/pip-install-4il7g9t9/pycurl/setup.py", line 101, in __init__
        self.configure()
      File "/tmp/pip-install-4il7g9t9/pycurl/setup.py", line 233, in configure_unix
        raise ConfigurationError(msg)
    __main__.ConfigurationError: Could not run curl-config: [Errno 2] No such file or directory: 'curl-config': 'curl-config'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Workaround**
In Fedora, we should also install libcurl-devel
Run the following command, works fine.
`dnf install libcurl-devel`

**Comment by ntkathole** [comment]
We have it added in documentation https://github.com/SatelliteQE/robottelo/blob/master/docs/index.rst 
It is just that readthedocs is not updated

**Comment by hkx303** [comment]
> We have it added in documentation https://github.com/SatelliteQE/robottelo/blob/master/docs/index.rst
> It is just that readthedocs is not updated

oh, didn't notice that, yes,  I got the link through [README.rst](https://github.com/SatelliteQE/robottelo/edit/master/README.rst), so why don't we update the readme docs as well?
