### ISSUE TITLE
target_sat.api.Media behaves differently then entities.Media

### ISSUE THREAD

**Issue by pondrejk** [SatelliteQE/robottelo#9690]
Wrestling with automation failure for test_positive_rename_satellite in sys/test_rename.py:
```
media = target_sat.api.Media(organization=[module_org], path_=url).create()
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/pondrejk/.local/lib/python3.10/site-packages/nailgun/entities.py", line 4927, in create
    id=self.create_json(create_missing)['id'],
  File "/home/pondrejk/.local/lib/python3.10/site-packages/nailgun/entity_mixins.py", line 920, in create_json
    response.raise_for_status()
  File "/usr/lib/python3.10/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://target-sat-hostname.com/api/v2/media
```

In a debug session, trying to create media with the same line fails, but trying it out with entities succeeds:

```
from nailgun import entities
media = entities.Media(organization=[module_org], path_=url).create()
-> nailgun.entities.Media(path_='https://SFgSnDLXEB.gov', name='UlgbmQArXkHE', operatingsystem=[], organization=[nailgun.entities.Organization(id=8)], location=[nailgun.entities.Location(id=2)], os_family=None, id=16)
```

**Comment by pondrejk** [comment]
more info:
the error is due to the fact that module_org is not being created on a target_sat, test def goes like:

```
@pytest.mark.destructive
def test_positive_rename_satellite(self, module_org, module_product, target_sat):
```
Action item -- make sure the module_org fixture uses target_sat object
